### ISSUE TITLE
`ErrorInvalidJump` bug

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-circuits#1004]
`JUMPI` does an extra stack pop, so the `rw_offset` of `RestoreContextGadget` also needs to be adjusted.

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/03dff55e7ab044f53f8bdd0592e8e0df31bd64a3/zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs#L226-L227

```diff
         self.restore_context 
-             .assign(region, offset, block, call, step, 2)?; 
+             .assign(region, offset, block, call, step, 2 + is_jumpi as usize)?;
```

**Comment by DreamWuGit** [comment]
I will fix this, currently only have internal call test for jump , no internal test for jumpi.
