### ISSUE TITLE
Keccak Challenge API Soundness Bug

### ISSUE THREAD

**Issue by jonathanpwang** [privacy-scaling-explorations/zkevm-circuits#1016]
I may be missing something, but it seems to me that there is a soundness error with the current use of Challenge API in Keccak. I ran the keccak bench code and it also failed to verify, so that gave me some encouragement to file this. 

The error I think is this: currently there are gates for "intermediate data rlc" that uses intermediate cells `data_rlcs` to keep the gate degree low. However these `data_rlcs` are managed by the `cell_manager`. All columns of the cell manager are in `FirstPhase`! So these intermediate `data_rlcs` are all in `FirstPhase` advice, which will remain `Value::unknown()` since their computation requires the challenge value in `SecondPhase`. 

The solution is probably to just put the intermediate data rlcs into the `KeccakTable` and have separate gate logic outside of `cell_manager` for it. If I see an easy way to do this I'll make a PR later.

@CPerezz @han0110

**Comment by CPerezz** [comment]
Hi @jonathanpwang thanks for mentioning this! 
Ye, you're probably right as the `CellManager` is giving the same exact issues in the EVMCircuit. We're probably going to get ridd of the randomness in the future.

In the EVM CellManager we managed to include Phase2 column support. But here I'm not sure if it's worth the effort.



What is interesting is that the bench code fails. Since our integration tests are passing with random ETH blocks. Are you in `main` at latest commit while running them?

**Comment by CPerezz** [comment]
@jonathanpwang WDYT  about the solution in d9c7a1d6??

Should be as simple as that IMO. Although of course could be solved much better and on a scalable way. But I don't think is worth the effort considering we might migrate to a `hi-low` limb approach to avoid RLCs and specifically these kind of soundness issues

**Comment by jonathanpwang** [comment]
I was actually thinking of an even more specialized fix where the intermediate rlcs are kept in the `data_rlc` column of `KeccakTable`, so your fix looks good if it's more in line with the EVM CellManager.

I did do a hard reset to `main` and then run `DEGREE=16 make packed_multi_keccak_bench`. 
I just did `git checkout` on https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/3587b0824db7cd1184ff2140ece6eadb5eccb2d7 and ran the bench command but it still fails to verify with `ConstraintSystemFailure`. Is it working locally for you?

**Comment by CPerezz** [comment]
> I was actually thinking of an even more specialized fix where the intermediate rlcs are kept in the `data_rlc` column of `KeccakTable`

This looks really nice TBH! But I was unsure it'll be worth enough. I think what we can do is:
1. Keep https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/3587b0824db7cd1184ff2140ece6eadb5eccb2d7 and merge it to fix the soundness issues via the naive way.
2. Fix https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/974 which will allow us to test the Keccak circuit and get the exact failing errors!
3. Address this issue and fix the circuit.
4. In the future, keep an eye on this. As I do also think that there are some places where we need to bench more and get to the perfect col/row ratio.

**Comment by jonathanpwang** [comment]
I agree with your suggested roadmap. It would be a great test of 2 if it can help debug this issue.

> I was actually thinking of an even more specialized fix where the intermediate rlcs are kept in the data_rlc column of `KeccakTable` 
Just FYI, I did implement this version here https://github.com/jonathanpwang/zkevm-circuits/tree/keccak-only-subtree because I needed it for some other purpose. (And the real prover passes verify test.) But as previously mentioned it requires `rows_per_round >= 9`, which is not flexible enough as a main fix.

**Comment by CPerezz** [comment]
> I agree with your suggested roadmap. It would be a great test of 2 if it can help debug this issue.
> 
> > I was actually thinking of an even more specialized fix where the intermediate rlcs are kept in the data_rlc column of `KeccakTable`
> 
> Just FYI, I did implement this version here https://github.com/jonathanpwang/zkevm-circuits/tree/keccak-only-subtree because I needed it for some other purpose. (And the real prover passes verify test.) But as previously mentioned it requires `rows_per_round >= 9`, which is not flexible enough as a main fix.

Thanks so much for this! Let us consider the inclusion of your re-design anyways! Will discuss it in the next call and be back to you!
In any case, thanks for sharing this!!!!

**Comment by CPerezz** [comment]
Seems that any of these [26 commits](https://github.com/pinkiebell/zkevm-circuits/compare/zkevm-chain...privacy-scaling-explorations:zkevm-circuits:main) caused the bench failures. As the integration tests are running on a previous `zkevm-circuits` commit.

**Comment by CPerezz** [comment]
After discussing with @ed255 this will be left unfixed until we have decided if the next milestone will impl Hi-Lo and therefore, we can save the refactor that the ChallengeAPI correct usage implies for the keccak `CellManager`.

**Comment by naure** [comment]
Update: there is [a solution](https://github.com/scroll-tech/zkevm-circuits/pull/308) in Scroll’s fork that can be ported upstream. It is most similar to this [comment ](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1016#issuecomment-1366785915) above, meaning no change in CellManager but rather utilizing free space in the table.

**Comment by ed255** [comment]
> Update: there is [a solution](https://github.com/scroll-tech/zkevm-circuits/pull/308) in Scroll’s fork that can be ported upstream. It is most similar to this [comment ](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1016#issuecomment-1366785915) above, meaning no change in CellManager but rather utilizing free space in the table.

That's great! I just saw your PR from a comment lispc made here https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1224#issuecomment-1439850073 

I think it would be great to have that solution in our repo as well, so a PR will be very welcomed!
@CPerezz you may be interested in following this.

**Comment by CPerezz** [comment]
Count on it @ed255 !

Thanks for pinging @naure with the solution.

**Comment by naure** [comment]
@CPerezz I will handle the port.

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1315
