### ISSUE TITLE
Documentation: AbsWord Gadget Edge Case

### ISSUE THREAD

**Issue by kcharbo3** [privacy-scaling-explorations/zkevm-circuits#1021]
A current edge case for the AbsWord gadget occurrs when:

`x = 2^255`

so `x_abs = 2^255` which is a negative number, but for signed 256 bit integers, there is no corresponding positive number. The upstream SDIV/SMOD gadget (that uses this AbsWord gadget) does take this behavior into account, as seen by this comment:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/325a58f9522a78c9ab3146d80b08886ab1b1c76f/zkevm-circuits/src/evm_circuit/execution/sdiv_smod.rs#L89-L94

So, I think it would also be great to include a comment describing this behavior in this AbsWord gadget itself.

**Comment by silathdiir** [comment]
We have discussion https://github.com/privacy-scaling-explorations/zkevm-specs/pull/213#discussion_r891319233 for this special case in `SDIV` spec PR. And it seems better to also add comment to `AbsWordGadget`.

<img width="1359" alt="sdiv" src="https://user-images.githubusercontent.com/31645658/210681718-3f6be1c7-de26-4cc9-acae-c2dcecef775d.png">
