### ISSUE TITLE
Implement bytecode refactor spec in circuit

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/zkevm-circuits#1026]
We have done the following refactor to the spec:

https://github.com/privacy-scaling-explorations/zkevm-specs/issues/151

https://github.com/privacy-scaling-explorations/zkevm-specs/pull/340

https://github.com/privacy-scaling-explorations/zkevm-specs/pull/351

This task is to implement this new spec into the bytecode circuit implementation in this repo.

**Comment by aguzmant103** [comment]
- Improving readability by expressing it as a state machine
- Changing constraints in the bytecode circuit and adjustments on some columns of the witness generation
- This will include before and after benchmarks just to make sure we're not regressing in performance
- Using RLC (prev code was already using it too)
