### ISSUE TITLE
Account/Storage non-existence handling

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1029]
Once https://github.com/privacy-scaling-explorations/zkevm-specs/issues/259 is resolved, update the circuits to match the spec approach.

## Storage
- [x] State Circuit: apply mapping to NonExisting storage MPT proof

## Account
- [x] State Circuit: apply mapping to NonExisting account MPT proof
- EVM Circuit: use `code_hash == 0` as non-existing account check
  - [x] BALANCE
  - [x] EXTCODEHASH
  - [ ] EXTCODECOPY https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1067
  - [x] EXTCODESIZE
  - [x] CALLCODE
  - [x] DELEGATECALL
  - [x] STATICCALL
  - [x] CALL

**Comment by silathdiir** [comment]
It seems that there are on-going discussions in https://github.com/privacy-scaling-explorations/zkevm-specs/pull/345 and https://hackmd.io/5FHDL-6RSRCOd5l_GMndZA.

Should we apply new changes in spec first? Thanks.

**Comment by ed255** [comment]
> It seems that there are on-going discussions in [privacy-scaling-explorations/zkevm-specs#345](https://github.com/privacy-scaling-explorations/zkevm-specs/pull/345) and https://hackmd.io/5FHDL-6RSRCOd5l_GMndZA.
> 
> Should we apply new changes in spec first? Thanks.

Yes! I opened this issue just to track the changes that will need to be done in the circuits, but we can only proceed once the spec is updated.  As for the updates in the spec, I'll extend the issue now with more details.

**Comment by ed255** [comment]
This PR will resolve this issue except for EXTCODECOPY: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1046
