### ISSUE TITLE
bug: extcodesize inconsistency rlc<->value

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1037]
it is wrong.

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/69c0a4a2b10aade85e8f44f21e1bdb2be842b2e1/zkevm-circuits/src/evm_circuit/execution/extcodesize.rs#L68

we never call cb.stack_push with the "real" value. We cb.stack_push RLCed value.

Any code longer than 0xff can fail.

**Comment by silathdiir** [comment]
Please help assign this issue to me. Thanks.
Suppose to fix field `code_size` to type `Word`, and will debug with a test case of `Bytes::from([0x30; 256])` (logger than `0xff`).
