### ISSUE TITLE
bug: behavior inconsistency between evm and circuits for address range

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1041]
in evm, it is valid to pass U256 value larger than U160 as address in opcodes like extcodesize/extcodehash, only the last 20bytes is used and the first 12bytes are ignored.

in current circuit, this behavior is not described, resulting some valid traces not accepted.

**Comment by lispc** [comment]
need something like this

**Comment by silathdiir** [comment]
I guess it may be caused by the first 12-bytes of address are not zero. And may fail on `stack_pop(address.expr())` in `configure`. Will confirm, thanks.

**Comment by lispc** [comment]
oh i forget paste my patch @silathdiir  

https://github.com/scroll-tech/zkevm-circuits/commit/fa36737d8c5bc5e465431229f98f61595cd9debb
