### ISSUE TITLE
Testool: nighlty suite fails to generate reports

### ISSUE THREAD

**Issue by ntampakas** [privacy-scaling-explorations/zkevm-circuits#1045]
It seems that testool stopped to compare the results with the previous commit, so the reports cannot be generated.
This happens when running the **nightly** suite. Tested **light** suite and it works just fine.

Environment: Jenkins
Tool: Testool
Parameters:
  suite: nightly
  report: true
  
  Best,
  Nick

**Comment by aguzmant103** [comment]
- It is probably about a configuration file or a parameter or memory problems.

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1070
