### ISSUE TITLE
Proof Generation for evm circuit fails with Error:InvalidInstances

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-circuits#1050]
zkevm-chain commit: dfe9cc5717b7f248b644715b00726cc340adcce6
circuits commit: "https://github.com/pinkiebell/zkevm-circuits.git", branch = "zkevm-chain"

logs & traces : https://zkevm-chain-testing.s3.eu-central-1.amazonaws.com/proveSingeCrossChainTx_evm_False_55-maronis.tar.gz

**Comment by CPerezz** [comment]
`InvalidInstances` is always usually the same error. We are not passing the correct amount of Instance vectors or empty ones.
Same applies for #1051 and #1052.

We need to check https://github.com/privacy-scaling-explorations/zkevm-chain/commit/dfe9cc5717b7f248b644715b00726cc340adcce6 and see if the commit has the latest version of `zkevm-circuits` and also, if the instances are being passed correctly.

**Comment by AronisAt79** [comment]
Proof generation for evm curcuit is now successfull

tested on zkevm-chain commit: 6cdd88644cfe87a7f640cc279c54a44b93bbf0fa
Full logs:
https://zkevm-chain-testing.s3.eu-central-1.amazonaws.com/proveSingeCrossChainTx_evm_True_326-timer.tar.gz
