### ISSUE TITLE
Proof Generation for copy circuit fails with Error:InvalidInstances

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-circuits#1051]
zkevm-chain commit: dfe9cc5717b7f248b644715b00726cc340adcce6
circuits commit: "https://github.com/pinkiebell/zkevm-circuits.git", branch = "zkevm-chain"

logs & traces: https://zkevm-chain-testing.s3.eu-central-1.amazonaws.com/proveSingeCrossChainTx_copy_False_59-maronis.tar.gz

**Comment by aguzmant103** [comment]
@ChihChengLiang will check the logs and extract useful information on how to proceed.

**Comment by ChihChengLiang** [comment]
Same as #1050 and #1052. Without the information of circuits and inputs, it is not possible to trace the bug.

**Comment by CPerezz** [comment]
I think in order to resolve this, we need to check how the code is written in `zkevm-chain`.

**Comment by aguzmant103** [comment]
@ChihChengLiang  will give another look to analyze what strategy we can take in the circuit codebase side.

Note: it seems one of the circuits might not have a correct assign instance function. We could add some block tracing somewhere
- Every time we generate a proof, the errors from Halo2 are not as meaningful. 
- One approach is to add more logs to Halo2

**Comment by CPerezz** [comment]
Both things mentioned above @aguzmant103 @ChihChengLiang will be solved by adding more column annotations and using `prover.assert_verify` once #1085 is merged

**Comment by ChihChengLiang** [comment]
@CPerezz, I Agree with you. With https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1085 merged, what do you think we close #1050, #1051, and #1052 and wait for the next report?

**Comment by CPerezz** [comment]
I don't think so @ChihChengLiang. These will still fail unless we check how `zkevm-chain` is passing instances there.
@pinkiebell  mentioned:
>That should only happen on the sub circuits i.e only state or evm circuit that doesn't return valid values on fn instance()

So I think we can take a look to these and see why they're not behaving correctly.
Do you want me to take this work??

**Comment by ChihChengLiang** [comment]
Yeah, feel free to take this. Thank you @CPerezz

**Comment by ed255** [comment]
> I don't think so @ChihChengLiang. These will still fail unless we check how `zkevm-chain` is passing instances there. @pinkiebell mentioned:
> 
> > That should only happen on the sub circuits i.e only state or evm circuit that doesn't return valid values on fn instance()
> 
> So I think we can take a look to these and see why they're not behaving correctly. Do you want me to take this work??

I'm currently working on a PR that should make sure that all `fn instance()` of every circuit works correctly.  This is the issue https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1099 and the approach is to run the tests for all circuits the same way, using a generic function over `SubCircuit` and always calling `SubCircuit.instance()` to generate the instance vectors.

**Comment by CPerezz** [comment]
Ping me @ed255 once is merged so that I can verify that it works in zkevm-chain

**Comment by ed255** [comment]
> Ping me @ed255 once is merged so that I can verify that it works in zkevm-chain

ping! https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1104 has been merged :)

**Comment by AronisAt79** [comment]
tested on zkevm-chain 6cdd88644cfe87a7f640cc279c54a44b93bbf0fa. Proof generation now succeeds.
Full logs at https://zkevm-chain-testing.s3.eu-central-1.amazonaws.com/proveSingeCrossChainTx_copy_True_330-timer.tar.gz
