### ISSUE TITLE
Proof generation for tx circuit fails with: Error:InvalidInstances

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-circuits#1052]
zkevm-chain commit: dfe9cc5717b7f248b644715b00726cc340adcce6
circuits commit: "https://github.com/pinkiebell/zkevm-circuits.git", branch = "zkevm-chain"

logs & traces: https://zkevm-chain-testing.s3.eu-central-1.amazonaws.com/proveSingeCrossChainTx_tx_False_57-maronis.tar.gz

**Comment by aguzmant103** [comment]
@ChihChengLiang will check the logs and extract useful information on how to proceed.

**Comment by ChihChengLiang** [comment]
This one has nothing traceable other than invalid instances. It would be helpful to know what inputs are fed into what circuits. cc @pinkiebell 

https://github.com/privacy-scaling-explorations/zkevm-chain/blob/68982510b93fd34e06f5d2f444a3807b90668b40/prover/src/utils.rs#L63

**Comment by pinkiebell** [comment]
I think that is due the tx circuit doesn't have a proper `fn instance` implemented yet.

**Comment by CPerezz** [comment]
Could you fill an issue in the repo to include them?? @pinkiebell

**Comment by ed255** [comment]
> I think that is due the tx circuit doesn't have a proper `fn instance` implemented yet.

This is correct!  I fixed it here https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1104

@pinkiebell Once that PR is merged, the zkevm-chain should be able to run all circuits like this:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/8d40c6497332789fb45ac583782838ffaa1eb141/integration-tests/src/integration_test_circuits.rs#L265-L285

That function can be called for each circuit like in here: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/feature%2Funify-integration-tests-1/integration-tests/tests/circuits.rs

**Comment by ed255** [comment]
> Is this solved then? @ed255

In theory I think it should be resolved, but I'd prefer to wait until this is deployed in the testnet so that we can really confirm this error is not appearing anymore :)

**Comment by pinkiebell** [comment]
@AronisAt79 This can be tested with this branch https://github.com/privacy-scaling-explorations/zkevm-chain/tree/2023-01-16

**Comment by AronisAt79** [comment]
> @AronisAt79 This can be tested with this branch https://github.com/privacy-scaling-explorations/zkevm-chain/tree/2023-01-16

Thanks @pinkiebell! will start the tests now.

**Comment by AronisAt79** [comment]
Testedon zkevm-chain commit 6cdd88644cfe87a7f640cc279c54a44b93bbf0fa.
Proof generation now succeeds.
Full logs: https://zkevm-chain-testing.s3.eu-central-1.amazonaws.com/proveSingeCrossChainTx_tx_True_329-timer.tar.gz
