### ISSUE TITLE
refactor to common error gadget

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#1059]
as more error gadgets added, I feel more common operations among them:

 -  look up false is_success
 -  go to end_tx when root
 - restore context when internal
 - rw_counter_end_of_reversion constraint.

it is better to refactor new common gadget like CommonErrorGadget to cover them.

**Comment by DreamWuGit** [comment]
also can create an associated fn for `RestoreContextGadget` like: `RestoreContextGadget::from_revert_ctx `which directly places all the 0's and has less "magic numbers" arround.
```
RestoreContextGadget::construct(
                cb,
                0.expr(),
                0.expr(),
                0.expr(),
                0.expr(),
                0.expr(),
                0.expr(),
            )
```

**Comment by CPerezz** [comment]
> also can create an associated `fn` for `RestoreContextGadget` like: `RestoreContextGadget::from_revert_ctx `which directly places all the 0's and has less "magic numbers" arround.
> 
> ```
> RestoreContextGadget::construct(
>                 cb,
>                 0.expr(),
>                 0.expr(),
>                 0.expr(),
>                 0.expr(),
>                 0.expr(),
>                 0.expr(),
>             )
> ```

https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1116#discussion_r1098744595 for context! :)

**Comment by DreamWuGit** [comment]
I am planning to do it this week 😄

**Comment by DreamWuGit** [comment]
closing as #1177  merged!
