### ISSUE TITLE
Address leftover TODOs regarding non-deterministic tests in CopyCircuit

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1065]
See: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/copy_circuit.rs#L892-L934 and enable these tests back again.

~~This comment was left by @lispc IIUC. But maybe my git blame tracking was not accurated enough.
In case it was, would be nice if @lispc could add a bit more background.~~

Seems @z2trillion  added the TODO. So please, add some feedback if you can and remember about it!

**Comment by lispc** [comment]
I checked and found it was introduced in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/762 by @z2trillion .

**Comment by z2trillion** [comment]
@andyrdt is working on this. I commented out the previous tests in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/762 because with the changes there, it's much harder to represent invalid copy circuit assigments as `CopyEvent`'s.

**Comment by CPerezz** [comment]
@z2trillion thanks! Could you file an issue for that? I can maybe work on make it easier so that we can have these tests back!

**Comment by andyrdt** [comment]
I have a PR out for this: #1078
