### ISSUE TITLE
Unify circuit testing strategies across workspace crates

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1097]
While working on #1094 I noticed that in our testing modules we're repeating a lot of code and doing the same thing in slightly different ways when testing our circuits with the `MockProver`. 

I thought that would be interesting to unify and simplify the testing adding a similar tool to the one I created in the `mock` crate with a builder pattern.
See: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/9e5ef920eae92328080452a2bbc041421fb6eb2f/mock/src/test_ctx.rs#L106

**Comment by ChihChengLiang** [comment]
Close for no action to take.
