### ISSUE TITLE
Add ExpCircuit to integration tests

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1100]
I just noticed that this circuit is missing in the integration tests

Depends on
- https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1063
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1099

**Comment by roynalnaruto** [comment]
Since the padding logic for Exponentiation circuit is not yet done, shall we wait for https://github.com/privacy-scaling-explorations/zkevm-specs/pull/359 and https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1062 to be merged before adding it to the integration tests?

**Comment by ed255** [comment]
> Since the padding logic for Exponentiation circuit is not yet done, shall we wait for [privacy-scaling-explorations/zkevm-specs#359](https://github.com/privacy-scaling-explorations/zkevm-specs/pull/359) and #1062 to be merged before adding it to the integration tests?

Yes!  We should wait :)

**Comment by ed255** [comment]
Depends on https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1148 because it refactors the integration tests a bit
