### ISSUE TITLE
Apply Column annotations for all of our circuits.

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1106]
We should start to take profit of the annotation system and annotate the columns of all our circuits.

### Circuits to annotate:

- [x] State Circuit (Kimi) https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1152
- [x] Evm Circuit (not sure with the CellManager how we will deal with it) #1137
- [x] ByteCode Circuit (Kimi) https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1152
- [x] CopyCircuit (Adrià) https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1165
- [x] PiCircuit (David) (https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1156)
- [x] Root Circuit (Kimi) (https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1173)
- [x] Keccak Circuit (leolara) https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1296
- [x] Exp Circuit (leolara) https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1167

- [ ] MptCircuit - This will not be done as part of this issue

**Comment by aguzmant103** [comment]
Depends onhttps://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1107

**Comment by CPerezz** [comment]
Now that I made the `LookupTrait` refactor, included annotations for all the lookup tables and also for the EVM Circuit, I think the rest of circuits are trivial to annotate taking #1137 as an example.

So un-assigning this from me. Anyone is free to claim any of the tasks mentioned in the issue description.

**Comment by CPerezz** [comment]
@leolara please modify the issue description to mark on which of the tasks you're working on :pray:

**Comment by KimiWu123** [comment]
I'm taking State Circuit and Bytecode Circuit, and the issue desc. updated.

**Comment by leolara** [comment]
Why are the collumns annotated in the witness assignation phase, while they wouldn't depend on the witness? Wouldn't it make more sense to annotate them when creating the gates?

**Comment by leolara** [comment]
I understand that when the is set to a region to be layouted, and at that point assigned to a "physical" column that is shared between "logical" columns in a circuit. But the annotated name info could be already set in the "logical" column.

I understand this is how it works, but the other design would be better interface I think.

**Comment by CPerezz** [comment]
> I understand this is how it works, but the other design would be better interface I think.

Ohh I see what you mean now. Yes, definitely would be nicer. As happens with the lookup annotations done in the configure step.
But sadly, it can't be done like this :(

**Comment by leolara** [comment]
@CPerezz in the execution circuit, why are the q_step_* columns not annotated, or am I missing something?

**Comment by CPerezz** [comment]
@leolara because we don't annotate Selectors. You can if they're `Fixed` columns used as a selector. That's up to you.  If I missed something in the PR, feel free to file an issue!!
