### ISSUE TITLE
Replace `assert!(prover.verify(), Ok(()))` by `prover.assert_satisfied()` for positive tests

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1107]
As discussed with @str4d during the last Halo2 office hours call on Jan 24th, `prover.verify()` should only be used to test expected circuit errors. 

Instead, for any other test, `prover.assert_satisfied` is much more nicer as it provides a way more info and also prints annotations for more cases.
So we should make that change.

**Comment by ed255** [comment]
Note that we should `prover.assert_satisfied_par()` to get the parallelization in the MockProver verification.

Also for the EVM circuit I think we're using `verify_at_rows_par`, so... maybe we need an `assert_satisfied_at_rows_par`?

**Comment by CPerezz** [comment]
> Note that we should prover.assert_satisfied_par() to get the parallelization in the MockProver verification. 
Is indeed what I'm adding!

> Also for the EVM circuit I think we're using verify_at_rows_par, so... maybe we need an assert_satisfied_at_rows_par?

See: https://github.com/privacy-scaling-explorations/halo2/issues/133 @ed255
