### ISSUE TITLE
Research ways to improve Circuit input builder

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-circuits#1114]
The focus should be in avoiding code repetition and simplifying the code base

**Comment by ed255** [comment]
Here are some ideas to research:
- Currently we have a CellManager in Keccak and another implementation in EVM.  And maybe a new one coming up in MPT.  Can we unify them?
- Brecht introduced some macros in the MPT refactor, could they be applied to the EVM circuit to simplify the code?  See https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/56b19e4976771d3f990f8ee0642902ef9728d51e/zkevm-circuits/src/mpt_circuit/branch/branch_key.rs#L144

**Comment by ed255** [comment]
Closing this because we have completed the tech-debt milestone and we have made some improvements in the Circuit Input Builder (like moving the gen_associated_steps for the BeginTx/EndTx to associated type functions)
