### ISSUE TITLE
Proof generation for exp circuit fails with  error <No Column<Advice> is used in phase Phase(1) while allocating a new "Challenge usable after phase Phase(1)>

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-circuits#1123]
zkevm-chain commit: 6cdd88644cfe87a7f640cc279c54a44b93bbf0fa
circuits commit: "https://github.com/pinkiebell/zkevm-circuits.git", branch = "zkevm-chain"

logs & traces: https://zkevm-chain-testing.s3.eu-central-1.amazonaws.com/proveSingeCrossChainTx_exp_True_328-timer.tar.gz

**Comment by AronisAt79** [comment]
@han0110 i guess this needs no adaptations on zkevm-chain components correct? We can just update the circuits dependency  towards latest circuits:main and retest in testnet?

**Comment by han0110** [comment]
Yes I think so, just need to update the `zkevm-circuits` to latest revision.

**Comment by AronisAt79** [comment]
Tested on zkevm-chain 297488bfdf9079ae97a3f8092706d697ec06bae8. Proof generation now succeeds.
Full logs at https://zkevm-chain-testing.s3.eu-central-1.amazonaws.com/proveSingeCrossChainTx_exp_True_345-timer.tar.gz
