### ISSUE TITLE
Keccak integration tests should not have keccak_padding: None

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/zkevm-circuits#1128]
From https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/967#issuecomment-1410617907

---

by @ed255 :

Also I see that we have keccak_padding: None in the integration tests, we should also change that for an appropriate value to get a constant keccak circuit.

**Comment by aguzmant103** [comment]
https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1148 waiting for this
