### ISSUE TITLE
Implement CREATE & CREATE2

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-circuits#1130]
Implementing CREATE & CREATE2 execution states in the EVM circuit. See the spec first https://github.com/privacy-scaling-explorations/zkevm-specs/issues/371

**Comment by roynalnaruto** [comment]
@aguzmant103 I am working on this currently. WIP is in the forked repo here: https://github.com/scroll-tech/zkevm-circuits/blob/feat/create-create2/zkevm-circuits/src/evm_circuit/execution/create.rs

**Comment by hero78119** [comment]
> @aguzmant103 I am working on this currently. WIP is in the forked repo here: https://github.com/scroll-tech/zkevm-circuits/blob/feat/create-create2/zkevm-circuits/src/evm_circuit/execution/create.rs

@adria0 here :)

**Comment by roynalnaruto** [comment]
Another scenario to be handled within the `Create` gadget is "insufficient balance" in caller's account.

WIP on the fork repo: https://github.com/scroll-tech/zkevm-circuits/pull/369
