### ISSUE TITLE
Fix zkevm-circuits CI Checks' consecutiveness instabilities with git-ops

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-circuits#1131]
https://github.com/privacy-scaling-explorations/github-ops

**Comment by ntampakas** [comment]
Investigation:
  - Add terraform & ansible support
  - Use lambda function to trigger manually the workflow that creates instance(s), in order to avoid GH short interval limitation.

**Comment by ntampakas** [comment]
> Investigation:
> 
> * Add terraform & ansible support
> * Use lambda function to trigger manually the workflow that creates instance(s), in order to avoid GH short interval limitation.

Probably it makes sense to implement the issues mentioned above, as enhancements.
