### ISSUE TITLE
Bug on account existance checking in bus-mapping

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1132]
While working on #1120 with @ed255 , the tests `callop_simple` and `callop_recursive` popped from nowhere and showed that something was not going as we expected.

This was due to the fact that we fixed the StateCircuit verification tests in d42cb3fb8. Now that we don't check only padding rows but all of then, some errors popped out.

Edu had some work already done on:  https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/4e6e5560990c4f3f76131c89b89156e8e4018606 which we tried but did not solve the problem.

Just as help, here is one trace of the RWs and the error we get:
```log
# We're reading twice the same account address and in between the reads, the value changed. That's what pops the error:
[zkevm-circuits/src/state_circuit.rs:215] offset = 451
[zkevm-circuits/src/state_circuit.rs:216] row = Account {
    rw_counter: 45,
    is_write: false,
    account_address: 0xffffffffffffffffffffffffffffffffffffffff,
    field_tag: CodeHash,
    value: 0,
    value_prev: 0,
}
[zkevm-circuits/src/state_circuit.rs:215] offset = 452
[zkevm-circuits/src/state_circuit.rs:216] row = Account {
    rw_counter: 76,
    is_write: false,
    account_address: 0xffffffffffffffffffffffffffffffffffffffff,
    field_tag: CodeHash,
    value: 89477152217924674838424037953991966239322087453347756267410168184682657981552,
    value_prev: 89477152217924674838424037953991966239322087453347756267410168184682657981552,
}
```

```
# This is the constraint error we-re getting:
error: constraint not satisfied

  Cell layout in region 'state circuit':
    | Offset | A1 | A83| A7 | F0 |
    +--------+----+----+----+----+
    |   451  |    |    | x2 |    |
    |   452  | x0 | x1 | x3 | x4 | <--{ Gate 'state circuit constraints' applied here

  Constraint 'non-first access reads don't change value':
    x4 * ((1 * x1) * ((1 - x0) * (x3 - x2))) = 0

  Assigned cell values:
    x0 = 0
    x1 = 1
    x2 = 0
    x3 = 0x2f71d9860890f284508cc661eb78c7b33a1d910a99daa1ccfade86f9a44419e
    x4 = 1

thread 'evm_circuit::execution::callop::test::callop_simple' panicked at 'circuit was not satisfied'
```

The tests are left with `#[ignore]` tags on them. And we'll fix that issue in a sepparated PR so that we don't block #1120 more.

**Comment by ed255** [comment]
> Edu had some work already done on: [4e6e556](https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/4e6e5560990c4f3f76131c89b89156e8e4018606) which we tried but did not solve the problem.

I just realized that the commit I showed you didn't fix anything, it just extended the checks for account lookups, which in turn makes some tests fail, but I didn't work on the fix because it was also being investigated by @lispc in here:  https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1118 .  The issue encountered may be related that investigation.

**Comment by ed255** [comment]
To resolve this issue I will start by adding an extra check to rw operations generated from bus-mapping which was mentioned in this issue https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1118#issuecomment-1408695768
