### ISSUE TITLE
Grafana: Implement CI Alerts/Notifications to discord

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-circuits#1133]

**Comment by aguzmant103** [comment]
@ntampakas is this still in progress? Just asking cause it's on circuits repo and appears on the board :)

**Comment by ntampakas** [comment]
Hey @aguzmant103 ,
This is on hold a long time now, sorry for not changing the status. Please let me move it to the backlog.

**Comment by ChihChengLiang** [comment]
Close for action to take in the short run.
