### ISSUE TITLE
New Soundness Bug: SHL/SHR 0 Divisor

### ISSUE THREAD

**Issue by kcharbo3** [privacy-scaling-explorations/zkevm-circuits#1136]
### Description
A malicious prover can assign `divisor = 0` in the SHL/SHR opcodes to prove any shift operation to output 0 to the stack. This is because a nonzero dividend, nonzero quotient, and nonzero shift is still possible even if the divisor is zero. 

SHL ex.
```
quotient = 2
divisor = 0
remainder = 0
dividend = 0
shift = 4
```
This will successfully prove that `4 2 SHR = 0`. This should be constrained to equal `32` instead.

SHR ex.
```
quotient = 1
divisor = 0
remainder = 4
dividend = 4
shift = 2
```
This will successfully prove that `2 4 SHR = 0`. This should be constrained to equal `1` instead.

### Further Explanation:
There are 7 explicit constraints.
```
1. quotient*divisor + remainder = dividend mod 2^256
2. divisor = 0 OR remainder < divisor
3. divisor = 0 OR shift = shift[0]
4. SHL => remainder = 0
5. SHR => quotient * divisor + remainder < 2^256
6. Divisor != 0 => divisor = 2^shf0
7. Shf0 = shift[0]
```
Constraints 2, 3, and 6 are all satisfied since the divisor is 0. With 6 satisfied, 7 can easily be satisfied. Now, all there is left is 1, 4, and 5. These 3 remaining constraints allow the general solutions:
```
SHL:
quotient = Any number < 2^256
divisor = 0
remainder = 0
dividend = 0
shift = Any number < 2^256
Thus proving: (Any Number < 2^256) (Any Number < 2^256) SHL = 0

SHR:
quotient = Any number < 2^256
divisor = 0
remainder = dividend
dividend = Any number < 2^256
shift = Any number < 2^256
Thus proving: (Any Number < 2^256) (Any Number < 2^256) SHR = 0
```

**Comment by silathdiir** [comment]
Yes. I see. It seems that we should constrain `shift > 255 if divisor == 0`, So it could guarantee the output is zero if `shift > 255` as https://www.evm.codes:
```
Any Number SHL shift (> 255) = 0
Any Number SHR shift (> 255) = 0
```
What do you think?

**Comment by kcharbo3** [comment]
That's great, I think that works!

**Comment by silathdiir** [comment]
Hi @kcharbo3, I am sorry that I check the code again, and it seems that you could not assign `shift` and `divisor` without [assign_exec_step](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/shl_shr.rs#L144) function (as we may not construct the test cases you mentioned above).

The `divisor` value is calculated via `shift` and then assign to a word in [this code](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/shl_shr.rs#L157). Please correct me if I was wrong. Thanks.

**Comment by kcharbo3** [comment]
Yeah I couldn't create a test case either. But when `divisor` is set in the `assign_exec_step` function, that is an assignment and not a constraint right? I am thinking a malicious prover could fork the code, modify the `assign_exec_step` function and get a successful proof. Let me know if that's not quite right.

**Comment by DreamWuGit** [comment]
@kcharbo3 yes, I think adversary can do it without following our assign code, @silathdiir will fix it !

**Comment by CPerezz** [comment]
@kcharbo3 is correct. We have to assume that assignation functions (and Rust type system even) don't represent any security guarantee. 
Otherwise any adversary could modify the source code to modify the assignation.

**Comment by CPerezz** [comment]
Assigning to @silathdiir

**Comment by kcharbo3** [comment]
Sounds good, thank you!
