### ISSUE TITLE
Reuse circuit code for ExecSteps that "revert"

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1146]
We have a lot of repeated circuit code in the error execution states:
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/a75c9aa3bda78575fcee1560cc6ff44f7aa9e22a/zkevm-circuits/src/evm_circuit/execution/error_stack.rs#L73-L133
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/a75c9aa3bda78575fcee1560cc6ff44f7aa9e22a/zkevm-circuits/src/evm_circuit/execution/error_oog_constant.rs#L54-L112
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/a75c9aa3bda78575fcee1560cc6ff44f7aa9e22a/zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs#L74-L134
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/a75c9aa3bda78575fcee1560cc6ff44f7aa9e22a/zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs#L99-L165

**Comment by DreamWuGit** [comment]
@ed255  I think it is duplicated with #1059
