### ISSUE TITLE
Sync `ErrorStack` with updated spec

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-circuits#1154]
Sync `ErrorStack` with https://github.com/privacy-scaling-explorations/zkevm-specs/pull/383.

Need to add the `stack_{overflow,underflow}` pairs to [`responsible_opcodes`](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/step.rs#L166) and update `ErrorStack`.

**Comment by silathdiir** [comment]
If no one is working on this issue please help assign it to me. Suppose to update `responsible_opcodes` according to spec.

**Comment by han0110** [comment]
That'd be nice! Thank you for taking it!

(seems we could update this function [`valid_stack_ptr_range`](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/eth-types/src/evm_types/opcode_ids.rs#L667) to become `invalid_stack_ptrs` and use it later in [`responsible_opcodes`](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/step.rs#L166))
