### ISSUE TITLE
Move into struct-associated functions EndTx and BeginTx `ExecutionState`s

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1180]
See: 
- https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder.rs#L256-L261
- https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder.rs#L274-L279

**Comment by KimiWu123** [comment]
Hey @CPerezz , would like to confirm the spec before start.
From the comment [here](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder.rs#L274-L279)
```
        // TODO: Move into gen_associated_steps with
        // - execution_state: BeginTx
        // - op: None
```

From my understanding, you would like do what `gen_associated_ops` and `fn_gen_associated_ops` are doing (like state pattern), having another file(s) to take care the logic of  `gen_begin_tx_steps` and `gen_begin_tx_steps`, right?
