### ISSUE TITLE
Change ExecError related functions to be associated-fns

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1181]
See: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f185b1276b67b730448724930b33c72a342ad96a/bus-mapping/src/error.rs#L138-L139

**Comment by ChihChengLiang** [comment]
@CPerezz I'm not sure what must be done in this task. Can you give some more detail to the description?

**Comment by CPerezz** [comment]
The idea is to move the marked function ` get_step_reported_error` inside of an `impl ExecError` block. The idea is that this should not need to be a standalone function.

Let me know if that makes sense @ChihChengLiang !!

**Comment by ChihChengLiang** [comment]
Now that makes sense. Thanks for elaborating this.
