### ISSUE TITLE
RwTableQueries in StateCircuit is missing `aux1` and `aux2`

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1182]
See https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f185b1276b67b730448724930b33c72a342ad96a/zkevm-circuits/src/state_circuit/constraint_builder.rs#L33

Figure out if this needs synchronization with the specs.

@ashWhiteHat you may look into this one to keep the state circuit and specs in sync.

**Comment by ed255** [comment]
Before working on this, review the changes introduced by https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1423 because they may already address this.

**Comment by ChihChengLiang** [comment]
I can confirm #1423 has addressed this issue. https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1423/files#diff-3c34e18842d60643d37a4c79494077f57237418db3eb5b2539827baa23859d60L29-R28
