### ISSUE TITLE
Unify restore_ctx and handle_return in bus_mapping

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1186]
See: https://github.com/appliedzkp/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L927-L928 

Also, try to mitigate code duplication. 
See `STOP` and `RETURN` impls.

**Comment by hero78119** [comment]
More addons

[Return op](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/return_revert.rs#L95)->[handle_restore_context](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L991)

Stop op
[Stop op](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/stop.rs#L40)-> [gen_restore_context_ops](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L1311)

Both function share some similarity. Will be good if can unified the logic.

**Comment by DreamWuGit** [comment]
supposed to be same with issue  #1256
