### ISSUE TITLE
Add dedicated module to managers all op codes' constant properties centrally

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#119]
these are some constant properties  regarding each op code of circuit, such as GC_DELTA, PC_DELTA, SP_DELTA ,GasCost . 
 Placing them in dedicated module which managers all op codes' such properties , which will make good organized & maintained.
 in the concrete op gadget circuit references that module ,  first discuss with @ChihChengLiang @han0110 , we agree that makes sense.
 if you are interested, leave your point !

**Comment by ChengYueJia** [comment]
Hi, has this issue been resolved?

**Comment by ChihChengLiang** [comment]
closed for inactivity
