### ISSUE TITLE
Investigate the leftover TODO about handling address creation in CodeHash ExecStep

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1190]
Check: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/43c67c91ca566fd2b7f3588979c537006090f185/bus-mapping/src/evm/opcodes/extcodecopy.rs#L14-L15 and https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/720 which is related to the TODO left and talk to @ed255 who was who introduced it.

**Comment by ed255** [comment]
Added task: Document how we handle non-existing accounts and account creation (with CodeHash = 0, etc)
