### ISSUE TITLE
Use mock crate for mock txs

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1192]
See https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f185b1276b67b730448724930b33c72a342ad96a/zkevm-circuits/src/evm_circuit/execution/error_oog_constant.rs#L212-L225
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f185b1276b67b730448724930b33c72a342ad96a/zkevm-circuits/src/evm_circuit/execution/begin_tx.rs#L423-L424

**Comment by ChihChengLiang** [comment]
Resolved in #1360
