### ISSUE TITLE
Remove leftover TODO in ReturnRevert opcode impl in bus_mapping

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1194]
See: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f185b1276b67b730448724930b33c72a342ad96a/bus-mapping/src/evm/opcodes/return_revert.rs#L18

**Comment by ChihChengLiang** [comment]
Fixed in #1587
