### ISSUE TITLE
Constrain value.prev and value_prev in StateCircuit

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1197]
See https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f185b1276b67b730448724930b33c72a342ad96a/zkevm-circuits/src/state_circuit.rs#L557-L558

@ashWhiteHat I think you're already aware of this; we add this issue to track the TODO in the code.

**Comment by ashWhiteHat** [comment]
This is same with https://github.com/privacy-scaling-explorations/zkevm-specs/issues/202 I think
