### ISSUE TITLE
Extend LookupTable trait

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1199]
See https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f185b1276b67b730448724930b33c72a342ad96a/zkevm-circuits/src/state_circuit.rs#L544-L545

Figure out if we can abstract more methods into the LookupTable trait, and if possible do it.

**Comment by ed255** [comment]
@CPerezz has more details about which methods to abstract, so if someone wants to take this issue ping him :)

**Comment by NOOMA-42** [comment]
Is this issue still valid? I'd like to investigate into this. 
To my understanding, both `rw_table` and `mpt_table` implement lookup_table, and `Queries` is used in create_gate and it represent a row of lookup table. Does this issue intend to abstract away `rw_table` so that there's no `rw_table` and only `lookup_table` ?

**Comment by ChihChengLiang** [comment]
Hi @NOOMA-42,
Here's my understanding of the issue. The task is about implementing the LookupTable trait for both `mpt_table` and `rw_table`.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/5d01150f55ae9e877fae92246d82e47f051db71e/zkevm-circuits/src/table.rs#L63

An example of implementing the LookupTable trait is the Exp table. The main benefit we get is the column annotations so it would be easier to debug the failing lookups in the future.

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/5d01150f55ae9e877fae92246d82e47f051db71e/zkevm-circuits/src/table/exp_table.rs#L174-L184

**Comment by ChihChengLiang** [comment]
We reevaluated the issue and determined the the current status is fine.
