### ISSUE TITLE
Deduplicate code between evm ConstraintBuilder and BaseConstraintBuilder

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1202]
evm ConstraintBuilder and BaseConstraintBuilder have:
- require_zero
- require_equal
- require_boolean
- require_in_set
- condition
- add_constraints
- add_constraint
- validate_degree

all with very similar implementation.  Deduplicate them

**Comment by leolara** [comment]
@ed255 a first look shows that BaseConstrainBuilder is used by other circuits other than EVM circuit. While ConstrainBuilder is used by EVM circuit exclusively. Perhaps it would be a good idea to take BaseConstrainBuilder outside EVM circuit module.

**Comment by aguzmant103** [comment]
#1318
