### ISSUE TITLE
Easier debugging for EVM Circuit

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1204]
Explore ideas to make it easier to debug the EVM Circuit
- Print execution path?
- Record each ExecStep which offset starts

The main idea is that when an EVM Circuit constraint fails, it's quite hard to figure out what happened:
- mapping a constraint failure to an Execution gadget, and to a particular constraint
- mapping a rw lookup to an Execution gadget and a particular rw lookup in the circuit code

**Comment by lispc** [comment]
i debugged a lot of failures in scroll testnet / scroll fork.   

Here is my personal experience:
mapping a constraint failure to an Execution gadget: check offset
mapping a rw lookup to an Execution gadget: the check_rw_lookup is good enough for me usually.

i made quite a few improvements in scroll fork for debugging (logging/assertion/...) O can introduce these in the friday community meeting.

or could give me a case which you think not easy to debug? then i can share how i usually deal with it

**Comment by ed255** [comment]
> Here is my personal experience: 
> mapping a constraint failure to an Execution gadget: check offset 
> mapping a rw lookup to an Execution gadget: the check_rw_lookup is good enough for me usually.

I have applied those strategies some time as well, but they are a a bit manual, and not friendly to those less experienced with the codebase; so the idea of this task would be to get more friendly/automated tools that anyone can use.  For example, I could imagine a helper for an EVM circuit execution test that records the offset of each assigned exec_step, then takes the MockProver FailureErrors, and matches the FailureErrors offsets with the steps.

In general I think the best scenario would be that given a constraint failure or a lookup failure (from the MockProver), we get the file + line where the constraint/lookup that failed was defined, along with the values used in the expressions.  This may be asking too much, but I think we should try to get as close to that scenario as possible.

> i made quite a few improvements in scroll fork for debugging (logging/assertion/...) I can introduce these in the friday community meeting.

That would be really nice!

> or could you give me a case which you think not easy to debug? then i can share how i usually deal with it

I've had some pain debugging rw lookups that were not working (trying to figure out which rw lookup out of all the step rw lookups was failing).  But I think `check_rw_lookup` was not being used?  I noticed that the check is only enabled when logging is set to debug:
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f185b1276b67b730448724930b33c72a342ad96a/zkevm-circuits/src/evm_circuit/execution.rs#L1245-L1258
And for example we're running the unit tests in github without `RUST_LOG=debug`.  I think we should change that, and disable the check in a different way (so that the default is to run it, and it can be disabled via a feature flag or an env var).

**Comment by Brechtpd** [comment]
> In general I think the best scenario would be that given a constraint failure or a lookup failure (from the MockProver), we get the file + line where the constraint/lookup that failed was defined

My `require!` macro does this, but I found this to be insufficient in some cases because of code reuse. As you said as well, ideally it's possible to make the constraint name the full call stack so we know exactly which constraint fails in which context. I believe that shouldn't be too difficult to add as there are libraries that provide this call stack info.

For lookups, maybe the most general and easiest way is to have a mode where lookups are also inserted in the circuit individually on top of the optimized method so their name (containing their location) isn't lost. This will obviously change the circuit itself a bit, and will increase the time the mock prover needs to run because potentially many more lookups, but should be very easy to implement and will immediately show where the problem is without having to know anything else about the circuits.

**Comment by ChihChengLiang** [comment]
@ ed255 Do we have something actionable here?

**Comment by ed255** [comment]
Closing as we have had some progress on this and we're at the end of the milestone.
