### ISSUE TITLE
SuperCircuit integration tests: make it non variadic

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1208]
Currently the SuperCircuit used in the integration tests is variadic depending on the inputs.  We can see this because the check `test_variadic` introduced in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1148 fails, and we also saw this already when trying the SuperCircuit with the real prover with chached proving keys (we observed ConstraintFailures).

I have taken a look at the fixed columns that vary between one run and the other, and they are fixed columns 3 to 10, which correspond to the Keccak Circuit.  This is no surprise, because the integration tests are using the circuits parameters `keccak_padding: None` which assigns the fixed columns of keccak dynamically.  We must change that for a value that works for the different integration tests.  A value of ~7000 should be enough (this is the max number of rows that the keccak fixed columns are assigned in the integration tests, gathered from observation)

**Comment by leolara** [comment]
I think there was a task also to make keccak_padding not an `Option`? But an `int` so it is automatic when `0` like in the EVM circuit? I don't see it now.

**Comment by ed255** [comment]
> I think there was a task also to make keccak_padding not an `Option`? But an `int` so it is automatic when `0` like in the EVM circuit? I don't see it now.

I think there was no issue for that, I've just created it https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1212

**Comment by aguzmant103** [comment]
https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1148 waiting for this

**Comment by ed255** [comment]
This issue is probably the same as https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1128

**Comment by ed255** [comment]
This issue is related to the failures in the Integration Testing that we can see in the main branch since https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1173
```
thread 'main' panicked at 'circuit fixed columns are not constant for different witnesses', /home/ubuntu/actions-runner/_work/zkevm-circuits/zkevm-circuits/integration-tests/src/integration_test_circuits.rs:254:17
test mock_prover::serial_test_super_circuit_multiple_transfers_0 ... FAILED

failures:
    mock_prover::serial_test_super_circuit_erc20_openzeppelin_transfer_fail
    mock_prover::serial_test_super_circuit_erc20_openzeppelin_transfer_succeed
    mock_prover::serial_test_super_circuit_multiple_erc20_openzeppelin_transfers
    mock_prover::serial_test_super_circuit_multiple_transfers_0
```

Hopefully once this issue is resolved, the integration tests pass again :)

**Comment by leolara** [comment]
This is solved for the mock prover here: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1224 but it is producing errors for the real prover.
