### ISSUE TITLE
Add keccak circuit to integration tests

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1209]
Depends on https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1148 because it refactors the integration tests a bit

**Comment by anylots** [comment]
How many transfer transactions can be included in a proof submission？

**Comment by ed255** [comment]
> How many transfer transactions can be included in a proof submission？

Is this question related to this issue?
