### ISSUE TITLE
Apply merge queue to zkevm-circuits

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-circuits#1210]

**Comment by ChihChengLiang** [comment]
I enabled the merge queue. It has some parameters. Let me know if something works or not. I can help configure accordingly.
<img width="755" alt="Screenshot 2023-02-16 at 2 06 08 PM" src="https://user-images.githubusercontent.com/3391420/219282409-1bfdb67a-48a1-40fa-bdf6-f3db97d2b545.png">

**Comment by ChihChengLiang** [comment]
Merge queue is up and running.
