### ISSUE TITLE
contract tx_lookup table

### ISSUE THREAD

**Issue by barryWhiteHat** [privacy-scaling-explorations/zkevm-circuits#122]
In zkevm based zkrollup a smart contract translates the call data and some block constants into a form the zkp is able to read. 

The circuit expects this data to be in the format of

a + r * b + r**2 c + r**3 d = x 

The polynomial should be constructed in the field defined by https://github.com/appliedzkp/halo2/pull/1

So the layer1 even needs to calculate x and pass that as a public input to the zkevm proof.  

The exact format of the polynomial is not exactly what i have described. @han0110 may have more info on this.

**Comment by barryWhiteHat** [comment]
Since we are building the data in the table in the l1 evm. It might also make sense to calculate the message hash in the l1 evm and then include that in this table. This will allow us to remove the message hash calculation from the circuits for now and still have something that works relatively easily. 

Calculating hte message hash in l1 evm will cost a bit more but this can be optimized out later. 

@han0110 does this make sense to you? Do you see any issue ?

**Comment by han0110** [comment]
I think it makes sense to do the tx hashing in L1 for now, and move the effort into circuit later.

**Comment by barryWhiteHat** [comment]
I think we are also planning to add 

1. call_data_gas_cost calculations. This is due to the really annoying gas fee difference for bytes of data that are 0 and nonzero bytes of data. This is hard to check in circuit and we hope will be removed soon :)
2. message hash calculation here. This is just to make things easier.

**Comment by han0110** [comment]
Closed by #484
