### ISSUE TITLE
Integration tests compare permutations of proofs to check for variadic circuits

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/zkevm-circuits#1220]
### Describe the feature you would like

Integration tests compare permutations of proofs to check for variadic circuits

**Comment by leolara** [comment]
Blocked by https://github.com/privacy-scaling-explorations/halo2/issues/146

**Comment by leolara** [comment]
Blocked by https://github.com/privacy-scaling-explorations/halo2/issues/160

**Comment by aguzmant103** [comment]
@ChihChengLiang will take a look on the issue above and check if there are further actions required.

**Comment by ChihChengLiang** [comment]
@leolara As the completion of #1366, this issue is fully unblocked.
