### ISSUE TITLE
Seems `fee` should not be reversible in begin tx

### ISSUE THREAD

**Issue by silathdiir** [privacy-scaling-explorations/zkevm-circuits#1235]
### Describe the bug

Reference go-ethereum code:

1. Seems `fee` is transfered in [buyGas function](https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L233).

2. [buyGas function](https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L215) is invoked by [preCheck function](https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L237).

3. `value` is transfered in [this Call invocation](https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L359).

4. Call [get StateDB snapshot](https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L184) and [revert snapshot](https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L243).

So seems transfer `value` should be reversible but `fee` should not? It is implemented as [transfer_with_fee](https://github.com/scroll-tech/zkevm-circuits/blob/scroll-stable/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L486) and set both as reversible in current zkevm-circuit.

If this is an issue, suppose to fix it in this WIP PR https://github.com/scroll-tech/zkevm-circuits/pull/348.

**Comment by han0110** [comment]
Yeah I think you are right, the fee shouldn't be reversible, so perhaps we need to split the `UpdateBalanceGadget` of `sender` into 2 and one irreversible (fee) and the other reversible (to `receiver`).

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/06e9d64789f0cf57a2c0260f963db7c8d520fd69/zkevm-circuits/src/evm_circuit/util/common_gadget.rs#L350-L355
