### ISSUE TITLE
Export stats-generation tools from ignored tests to a binary

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#1246]
### Describe the feature you would like

As mentioned in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1229 by @ChihChengLiang it would be nice to have our reporting tools as external binaries rather than an ignored tests.

This doesn't only happen for the `ExecutionStep` occupancy in EVM. You can see that there are more in here:
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/Makefile#L66-L76

### Additional context

This is already how the `testool` works and it's much better and easier to use and integrate. 
So definitely looks like the right move.

**Comment by ed255** [comment]
We decided we're happy with the current situation.
