### ISSUE TITLE
bug: returndatasize after successful creation should be 0

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1250]
### Describe the bug

according to https://eips.ethereum.org/EIPS/eip-211， “As an exception, CREATE and CREATE2 are considered to return the empty buffer in the success case and the failure data in the failure case.”

we did not handle this now

**Comment by hero78119** [comment]
it's blocked by issues [Implement CREATE & CREATE2](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1130) 

After that, also need to check logic in bus mapping
