### ISSUE TITLE
bug: don't truncate 160bits address in rw

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1252]
### Describe the bug

this pattern in extcodecopy is incorrect

```

    let external_address = geth_step.stack.nth_last(0)?.to_address();
    state.stack_read(
        &mut exec_step,
        geth_step.stack.nth_last_filled(0),
        external_address.to_word(),
    )?;
```

discussed in https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1041 before

need to recheck this type of err in other opcodes.

**Comment by lispc** [comment]
@silathdiir (not urgent)

**Comment by silathdiir** [comment]
Please help assign this issue to me. Thanks.
