### ISSUE TITLE
refactor buss mapping  `handle_restore_context` and `gen_restore_context_ops`

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#1256]
these two method are similar , better to refactor to one !
`gen_restore_context_ops`:  https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L1254
`handle_restore_context`: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L953
refactor buss mapping  `handle_restore_context` and `gen_restore_context_ops`

**Comment by lispc** [comment]
oh it is not bug. So no need for the 'T-bug' label

**Comment by DreamWuGit** [comment]
bug template , otherwise use feature template will mark T-Featrue
