### ISSUE TITLE
implement ErrorOutOfGasCodeStore & ErrorMaxCodeSizeExceeded

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#1259]
these two errors are both `create` related errors, all about code store, plan to merge to one gadget to handle.

**Comment by KimiWu123** [comment]
Hi @DreamWuGit , there was the issue for https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1545. Could you help update issue number in #1545 and delete #1546 and #1547?

**Comment by ChihChengLiang** [comment]
closed by #1545
