### ISSUE TITLE
Handle `ErrorDepth` in `CALL_OP` and `CREATE

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-circuits#1312]
### Describe the feature you would like

When call or create dives too deep (> 1025), it's treated as failure of call or create, and should push a `0` onto the stack. 

- [x] `CALL_OP` - https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1155
- [x] `CREATE` - No yet

**Comment by KimiWu123** [comment]
`CREATE` was covered in #1430 .
