### ISSUE TITLE
Code duplication between returndatacopy and error_return_data_oo_bound

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#1324]
### Describe the feature you would like

Tech debt reported in #1323 by @xiaodino 

> We should refactor the unit tests in error_return_data_oo_bound, returndatacopy and other files as they use similar test codes to construct contract for testing.

### Additional context

Specifically

1. error_return_data_oo_bound https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/2a1074a6aaed02f9774834c63bd7da60d4de2cd7/zkevm-circuits/src/evm_circuit/execution/error_return_data_oo_bound.rs#L227-L244
2. returndatacopy https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/6113111dcfe541a316c108afa536eaf80626837e/zkevm-circuits/src/evm_circuit/execution/returndatacopy.rs#L301-L312

**Comment by ChihChengLiang** [comment]
@xiaodino Can you point out examples of other files that can be refactored together?

**Comment by xiaodino** [comment]
Other files are:

- calldatacopy.rs
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/calldatacopy.rs#L305-L330

- calldataload.rs
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/calldataload.rs#L266-L307

- returndatasize.rs
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/returndatasize.rs#L97-L121

- balance.rs
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/balance.rs#L258-L288

- address.rs
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/address.rs#L112-L134

I'm interested in working on the ticket in the next several days.

**Comment by ChihChengLiang** [comment]
@xiaodino Thanks for pointing out the files. And thanks for taking on this task.
Let me assign it to you.

**Comment by ChihChengLiang** [comment]
Resolved in #1340
