### ISSUE TITLE
Soundness bug in Bytecode circuit 1 (missing state transition constraint)

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1332]
The Bytecode circuit is missing the constraint that forces the a "header" state after the last "byte" state in a bytecode.  This allows an attacker to insert bytes after the last real byte.  If we insert a "byte" state after the last bytecode "byte", we reach a situation in which we can only have "byte" states until the end of the circuit.  In theory this should not be possible because we are constraining the last state to be "header", but there's another bug here!  `q_enable` is used in the constraint to force the last row to be "header", and `q_enable = 0` in the last row.

Here's an example of the attack:

For a bytecode circuit of size 6 which contains 1 bytecode of length 3 it looks like this:

| Tag    | Index | Value | CodeHash |
| ------ | ----- | ----- | -------- |
| Header | 0     | 3     | 0        |
| Byte   | 0     | a     | C1       |
| Byte   | 1     | b     | C1       |
| Byte   | 2     | c     | C1       |
| Header | 0     | 0     | 0        |
| Header | 0     | 0     | 0        |

But we can do this assignment and the constraints will work

| Tag    | Index | Value | CodeHash |
| ------ | ----- | ----- | -------- |
| Header | 0     | 3     | 0        |
| Byte   | 0     | a     | C1       |
| Byte   | 1     | b     | C1       |
| Byte   | 2     | c     | C1       |
| Byte   | 3     | d     | C1       |
| Byte   | 4     | e     | C1       |

We're introducing bytes 3 and 4 and we can use any value for those.

# Summary

## Bug 1

The transition Byte -> Header is not constrained to be true when the appropriate condition appears
- Solution: Add a constraint that forces the next state to be "Header" when the current state is "Byte" and index == length - 1

## Bug 2

The last row has `q_enable=0`, which effectively disables all polynomial constraints applied in that row (including the one that forces the row to be a "Header" state).
- Solution: Set `q_enable=1` to all rows of the circuit, including the last one

# Demo

This commit https://github.com/privacy-scaling-explorations/zkevm-circuits/compare/main...bug/bytecode_soundness1 includes a test and some helper code that overwrites the assignment to show how bytes can be added after the "real" bytecode, and all the constraints still pass.

**Comment by rrzhang139** [comment]
Would like to give this a try! Btw, there is a typo in Bug 2. I think you meant to say q_enable=0 on the last row. Will first change the specs!

**Comment by ed255** [comment]
> Would like to give this a try! Btw, there is a typo in Bug 2. I think you meant to say q_enable=0 on the last row. Will first change the specs!

Thanks for catching the typo! I updated the first message :)
Sounds good to me for you to work on this! I'll assign you to this issue.

> By "last row" do you mean the last row of a bytecode (header,byte,byte....,) or do you mean the last row of the whole bytecode circuit (q_last)?

For "last row" I mean the last row of the whole bytecode circuit (where q_last = 1)
