### ISSUE TITLE
implement ErrorOutOfGasAccountAccess error state 

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#1349]
### Describe the feature you would like

this kind of error is for Balance | ExtCodeSize | ExtCodeHash.

**Comment by DreamWuGit** [comment]
already draft here https://github.com/scroll-tech/zkevm-circuits/pull/426 . will push to upstream when current pending error PRs merged!

**Comment by KimiWu123** [comment]
https://github.com/scroll-tech/zkevm-circuits/pull/426 has been merged, this task is unblocked. @DreamWuGit

**Comment by DreamWuGit** [comment]
@KimiWu123 yeah, I will push it to upstream soon.
