### ISSUE TITLE
Bugreport

### ISSUE THREAD

**Issue by bankkiku10** [privacy-scaling-explorations/zkevm-circuits#1359]
### Describe the bug

![Screenshot_25660403_184826](https://user-images.githubusercontent.com/87906755/232184408-939555dd-9bfa-4017-a355-7ce25fa33c3d.jpg)
![Screenshot_25660403_184908](https://user-images.githubusercontent.com/87906755/232184411-90215677-0bb5-4dfc-b0e7-e8b925715684.jpg)
![Screenshot_25660403_185035](https://user-images.githubusercontent.com/87906755/232184414-36bac88c-8e03-44e3-a65f-1322d6ca9b59.jpg)
![Screenshot_25660403_190033](https://user-images.githubusercontent.com/87906755/232184416-42af3d70-64ef-46f6-84b8-5c91830badb4.jpg)
![Screenshot_25660403_190050](https://user-images.githubusercontent.com/87906755/232184424-00ab49af-4e0f-4722-b54f-7ac6ac105d18.jpg)
![Screenshot_25660403_190713](https://user-images.githubusercontent.com/87906755/232184429-e6162c60-332e-4540-923c-7f1c4dd2aea0.jpg)

### Concrete steps to reproduce the bug. If it's able reproduce via testool, please share `test_id` from jenkins report

Transaction eror

**Comment by ChihChengLiang** [comment]
Sorry, I think this issue belongs to the scroll testnet side. @lispc can you show us where would be a better place to report this type of bugs?

**Comment by ChihChengLiang** [comment]
Close with inactivity
