### ISSUE TITLE
EIP-3651: Warm COINBASE

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#1367]
### Describe the feature you would like

[EIP-3651: Warm COINBASE](https://eips.ethereum.org/EIPS/eip-3651)

### Additional context

Pending analysis of what work should be done

**Comment by KimiWu123** [comment]
This was covered in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1424
