### ISSUE TITLE
EIP-3860: Limit and meter initcode

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#1368]
### Describe the feature you would like

 [EIP-3860: Limit and meter initcode](https://eips.ethereum.org/EIPS/eip-3860)

### Additional context

This task requires changing behaviors in contract creation transaction, CREATE, and CREATE2. Better do it after #1130 is resolved.

**Comment by KimiWu123** [comment]
This issue was addressed in #1424 and #1562.
