### ISSUE TITLE
Support prevrandao opcode

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#1376]
After the Merge, the DIFFICULTY opcode was renamed to PREVRANDAO

```
            difficulty: if eth_block.difficulty.is_zero() {
                eth_block
                    .mix_hash
                    .unwrap_or_default()
                    .to_fixed_bytes()
                    .into()
            } else {
                eth_block.difficulty
            },
```

> another remainder is that we need to support prevrandao opcode (renamed from DIFFICULTY). I make this change  https://github.com/scroll-tech/zkevm-circuits/blob/1ea9b5970ff873191de29e625687765f427326dd/bus-mapping/src/circuit_input_builder/block.rs#L119-L127 to be compatible with latest node/libs.

_Originally posted by @lispc in https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1362#issuecomment-1517697230_
            
References

- https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
- https://eips.ethereum.org/EIPS/eip-4399

**Comment by ameya-deshmukh** [comment]
@ChihChengLiang is this open to take up?

**Comment by ChihChengLiang** [comment]
Hi @ameya-deshmukh,
Thanks for your interest in contributing to this task.
Yes, the issue is open to take up. But it would be great if you could help update the spec first https://github.com/privacy-scaling-explorations/zkevm-specs/issues/437.

**Comment by ameya-deshmukh** [comment]
Great, thank you!

**Comment by dyxushuai** [comment]
Is this issue working in progress? Maybe I can help for it, we met this issue and fixed in our project. @ChihChengLiang @ameya-deshmukh

**Comment by ChihChengLiang** [comment]
Hi @ameya-deshmukh, Can you give an update? It's okay if you are too busy and not able to work on this task.

**Comment by dyxushuai** [comment]
> Hi @ameya-deshmukh, Can you give an update? It's okay if you are too busy and not able to work on this task.

So, may I claim this?

**Comment by ameya-deshmukh** [comment]
Hey @dyxushuai would you like to work on it together? I wasn't able to get started on this.

**Comment by dyxushuai** [comment]
> Hey @dyxushuai would you like to work on it together? I wasn't able to get started on this.

Of course, I will begin to do this ASAP

**Comment by ameya-deshmukh** [comment]
Where can we communicate? We can split up the tasks.

**Comment by dyxushuai** [comment]
@ameya-deshmukh You can email me by johnxu@duck.com

**Comment by johntaiko** [comment]
> difficulty: if eth_block.difficulty.is_zero() {
>                 eth_block
>                     .mix_hash
>                     .unwrap_or_default()
>                     .to_fixed_bytes()
>                     .into()
>             } else {
>                 eth_block.difficulty
>             },

I think this is good enough for eip-4399 🐶

**Comment by dyxushuai** [comment]
> difficulty: if eth_block.difficulty.is_zero() {
>                 eth_block
>                     .mix_hash
>                     .unwrap_or_default()
>                     .to_fixed_bytes()
>                     .into()
>             } else {
>                 eth_block.difficulty
>             },

I think this logic is good enough to fit the eip-4399 🐶, but we don't like Geth, we don't have flags for features or forks, so we can only keep forward compatibility

**Comment by KimiWu123** [comment]
Hey @dyxushuai and @ameya-deshmukh, could you give an update? It's fine if both of you are busy and unable to work on this task.

**Comment by dyxushuai** [comment]
> Where can we communicate? We can split up the tasks.

> Hey @dyxushuai and @ameya-deshmukh, could you give an update? It's fine if both of you are busy and unable to work on this task.

Sorry, I think @ameya-deshmukh didn't message me. So, I will give a PR in the next few days alone.

**Comment by ameya-deshmukh** [comment]
Sure! Sorry I couldn't devote time to this.

**Comment by ed255** [comment]
It seems no one is currently working on this issue, so I left it unassigned (please let me know if this is not the case!)

**Comment by dyxushuai** [comment]
> It seems no one is currently working on this issue, so I left it unassigned (please let me know if this is not the case!)

Sorry, I just got back from a long vacation. (2 weeks)

@ed255 @KimiWu123 https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1648 This is my implementation of prevrandao opcode. If you find any problems, please let me know, for now, I can respond ASAP.
