### ISSUE TITLE
align gas_limits & nonce from word to u64

### ISSUE THREAD

**Issue by hero78119** [privacy-scaling-explorations/zkevm-circuits#1377]
### Describe the feature you would like

Due to `ether-core` lib some basic type defining gas_limits and nonce in Word type, hence in current codebase most of place we are aligned with it. However this two types should be u64 instead.

**Comment by ChihChengLiang** [comment]
I noticed the problem too. Do you have any tasks blocked by this one? Should we prioritize it?

**Comment by hero78119** [comment]
> I noticed the problem too. Do you have any tasks blocked by this one? Should we prioritize it?

Right now no blocked. This task is pretty isolated. Since it touch widely of the codebase, we can work on it later once we reduce the number of other open pr.

**Comment by ChihChengLiang** [comment]
Taking this.
