### ISSUE TITLE
EVM Circuit: Refactor word_rlc into word lo/hi

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1379]
Specs: https://github.com/privacy-scaling-explorations/zkevm-specs/pull/390

Blocked/Conflicted by:
- [ ] CREATE A https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1356
- [ ] CREATE B https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1357
- [ ] CREATE C https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1358
- [ ] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1265
- [ ] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1292

Depends on:
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1388

**Comment by hero78119** [comment]
- [ ] adapt lo/hi refactor
- [ ] pass all unittest
   - [ ]  review H256 and U256 endian handling

**Comment by ChihChengLiang** [comment]
@hero78119 Can we move the pending tasks listed here to #1487 and close this issue?

**Comment by hero78119** [comment]
> @hero78119 Can we move the pending tasks listed here to #1487 and close this issue?

Yes! I closed this issue and move related to #1487
