### ISSUE TITLE
Bytecode Circuit: Refactor word_rlc into word lo/hi

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1380]
Specs: https://github.com/privacy-scaling-explorations/zkevm-specs/pull/390

Blocked/Conflicted by:
- [ ] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1348

Depends on:
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1388

**Comment by ChihChengLiang** [comment]
closed by #1468
