### ISSUE TITLE
MPT Circuit: Refactor word_rlc into word lo/hi

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1381]
Specs: https://github.com/privacy-scaling-explorations/zkevm-specs/pull/390

Blocked/Conflicted by:
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/398

Depends on:
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1388

**Comment by ChihChengLiang** [comment]
Fixed in #1531
