### ISSUE TITLE
Merge structs between CIB and evm circuit witness

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#1391]
### Describe the feature you would like

This is a continuation of unfinished tasks in #528

We explore more merging opportunities between the structs in the circuit input builder(CIB) and the evm circuit witness.

- [ ] Bytecode. The witness has one more field, the bytecode hash. If we add the bytecode hash in CIB's Bytecode struct, then we can safely remove the struct in witness.rs. WIP
- [ ] Block. witness::Block and witness::BlockContext have many overlapping fields with CIB::Block. We can create better structs in CIB and remove some of the witness's block structs.
- [x] ExecStep. Many duplicated fields between witness::ExecStep and CIB::ExecStep, which suggests possible struct merging.
- [ ] Tx. Further deduplication seems still possible. In review https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1457
- [x] Call

**Comment by ed255** [comment]
A bit related to this issue: https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1451
