### ISSUE TITLE
The recent CI hanging and failure

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#1417]
### Describe the bug

There are two styles of failure:

The first one is that the self-host runner couldn't pick up the task. The current instances were canceled, so I'll post a new one here if the failure happens again.

The second one is the CI hangs at a particular stage. Notably, the "Run light tests"
- https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/5011576441/jobs/9003329648 ![Screenshot 2023-05-19 at 3 39 33 PM](https://github.com/privacy-scaling-explorations/zkevm-circuits/assets/3391420/14f1f1b6-b643-4672-8b70-6cfd89e43fbc)
- https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/5004358516/jobs/8966828870 This one, the operation was canceled after hanging 6hrs.

**Comment by AronisAt79** [comment]
@ChihChengLiang 

same freeze condition occurs when testtool is invoked manually.
```
running 13 tests
test abi::test::test_abi_encoding ... ok
test statetest::json::test::test_json_parse ... ok
test statetest::yaml::test::combinations ... ok
test utils::test::networks ... ok
test statetest::yaml::test::parse ... ok
test statetest::yaml::test::marked_as_exception_and_fails ... ok
test statetest::yaml::test::marked_as_exception_but_does_not_fail ... ok
test statetest::yaml::test::bad_balance has been running for over 60 seconds
test statetest::yaml::test::bad_code has been running for over 60 seconds
test statetest::yaml::test::bad_nonce has been running for over 60 seconds
test statetest::yaml::test::result_pass has been running for over 60 seconds
test statetest::yaml::test::sstore has been running for over 60 seconds
test statetest::yaml::test::test_result_bad_storage has been running for over 60 seconds
```
strace shows that testtool process is using a futex system call to wait for some condition to be met:

```
futex(0x55a5655c4c88, FUTEX_WAIT_BITSET_PRIVATE, 4294967295, NULL, FUTEX_BITSET_MATCH_ANY
```
we also notice that nightly run on jenkins test automation is stack in a similar manner since May 18th. ( we have similar strace indication), but this happens in heavy tests as well.

While investigation is ongoing, 
@adria0 are you able to further debug via a local run of the light test suite? Are you also maybe aware if there are any recent changes in testtool that could break the workflow or cause it to get stack in waiting mode?

**Comment by ChihChengLiang** [comment]
Meanwhile, I'm wondering if #1420 is relevant. A hanging behavior was introduced in #1406, roughly the same time that CI hangs.

**Comment by ed255** [comment]
I've made a PR with a possible fix, let's wait for the CI tests to pass to confirm it's resolved: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1421

**Comment by ed255** [comment]
> The first one is that the self-host runner couldn't pick up the task. The current instances were canceled, so I'll post a new one here if the failure happens again.

This has not been resolved yet

> The second one is the CI hangs at a particular stage. Notably, the "Run light tests"

This was resolved with https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1421

**Comment by AronisAt79** [comment]
Thanks for the summary @ed255 . Unfortunately there is yet no reaction on the discussion :(
