### ISSUE TITLE
support byte16 range check

### ISSUE THREAD

**Issue by hero78119** [privacy-scaling-explorations/zkevm-circuits#1426]
### Describe the feature you would like

part of the optimisation proposed during word lo/hi refactor

- [ ] attach report to show column occupancy by `cargo test -p zkevm-circuits --release get_exec_steps_occupancy --features test -- --nocapture --ignored`

**Comment by lispc** [comment]
there is already a u16 fixed lookup inside state circuit.  So maybe we can refactor codes a bit so other sub curcuits can use that?

**Comment by hero78119** [comment]
> there is already a u16 fixed lookup inside state circuit. So maybe we can refactor codes a bit so other sub curcuits can use that?

Right, thanks for the heads up!  I think `u8/u16` defined in state circuit can all be reused with evm circuit (and maybe other circuit which need range check)
