### ISSUE TITLE
TestContext sets tx nonces incorrectly (sometimes)

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1461]
The TestContext is used to setup an Ethereum state, run txs on it with go-ethereum and get the resulting traces.  When using various transactions, the TestContext automatically assigns a default nonce to them, in sequence starting from 0 (and these values can then be overwritten by the user).  This only works assuming all txs come from the same address and this address has nonce 0 at the beginning: 
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/06cce9f01d252bf9b1e84cebc22ac982a12ddc99/mock/src/test_ctx.rs#L135-L146

This automatic assignment of nonces doesn't work for example when you have 2 txs from different accounts (each with `nonce = 0`).  I think the automatic assignment should only be implemented it if covers all cases, because otherwise the developer may take some time to realize what's failing: When having 2 txs from different accounts the developer may assume that each tx.nonce is 0 (because that's the default value of the `MockTransaction`), but they will find that the second tx is sent with `nonce = 1`.

So I think we should either remove this automatic (sometimes incorrect) nonce assignment, or alternatively do it right (by inspecting the from address, and checking the nonces in the setup `accounts`).

**Comment by zemse** [comment]
Thanks for marking this as good first issue. I am interested in taking this up.
