### ISSUE TITLE
Pass the Keccak Circuit unit tests in word-lo-hi branch

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1477]
The Keccak Circuit word lo/hi refactor was merged via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1434

After this https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1442 was resolved, the unit test are building, so we need to review the unit tests of the circuit to verify that they pass, and fix as necessary if they don't.  We can do this now to reduce the amount of work we will face when merging the word-lo-hi branch to main

**Comment by hero78119** [comment]
Locally verified, keccak circuit unittest currently is passed, therefore close this ticket :)
