### ISSUE TITLE
[word lo/hi] optimisation and improvements.

### ISSUE THREAD

**Issue by hero78119** [privacy-scaling-explorations/zkevm-circuits#1487]
### Describe the feature you would like

Aimed as super issue to record some further optimisation/housekeeping tasks related to word-lo-hi refactor. 

cc @ed255 @ChihChengLiang @adria0 @KimiWu123 

- [ ] polishing word arithemetics syntax, see discusssion https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1411#discussion_r1234952340
- [ ] In `zkevm-circuits/src/table.rs` check all the fields in table called
  `foo_word` and remove the legacy ones (`foo`), rename `foo_word` to `foo.
- [ ] https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1479 
- [ ] explore static assertion on Word type api
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1491 Rename `foo_new` to `foo`, `FooNew` to `Foo`:
	- Delete `Foo::construct`, rename `Foo::construct_new` to `Foo::construct` for
	  `AddWordsGadget`, `MulAddWordsGadget`, `TransferWithGasFeeGadget`,
	  `MemoryAddressGadget`, `ModGadget`, 
	- `WordNew` import alias to `Word`
	- `original_word_new` to `original_word`
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1491 Rename `foo_word` methods in ConstraintBuilder to `foo`:
	- `stack_pop_word`
	- `stack_push_word`
	- `account_read_word`
	- `account_write_word`
	- `tx_context_lookup_word`
	- `block_lookup_word`
	- `bytecode_lookup_word`
	- `bytecode_length_word`
	- `account_storage_access_list_read_word`
	- `tx_refund_write_word`
	- `account_storage_read_word`
	- `account_storage_write_word`
	- `stack_lookup_word`
	- `keccak_table_lookup_word`
	- Rename `tx_context_as_word32` to `tx_context_as_word`
- [x] u16 range check https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1427
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1491 Remove `_word` from `AbsWord::{x_word, x_abs_word}`
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1491 Remove `_word` from `memory_gadget expr_word`
- [x] Remove anything that contains "legacy"
	- `MulAddWords512Gadget::legacy_construct`

**Comment by ChihChengLiang** [comment]
It looks like this task is done.
The only task on the list that is open is #1479. We should do it after merging lo-hi to main. @hero78119 Feel free to reopen if you have something to add.

**Comment by hero78119** [comment]
One of them should be resolved before merge main: rename all `foo_word` to `foo`

For others can be lower priority and `AFTER` word-lo-hi merge back to main.
