### ISSUE TITLE
Proof chunking exploration

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1498]
Initial document https://hackmd.io/1h_McCIcTpmILN0xZlbnSw

Feel free to extend the document with more ideas, create new ones, or discuss ideas in this issue.

It seems scroll has already started working on this https://github.com/scroll-tech/zkevm-circuits/blob/proof-aggregation-circuit/aggregator/README.md it would be great to sync on the details!

------- Task lists ----------
- [x] #1601
- [x] #1696 
- [x] #1602
- [x] #1603
- [x] #1604
- [ ] #1778
- [ ] blocked by #1783 
- [ ] #1631

**Comment by ChihChengLiang** [comment]
Next step:

- @hero78119 sync up Arantxa with the problem description.
- Work on experimental PoCs based on the idea we have so far.

**Comment by hero78119** [comment]
https://hackmd.io/NPDfrFfjQoa5ebzH6bS39w?view proof chunk design docs. Pending for design alignment then will raise list of sub-issues

**Comment by ed255** [comment]
Next step: get review of the document by Arantxa

**Comment by ChihChengLiang** [comment]
@hero78119 will give an update on this one

**Comment by hero78119** [comment]
Updated on 19 Oct 2023 

Ongoing Tasks
- super circuit: https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1601
- root circuit: https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1602
- Taiko: Tto support bus-mapping change on multiple chunks
