### ISSUE TITLE
Investigate error log on ci light-test padding_len overflow

### ISSUE THREAD

**Issue by hero78119** [privacy-scaling-explorations/zkevm-circuits#1507]
### What command(s) is the bug in?

on ci light test of all the exiting pull requests. 

### Describe the bug

Can find this error log in all the existing pull request ci light test. 

For example https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/5413925634/jobs/9840226199?pr=1500

Light test is pass, however this error shows a concern. 
~It seems only happened when one command matching more > 1 tests. Maybe related to recent modification of evm circuit cache.~

```
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 41, rows_len: 42
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 41, rows_len: 42
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 41, rows_len: 42
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 41, rows_len: 42
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 41, rows_len: 42
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 41, rows_len: 42
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 34, rows_len: 35
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 34, rows_len: 35
[2023-06-29T15:26:28Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 34, rows_len: 35
[2023-06-29T15:26:29Z ERROR zkevm_circuits::witness::rw] RwMap::padding_len overflow, target_len: 34, rows_len: 35
```

### Concrete steps to reproduce the bug. If it's able reproduce via testool, please share `test_id` from jenkins report

Can reproduce this error locally on main branch
```
RUST_LOG=DEBUG cargo test --features test --package zkevm-circuits --lib -- evm_circuit::execution::create::test::test_create_address_collision_error
```

This error not dedicated to `create`. ~~Any command matching > 1 tests can reproduce~~

**Comment by hero78119** [comment]
Hi @davidnevadoc do you think is it related to the recent change https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1445 ?

**Comment by ed255** [comment]
> Hi @davidnevadoc do you think is it related to the recent change #1445 ?

Yes, I think this comes directly related to this discussion https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1445#discussion_r1223194434

My guess is that there's a check that is too "overprotective" and logs an error even though the parameters are safe.  The other option is that we're skipping enabling some necessary rows (and thus skipping their constraints), which could mean a soundness issue.  So I believe this needs some investigation.  I would also suggest to avoid logging errors without panicking in such situations; if the circuit parameters not enough to hold the full witness, we should panic.

**Comment by hero78119** [comment]
> Yes, this was introduced in #1445 . I was a bit on the fence about this issue because I too got this error. However, I think it is due to what @ed255 mentioned: An overprotective check. By having `max_rws +3` here
> 
> https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/3575aabd7ce18664d14e21d4e33b5f5f8aff6e39/bus-mapping/src/circuit_input_builder.rs#L377
> 
> 
> the error will go away. But I could not logically explain such a magic number so I left the `+1` which is what I think makes sense according to the specs.

Thanks for the hint. After I applied the `max_rws +3` commit https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1504/commits/360ad8102449b6f0a8338aaccef2b17e9fa7f022 the error indeed gone.

However agree that we should investigate what's the root cause for magic number + 2

**Comment by hero78119** [comment]
> Yes, this was introduced in #1445 . I was a bit on the fence about this issue because I too got this error. However, I think it is due to what @ed255 mentioned: An overprotective check. By having `max_rws +3` here
> 
> https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/3575aabd7ce18664d14e21d4e33b5f5f8aff6e39/bus-mapping/src/circuit_input_builder.rs#L377
> 
> 
> the error will go away. But I could not logically explain such a magic number so I left the `+1` which is what I think makes sense according to the specs.

Hi @davidnevadoc , after L377, there is `send_end_block` which still push 2 RW op plus context lookup, so if wanna double confirm if we set  `max_rws = max_rws + 1`  but not counting rw op happened in set_end_block is it still correct?

**Comment by hero78119** [comment]
Tried to fixed in PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1515/

**Comment by hero78119** [comment]
> > there is `send_end_block` which still push 2 RW op plus context lookup
> 
> Oh there it is!! You are right, I missed those and that is why I left the `+1`. Now that we know where the other 2 come from I'm comfortable having the `+3` 👍

Actually +1 + 1 (overall +2) work in this case, 😄 the pr should fixed it generally 👆
