### ISSUE TITLE
Improve BufferReaderGadget

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#1513]
### Describe the feature you would like

We should add some tests for `BufferReaderGadget`.

- The tests should cover different start addresses and end addresses

See #1485 for more insights.

**Comment by NOOMA-42** [comment]
Can I pick up this issue? 

p.s. This seems also relate to https://github.com/privacy-scaling-explorations/zkevm-specs/issues/440

**Comment by ChihChengLiang** [comment]
Hi @NOOMA-42, 
Yes, feel free to pick up this issue! The spec 440 issue you mentioned is related too. Feel free to take that issue too!
