### ISSUE TITLE
ecdsa verifier

### ISSUE THREAD

**Issue by barryWhiteHat** [privacy-scaling-explorations/zkevm-circuits#153]
We have been working on generic wrong field ec operations. The goal of this work is to make ecsda verifyer and recursion to allow proof aggregation. 

https://github.com/kilic/halo2wrong is the wrong field arithmetic. We are working on a repo to do elliptic curve operations and plan to produce a trait that others can use. 

This issue is given this trait implement ecdsa signature verification such that a string signed in metamask can be verified inside zkevm.

**Comment by ed255** [comment]
The ECDSA verifier is implemented in the halo2wrong repository.
