### ISSUE TITLE
bug: coinbase account should be created first before being added refund balance

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1554]
### Describe the bug

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/68b4f06c928af3d9a706e80c4e103de8126e3912/bus-mapping/src/evm/opcodes/begin_end_tx.rs#L283

There are ~4000 failures in testool report <http://testool-public.s3-website.eu-central-1.amazonaws.com/nightly.1691192288.6cf2929.html#by_folder> with err msg like "RWTable Account field WRITE lookup to non-existing account rwc". Most of these are related to this bug.

We already have a fix: https://github.com/scroll-tech/zkevm-circuits/blob/develop/bus-mapping/src/evm/opcodes.rs#L924-L931

(orignal PR: https://github.com/scroll-tech/zkevm-circuits/pull/588)

will fix that to upstream soon

**Comment by ChihChengLiang** [comment]
@hero78119 will follow up on this.

**Comment by lispc** [comment]
@lightsing
