### ISSUE TITLE
Fix rw counter delta of CommonErrorGadget

### ISSUE THREAD

**Issue by KimiWu123** [privacy-scaling-explorations/zkevm-circuits#1576]
### Describe the feature you would like

There are two rw lookups inside `CommonErrorGadget` ,and those are `IsSuccess` and `RwCounterEndOfReversion`. However, the rw counter delta is passed from outside (that means callers have to have an extra `+2`) which doesn't make sense and could have bugs potentially.

**Expectation**:
Moved the `+2` into `CommonErrorGadget::construct_with_return_data()`

**Comment by ChihChengLiang** [comment]
resolved in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1577
