### ISSUE TITLE
proposal: return error instead of panic when max_rws not enough for CircuitInputBuilder<FixedCParams>

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1592]
### Describe the feature you would like

Do you think it is good to use return err to replace the panic here?

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/circuit_input_builder.rs#L301-L307

We have a PR to fix this already. https://github.com/scroll-tech/zkevm-circuits/pull/804/commits/efff603da5706d216e7917af85f0aacaecc46496 if it is ok, i can port the PR upstream.

This PR changes some methods signatures like: `CircuitInputStateRef::call_context_read/write() /*-> ()*/` to  `CircuitInputStateRef::call_context_read/write() -> Result<(), Error> `.  So i need some consensus before continuing.

**Comment by ChihChengLiang** [comment]
I like Error over panics. I think we can make the Error more traceable with the following improvements.

In https://github.com/scroll-tech/zkevm-circuits/commit/efff603da5706d216e7917af85f0aacaecc46496 the error looks like this:
```
        if rwc > max_rws {
            log::error!("rwc > max_rws, rwc={}, max_rws={}", rwc, max_rws);
            return Err(Error::InternalError("rws not enough"));
        };
```
Can we extend an error case so it looks like:

```
        if rwc > max_rws {
            return Err(Error::RwsNotEnough(max_rws, rwc));
        };
```
Or at least something like:
```
        if rwc > max_rws {
            let msg = format!("rwc > max_rws, rwc={}, max_rws={}", rwc, max_rws)
            log::error!(msg);
            return Err(Error::InternalError(msg));
        };
```

**Comment by lispc** [comment]
ok i can change to

```
        if rwc > max_rws {
            return Err(Error::RwsNotEnough(max_rws, rwc));
        };
```

i will continue this issue.   (dozens of files in bus-mapping will be changed since call_context_read/call_context_write return value changed from () to Result.)

**Comment by ChihChengLiang** [comment]
Sounds great! Thank you @lispc

**Comment by ChihChengLiang** [comment]
Hi @lispc, do you plan to work on this one?

**Comment by lispc** [comment]
will pick this pr this week
