### ISSUE TITLE
[proof-chunk] super circuit implement new permutation gadget for evm rwtable lookup

### ISSUE THREAD

**Issue by hero78119** [privacy-scaling-explorations/zkevm-circuits#1601]
This issue focus on super circuit change scope. 

Based on the design https://hackmd.io/NPDfrFfjQoa5ebzH6bS39w 
There will be 2 RwTable
- [new] chronologically sorted rwtable
- [existing] multi-sorted rwtable.

> multi-sorted rwtable https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/1bc1eef6344fba33105b018216d7af5f04550cd8/zkevm-circuits/src/witness/rw.rs#L141-L150

EVM circuit will switch to lookup into new chronologically-sorted rwtable, and at the end we need to constraints multi-sorted rwtable vs chronologically sorted rwtable are permutation of each others.

To prove permutation of 2 tables, we can introduce a new permutation gadget to layout the custom gates to constraint permutation fingerprints updated of 2 rwtable, and at the last row we constraints the permutation fingerprints equality of 2 rwtable fingerprints.

## Permutation fingerprint challenge

To update the permutation fingerprints there need a challenge. In super circuit scope we can trust challenge bypass from public-input first, and constraint its consistency from row 1 to the end row. The validation of challenge will be outside of super circuit, which is in the scope of root circuit + snark-verifier in another issues. https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1603

## Last chunk (reminded by @ed255 )
Introduce new public input `is_last_chunk: bool` to toggle some extra custom gates check for last chunk
- Last step should be `EnbBlock`
- permutation fingerprint LHS/RHS equality
- .... 

Besides to keep scope smaller, this issue keep single supercircuit proof (chunk) as usual. Multiple supercircuit proof chunk can be defered into https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1604

**Comment by ed255** [comment]
Status: this issue has already been resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1641 and is now in the branch https://github.com/privacy-scaling-explorations/zkevm-circuits/tree/proof-chunk but not yet in main
