### ISSUE TITLE
[proof-chunk] explore snark-verifier in root circuit to append custom protocols

### ISSUE THREAD

**Issue by hero78119** [privacy-scaling-explorations/zkevm-circuits#1602]
Based on proof chunk [design](https://hackmd.io/NPDfrFfjQoa5ebzH6bS39w) we need to add some custom protocols aside from original super-circuit protocol. 

First there is requirement to using poseidon hash to compute permutation fingerprint challenge based on column commitment. and an optimise version is appending poseidon hash protocol (circuit) at the end of of supercircuit protocol once, giving there might be more supercircuit protocol for more than once chunk.

> We can support fixed number of super circuit proof with empty proof padding. It will also be nice to leave door open to support dynamic number supercircuit proof.

There are also some custom protocols. In summary
- poseidon hash to compute challange
- constraint between super-circuit proofs, e.g. rwtable column consistency across proof via public input, challenge consistency across proof.
- ~~assure some flag toggle `on` at last supercircuit proof (via public input ?)~~
- assure challenge equality with last chunk

**Comment by hero78119** [comment]
Hey @han0110 do you have any input based on the proposol ?

**Comment by han0110** [comment]
I feel we don't need to change `snark-verifier` to support these, `snark-verifier` could be seen as a tool to verify a plonk proof only, and later on you could reuse the commitments to do further checks, so perhaps Root circuit will be the target to update.

**Comment by hero78119** [comment]
### Updated
fingerprint equality on last chunk is done in super circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1674
