### ISSUE TITLE
refactor(bytecode): unify circuit style

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1607]
### Describe the feature you would like

due to historical reasons, the codes of bytecode circuit is a bit different than other circuits:

1. circuit implementation file location.  Other circuits puts circuit/config implementation directly inside `src`, while bytecode circuit has another level of hierarchy.

```
 $ wc -l zkevm-circuits/src/*circuit.rs
      12 zkevm-circuits/src/bytecode_circuit.rs
     854 zkevm-circuits/src/copy_circuit.rs
     528 zkevm-circuits/src/evm_circuit.rs
     550 zkevm-circuits/src/exp_circuit.rs
    1069 zkevm-circuits/src/keccak_circuit.rs
     858 zkevm-circuits/src/mpt_circuit.rs
    1653 zkevm-circuits/src/pi_circuit.rs
     190 zkevm-circuits/src/root_circuit.rs
     614 zkevm-circuits/src/state_circuit.rs
     493 zkevm-circuits/src/super_circuit.rs
     361 zkevm-circuits/src/tx_circuit.rs
```

2. the use of `minimum_rows: meta.minimum_rows()`. Other circuits don't use this.

**Comment by ChihChengLiang** [comment]
It looks like the actions to take are:

1. Move the bytecode circuit to the correct file. 
2. Remove the `minimum_rows: meta.minimum_rows()`, and fix the tests that depends on `minimum_rows`.

Note that `minimum_rows` is the number of reserved rows for blinding factors and other stuff. It helps the verifier compute the maximum possible number of rows we can utilize. 

Here's how it works. The bytecode circuit takes the parameter "size" to configure, usually, the size is two to the power of degree, as the example in the circuit benchmark shows.

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/bb0d9e479a8081c5e7d903b93d68b97c66b46bce/circuit-benchmarks/src/bytecode_circuit.rs#L49-L53

The bytecode circuit then subtracts `minimum_rows` from size, resulting in the maximum number of usable rows. The verifier then sets the last row selector `q_last` there. 

However, I realized that's not how the current supercircuit works. We didn't configure the bytecode circuit size in the super circuit with degrees but instead with the number of bytes (technically the number of bytes plus the number of headers) to prove.

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/bb0d9e479a8081c5e7d903b93d68b97c66b46bce/zkevm-circuits/src/bytecode_circuit/circuit.rs#L795-L798

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/bb0d9e479a8081c5e7d903b93d68b97c66b46bce/bus-mapping/src/circuit_input_builder.rs#L370

The way we configure bytecode circuit in the supercircuit is problematic in two ways: 

1. The setup time circuit description `q_last` is determined by the proving time bytes to prove. This problem will not be revealed in CI.

2. The `q_last` is configured to be the `bytecode size- minimum_rows`. This should cause some bugs in the supercircuit. 

To fix 2, we should change it to something like this.
```
fn new_from_block(block: &witness::Block<F>) -> Self { 
     Self::new(block.bytecodes.clone(), next_power_of_2(block.circuits_params.max_bytecode))
 } 
```
