### ISSUE TITLE
Frequent CI failure and lost logs

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#1629]
### What command(s) is the bug in?

It is on automatic CI run.

### Describe the bug

We recently encountered frequent CI run failures that look like this. It failed without keeping any logs.

https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/6300080882/job/17104708809?pr=1624

<img width="1074" alt="Screenshot 2023-09-26 at 1 02 17 PM" src="https://github.com/privacy-scaling-explorations/zkevm-circuits/assets/3391420/a63e2a39-9974-41a0-a406-578b875fcacc">

I tried to run with the option "Enable debug logging" checked. 

<img width="637" alt="Screenshot 2023-09-26 at 1 06 08 PM" src="https://github.com/privacy-scaling-explorations/zkevm-circuits/assets/3391420/7e05e2b6-e558-4286-890a-8a81743b33e9">

Then I saw this message for the first time in the running result.

<img width="1026" alt="Screenshot 2023-09-26 at 1 01 29 PM" src="https://github.com/privacy-scaling-explorations/zkevm-circuits/assets/3391420/d8283559-4c2e-433c-bc73-847282435142">

Here's the text expression.

> [Heavy unit tests](https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/6300080882/job/17104708809)
The self-hosted runner: ip-10-15-1-202 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

### Concrete steps to reproduce the bug. If it's able reproduce via testool, please share `test_id` from jenkins report

I don't know a way to reproduce it. It happens randomly.

**Comment by ntampakas** [comment]
There seems to be an issue with the GitHub API when the github-ops workflow triggers it to receive job status. F.x., even though the job on the GitHub dashboard seems to be **in_progress**, the API call returns a **completed** status:
```
  "url": "https://api.github.com/repos/privacy-scaling-explorations/zkevm-circuits/actions/jobs/17130797112",
  "html_url": "https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/6300080882/job/17130797112",
  "status": "completed",
  "conclusion": "success", 
```
As a result, the github-ops workflow correctly terminates this specific instance, as the job it was assigned to do has been completed. I'm not sure if this is a recent generic API issue or if it only happens for this specific workflow.

**Comment by ntampakas** [comment]
An update follows regarding the issue:
When a workflow consists of two or more jobs that utilize self-hosted runners, there are instances where a job id is associated with the 'incorrect' ephemeral runner.


Here are some details on how github-ops works:
When a workflow requiring ephemeral runners is in status queue, an ephemeral runner is spawned for each job.
Each ephemeral runner is virtually linked to a specific job, using a tag that comprises the workflow id and job id.
Unfortunately, GH runner app doesn' t provide the option to associate a specific process with a specific job-id, rather it associates it with the workflow id.
Consequently, if there are two ephemeral runners, the one initialized more quickly, will claim the first job in the queue.

Generally, that wouldn' t be a problem, but the github-ops workflow is designed to check for hanged ephemeral runners and terminate them.
This function checks if the job id linked with a specific runner is completed; if it is marked as completed, and the ephemeral runner is running for any reason, is gets terminated.

F.x. the workflow with id 100 has 2 jobs with id 111 and 222 in the queue.
Two ec2 instances are launched with tag names 100-111 and 100-222. When the 100-111 instance executes job id 111 and 100-222 instance executes job-id 222, everything is working as expected.
In the opposite scenario, and if some other conditions are met*, the github-ops workflow will terminate the wrong instance assuming that the job is is completed.

For time being a workaround has been applied and i am currently investigating options to implement a permanent solution.

\* the period github-ops workflow is executed (the schedule event can be delayed during periods of high loads of GitHub Actions workflow runs), what is the job is that was completed first, etc.

**Comment by ntampakas** [comment]
Two methods were added to the GH-ops workflow in order to address the issue:
- The instance termination function is triggered against running instances after 90' of uptime.
- CPU Load is checked for each instance via cloudwatch.

I spent some time adapting the workflow scripts to use job IDs, but it seems that this is not supported by GH.

Please feel free to reopen the issue if the specific pattern is replicated again.

**Comment by ChihChengLiang** [comment]
Thank you @ntampakas for investigating and fixing this issue!
