### ISSUE TITLE
Report halo2 stats of each sub circuit

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1645]
Write a binary (or utility function triggered by a test) that reports: 
- number of gates
- max degree of gates
- number of advice, instance and public columns
- number of rotations?
- number of lookups
- number of copy constraints (or number of column pairs involved in copy constraints)

**Comment by lispc** [comment]
I have this https://github.com/scroll-tech/zkevm-circuits/blob/7d9bc181953cfc6e7baf82ff0ce651281fd70a8a/zkevm-circuits/src/util.rs#L294 haha

**Comment by ed255** [comment]
> I have this https://github.com/scroll-tech/zkevm-circuits/blob/7d9bc181953cfc6e7baf82ff0ce651281fd70a8a/zkevm-circuits/src/util.rs#L294 haha
> 
> https://github.com/scroll-tech/zkevm-circuits/blob/7d9bc181953cfc6e7baf82ff0ce651281fd70a8a/zkevm-circuits/src/super_circuit.rs#L257 And print these nums after each sub circuit

That's awesome!  We can just port that, as it fulfills our exact needs :D
