### ISSUE TITLE
Fix benchmarks

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1646]
In https://github.com/privacy-scaling-explorations/zkevm-circuits/tree/main/circuit-benchmarks/src we have a series of tests to build a proof of each subcircuit to get benchmark results.
These benchmarks have been broken for a while and need to be fixed.

Example:
```
$ DEGREE=10 cargo test --features=benches state_circuit::tests::bench_state_circuit_prover
warning: `zkevm-circuits` (lib) generated 1 warning
    Finished test [unoptimized + debuginfo] target(s) in 0.23s
     Running unittests src/lib.rs (/mnt/data/dev/git/zkevm/zkevm-circuits/target/debug/deps/circuit_benchmarks-6d442a10c45f553e)

running 1 test
test state_circuit::tests::bench_state_circuit_prover ... FAILED

failures:

---- state_circuit::tests::bench_state_circuit_prover stdout ----
Start:   State Circuit [Setup generation] with degree = 10
End:     State Circuit [Setup generation] with degree = 10 .........................1.323s
thread 'state_circuit::tests::bench_state_circuit_prover' panicked at 'keygen_vk should not fail: NotEnoughRowsAvailable { current_k: 10 }', circuit-benchmarks/src/state_circuit.rs:58:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    state_circuit::tests::bench_state_circuit_prover

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 9 filtered out; finished in 1.33s

error: test failed, to rerun pass `--lib`
```

**Comment by zemse** [comment]
Since StateCircuit uses the U16 table, it seems to me that the degree should have to be at least 16. Should the fix simply add a minimum default value for the DEGREE env [similar to other tests](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/09651d40afc59462fd943e9789be8f8b0ccb90d9/circuit-benchmarks/src/bytecode_circuit.rs#L34)?

How are the benchmark tests triggered? Is it run individually passing in the DEGREE manually or using `cargo test` inside circuit-benchmarks?

```
circuit-benchmarks $ cargo test --features=benches
```

**Comment by ed255** [comment]
> Since StateCircuit uses the U16 table, it seems to me that the degree should have to be at least 16. Should the fix simply add a minimum default value for the DEGREE env [similar to other tests](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/09651d40afc59462fd943e9789be8f8b0ccb90d9/circuit-benchmarks/src/bytecode_circuit.rs#L34)?

That makes sense.  Your suggestion would be a possible solution.  Another solution that comes to my mind is to just check if DEGREE is >= 16 for the StateCircuit benchmark, and if not panic early with a message.  Also the same process should be done for the other benchmakrs: check if the other circuits have a minimum degree, and either panic with a useful message when degree is lower, and/or set a default degree that is the minimum.

> How are the benchmark tests triggered? Is it run individually passing in the DEGREE manually or using `cargo test` inside circuit-benchmarks?
> 
> ```
> circuit-benchmarks $ cargo test --features=benches
> ```

You can trigger them with this command from the `circuit-benchmarks` directory:
```
DEGREE=10 cargo test --features=benches state_circuit::tests
```
You can replace `state_circuit` by any of the implemented benchmarks which are:
- bytecode_circuit
- copy_circuit
- evm_circuit
- exp_circuit
- mpt_circuit
- packed_multi_keccak
- pi_circuit
- state_circuit
- super_circuit
- tx_circuit

**Comment by ChihChengLiang** [comment]
Assign this task to @zemse
