### ISSUE TITLE
Improve external tracer error handling

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#165]
The external tracer currently has a few places where errors don't contain a lot of context, which can be improved.

# Capture error in the `trace` function
- https://github.com/appliedzkp/zkevm-circuits/blob/8117aa1f536c9b94fd52f1727e81b05b4bf334bd/bus-mapping/src/external_tracer.rs#L53 
There are a few `map_err(|_| Error::TracingError)`, which lose the original error.  It would be better if we can wrap that error inside the `Error::TracingError`

# Avoid expects / unwraps and return error instead
- https://github.com/appliedzkp/zkevm-circuits/blob/8117aa1f536c9b94fd52f1727e81b05b4bf334bd/bus-mapping/src/external_tracer.rs#L73
- https://github.com/appliedzkp/zkevm-circuits/blob/8117aa1f536c9b94fd52f1727e81b05b4bf334bd/geth-utils/src/lib.rs#L15
- https://github.com/appliedzkp/zkevm-circuits/blob/8117aa1f536c9b94fd52f1727e81b05b4bf334bd/geth-utils/src/lib.rs#L25

# Propagate errors generated from the go library into rust, instead of printing them to stderr:
- https://github.com/appliedzkp/zkevm-circuits/blob/8117aa1f536c9b94fd52f1727e81b05b4bf334bd/geth-utils/src/lib.rs#L13 Here the Result doesn't contain context about the kind of error.
- https://github.com/appliedzkp/zkevm-circuits/blob/8117aa1f536c9b94fd52f1727e81b05b4bf334bd/geth-utils/lib/lib.go#L23 Here the error is printed, instead of finding a way to return it via FFI.

**Comment by han0110** [comment]
Closed by #292
