### ISSUE TITLE
wrong calcualtion in gas cost for memory expand

### ISSUE THREAD

**Issue by 0x4ka5h** [privacy-scaling-explorations/zkevm-circuits#1679]
### Describe the bug

in eth_types gas_utils.rs [gas_utils.rs] seems like previously [here](https://github.com/scroll-tech/zkevm-circuits/commit/18dfe7c2d44423db7afcee4a397f10d4d4636b48), dev was trying to calculate the gas cost increases as the square of the difference between the next_memory_word_size and the curr_memory_word_size.
`(next_memory_word_size * next_memory_word_size - curr_memory_word_size * curr_memory_word_size) / GasCost::MEMORY_EXPANSION_QUAD_DENOMINATOR.0`
but now, they try to do `(a*a - b*b)/C -> (a*a)/C - (b*b)/C `, in this process the calculation was done incorrectly because of bodmas
```rs
/// Calculate memory expansion gas cost by current and next memory word size.
pub fn memory_expansion_gas_cost(curr_memory_word_size: u64, next_memory_word_size: u64) -> u64 {
    if next_memory_word_size == curr_memory_word_size {
        0
    } else {
        GasCost::MEMORY_EXPANSION_LINEAR_COEFF.0 * (next_memory_word_size - curr_memory_word_size)
            + next_memory_word_size * next_memory_word_size
                / GasCost::MEMORY_EXPANSION_QUAD_DENOMINATOR.0
            - curr_memory_word_size * curr_memory_word_size
                / GasCost::MEMORY_EXPANSION_QUAD_DENOMINATOR.0
    }
}
```

**Comment by 0x4ka5h** [comment]
@leolara

**Comment by 0x4ka5h** [comment]
@lispc

**Comment by ChihChengLiang** [comment]
Hi @0x4ka5h,
I'm not sure if I fully understand the issue. Do you mean the A and B below would disagree in output?

- A: `(a*a - b*b)/C`
- B: `(a*a)/C - (b*b)/C`

The output should be the same because dividing by C is linear.

I might ask too much for this, but I'd appreciate it if you could send a draft PR to point out the correct formula and how its output differs from the incorrect one.

**Comment by 0x4ka5h** [comment]
I mean you should put () before division @ChihChengLiang 

This means, some x*x/y differs from (x*x)/y.

**Comment by ChihChengLiang** [comment]
@0x4ka5h That doesn't make sense to me. The [doc](https://doc.rust-lang.org/reference/expressions.html#expression-precedence) says `* / %` is in the same group, and they follow a left-to-right order of operation, so that `x*x/y` should be the same as `(x*x)/y`.
