### ISSUE TITLE
Upgrade Halo2 version to latest tag

### ISSUE THREAD

**Issue by hero78119** [privacy-scaling-explorations/zkevm-circuits#1691]
### Describe the feature you would like

Need [unblinded advice column features](https://github.com/privacy-scaling-explorations/halo2/pulls?q=is%3Apr+is%3Aclosed) to support proof chunk https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1498
In more detail, we need to compute permutation challenge in bus-mapping witness generation phase, and matching with result derived in aggregation circuit

**Comment by ed255** [comment]
Let's try to use halo2 tag `v0.3.0` with halo2curves `0.6.0`

**Comment by hero78119** [comment]
Hi @han0110 

I think `snark verifier` also need to be upgrade accordingly with new tag, is it?

https://github.com/privacy-scaling-explorations/snark-verifier/blob/c400ffcd629c337111c4e3cbf95acfe1230b068b/snark-verifier/Cargo.toml#L14-L20
