### ISSUE TITLE
Non-deterministic constraint generation in memory.rs

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/zkevm-circuits#1700]
Since `self.banks` is declared as HashMap

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/e246d4dbf30ccf8369fc455422129b59137e219a/zkevm-circuits/src/circuit_tools/memory.rs#L22-L25

and in constraint generation is iterated

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/e246d4dbf30ccf8369fc455422129b59137e219a/zkevm-circuits/src/circuit_tools/memory.rs#L77-L85

thus, since HashMap iteration is not deterministic, constraint generation is not also.

Must be changed with something like `BTreeMap`

**Comment by ed255** [comment]
@zemse is currently working on this
