### ISSUE TITLE
soundness: begin_tx tx_id should be read?

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#1707]
### Describe the bug

here https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/66788d7902e35d93d07580b6d917a0d922e0a173/zkevm-circuits/src/evm_circuit/util/tx.rs#L42 the tx_id is written into CallContext, but this cell is not constrained.   I know in EndTxGadget, tx_id is increased by one.    I think in begin_tx, an evil attacker can still assign an invalid value to BeginTxHelperGadget.tx_id?   The call_context_lookup_write of TxId inside EndTx, and the call_context_lookup_write of TxId inside BeginTx, are **2 different rws**, so the former cannot constrain the latter?  Unless we modify codes and deliberately make them **share same rwc so they can be same identical rw**?

**Comment by hero78119** [comment]
Hi, Just have a quick look, In end_tx.rs

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/66788d7902e35d93d07580b6d917a0d922e0a173/zkevm-circuits/src/evm_circuit/util/tx.rs#L127-L131

it constrain next TxId should be current TxId + 1 with under next state (cb.**next**.state) rw_counter  `cb.next.state.rw_counter`. So end_tx and next begin_tx already share the same *rwc* ?

Besides,  rw_counter should be unique under same tag 
> https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/ef143529304544a18416aa96ba0c6dfa9872a77b/zkevm-circuits/src/state_circuit/lexicographic_ordering.rs#L128-L134

It seems to me there is no soundness issue, cmiiw :)

**Comment by lispc** [comment]
> Hi, Just have a quick look, In end_tx.rs
> 
> https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/66788d7902e35d93d07580b6d917a0d922e0a173/zkevm-circuits/src/evm_circuit/util/tx.rs#L127-L131
> 
> it constrain next TxId should be current TxId + 1 with under next state (cb.**next**.state) rw_counter `cb.next.state.rw_counter`. So end_tx and next begin_tx already share the same _rwc_ ?
> 
> Besides, rw_counter should be unique under same tag
> 
> > https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/ef143529304544a18416aa96ba0c6dfa9872a77b/zkevm-circuits/src/state_circuit/lexicographic_ordering.rs#L128-L134
> 
> It seems to me there is no soundness issue, cmiiw :)

I think line128, the rwc is used as call_id.    Rwc is automatically maintained inside constrain builder. So ithink they don't share same rwc

**Comment by hero78119** [comment]
Hi @lispc This issue was fixed in PR #1719 and merged, please kindly check, thanks!

**Comment by lispc** [comment]
seems good!
