### ISSUE TITLE
Two `Word` types in zkEVM codebase

### ISSUE THREAD

**Issue by zemse** [privacy-scaling-explorations/zkevm-circuits#1736]
### Describe the feature you would like

Currently, there are two `Word` types in the codebase

- [zkevm_circuits::util::word::Word](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/4dc76ebd2c1776abb15ee5bc8064bd13b000f78c/zkevm-circuits/src/util/word.rs#L199) has two limbs.
- [eth_types::lib::Word](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/4dc76ebd2c1776abb15ee5bc8064bd13b000f78c/eth-types/src/lib.rs#L152) which is alias of U256.

It would be great if one of these is renamed.

**Comment by rrtoledo** [comment]
There were some proposals for Circuit's words at an online meeting including:
- ZWord
- CWord
- WordLimbs
- WordCell

**Comment by rrtoledo** [comment]
There are also some types with the same names in bus mapping and zkevm-circuits such as `Block` (defined in bus-mapping/src/circuit_input_builder/block.rs and zkevm-circuits/src/witness/block.rs).
Do you think we should open an issue per homonyms or turn this one here for all?

**Comment by ChihChengLiang** [comment]
@rrtoledo Let's address the renaming of the Blocks in a new issue.

Feel free to choose any name you see fit for Word.
