### ISSUE TITLE
Pre-load fixed constants into lookup tables

### ISSUE THREAD

**Issue by therealyingtong** [privacy-scaling-explorations/zkevm-circuits#2]
In both state and EVM circuits, we have to check that certain inputs are within an allowed range of values. At keygen, these allowed values are loaded as fixed constants into lookup tables. The constants include:

- [ ] opcodes
- [ ] memory addresses
- [ ] storage addresses
- [ ] stack addresses (a 10-bit range, from 0..=1024)
- [ ] global counter (?)
- [ ] program counter (?)
- [ ] TBD: 8-bit lookup tables for encoding and decoding 256-bit words (?)
- [ ] any more?

**Comment by han0110** [comment]
Memory addresses also have a maximum specified here https://github.com/ethereum/go-ethereum/blob/master/core/vm/gas_table.go#L38. The maximum `0x1FFFFFFFE0` is around `2^37`.

**Comment by han0110** [comment]
Close since all of them are taken care in State circuit now
