### ISSUE TITLE
tests: use geth trace to build test inputs of evm circuit

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#204]
Currently the test inputs of evm circuits are constructed manually, which requires a lot of work.

I think it is better to construct circuit test inputs from real geth trace, and I managed to rewrite the test of ADD like this <https://github.com/lispc/zkevm-circuits/blob/feature/refactor-step/zkevm-circuits/src/evm_circuit/execution/add.rs#L132-L163>.

I have two plans:

1. rewrite every opcode test in evm_circuit::execution like above.
2. Add a testdata folder where testcases like add.asm sub.asm xor.asm resides in,  and add a 'test_circuit_for_bytecode` binary like <https://github.com/lispc/zkevm-circuits/blob/feature/refactor-step/zkevm-circuits/src/bin/prover.rs>, so it will be for easy to add more bytecodes for testing in the future.

@barryWhiteHat Which method seems more sense for you or both? Thank you for any comment!

**Comment by ChihChengLiang** [comment]
@lispc What's the status of this issue? I like your two plans. I think eventually we need both unit tests and some larger bytecode tests. 1. seems suitable for the former and 2. for the latter.

**Comment by lispc** [comment]
@ChihChengLiang 

For the first one, I think it is already finished and merged. Most opcodes are already tested with real geth trace now.  

For the second, I am not sure whether it is needed now. There are low level unit tests and WIP high level integration-test ( geth trace from real nodes and real solidity contracts). If you think test like <https://github.com/lispc/zkevm-circuits/blob/feature/refactor-step/zkevm-circuits/src/bin/prover.rs> are helpful to be added into this repo, any further suggestions on the source code structure like where to put these codes ? add a new crate or put it into an existing crate?

**Comment by ChihChengLiang** [comment]
> For the second, I am not sure whether it is needed now. There are low level unit tests and WIP high level integration-test ( geth trace from real nodes and real solidity contracts).

Let's wait the WIP high level integration-test merged then decide whether to add it or where to add it?

**Comment by ed255** [comment]
Regarding point 2, @adria0 has been working on porting the [official ethereum tests](https://github.com/ethereum/tests) to run on our circuits in https://github.com/appliedzkp/zkevm-circuits/pull/382

The official ethereum tests are super extensive, so I think that can cover point 2 without requiring us to manually write the assembly for test cases :)

**Comment by ed255** [comment]
Closing this issue and creating a new one focused on the ethereum tests at https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/658
