### ISSUE TITLE
Improve CircuitInputBuilder for calls and reverts

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#284]
# 1 Number of iterations over geth_steps
https://github.com/appliedzkp/zkevm-circuits/pull/278#discussion_r784733435

Currently we have 3 iterations over geth steps: get access trace, get
is_success for each call, gen_associated_steps.  We could merge the first two
iterations:

1st iteration: 
1. Collect access trace (gen_state_access_trace) to get required (accounts, codes, proofs) by client
2. Collect meta information of a call like is_success

2nd iteration:
1. gen_associated_steps

# 2 call handling
https://github.com/appliedzkp/zkevm-circuits/pull/278#discussion_r784747566
https://github.com/appliedzkp/zkevm-circuits/pull/278#discussion_r785306828

Currently the call handling is done in `handle_tx`.  The proposal is to do the
necessary changes so that the call handling can be done in the
`gen_associated_steps`.  This requires adding new methods to the
`CircuitInputStateRef`, and possibly adding new fields, like the
`call_is_success` HashMap.

Another point is that we should explore moving functionality of the
`gen_associated_steps` for CALL into methods of `CircuitInputBuidlerRef`

# 3 Revert handling
https://github.com/appliedzkp/zkevm-circuits/pull/278#discussion_r785305480
https://github.com/appliedzkp/zkevm-circuits/pull/278#discussion_r784712640

Currently we are generating the reverse operation for each state write
operation in advance, and storing them in `CallContext.operations`, so that if
a revert happens, we can iterate that list.

It would be better if the list of reverse operations was generated automatically.

**Comment by han0110** [comment]
Closed by #292
