### ISSUE TITLE
merge EVM circuit and state circuit

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#322]
After some discussions with Han , we think EVM circuit and state circuit need to be merged together into ONE CIRCUIT to be consistent with each other.  Here is my thoughts on this, and any comments welcome.

1. change the rw lookup table of the current EVM circuit from a RWCounter-sorted fixed-column table to advice-column table using the same sorting as the current state circuit. 
2. constraints of the current state circuit are moved onto the new RW table in EVM circuit.  Only stack/memory/storage rows are affected here.     
3. make sure rw table matches with evm trace. Since rw records created by evm trace are sequential and uniq, we need only make sure the final rw_counter generated by evm trace is equal to the number of rows in rw table? 
4. the current state circuit is no longer useful

Any comments? @han0110  @miha-stopar 
Thank you!

**Comment by barryWhiteHat** [comment]
Just a quick update on this. I am chatting with @lispc about this one. My current TLDR is Lets put the evm proof and state proof side by side and verify them in a single proof. 

This is possibly necessary to make it easier for pass bus mapping elements from state proof to evm proof. 

That said we still have some exploring to do so no urgent change is require. Will update here :)

**Comment by ed255** [comment]
Recently I've been reviewing the current implementation of the state circuit and started working towards bringing it up to date.  I would like to participate in this discussion :)

**Comment by lispc** [comment]
Barry another approach 

"So the way i was thinking to do this, maybe you or Han have a better idea here, was to

1. Give each element a unique tag 
2. Count each element read in evm proof 
3. In the l1 evm do a range proof to prove that the degree of the table == count_of_each_element"    

I am not sure how to implement these from the coding side

**Comment by lispc** [comment]
> Recently I've been reviewing the current implementation of the state circuit and started working towards bringing it up to date. I would like to participate in this discussion :)

Hi Edu, may i know your plan on this？I am considering update some of state_circuit.rs with data types(like Block) in witness.rs.  I am afraid that our updates may conflict/redundant

**Comment by ed255** [comment]
> > Recently I've been reviewing the current implementation of the state circuit and started working towards bringing it up to date. I would like to participate in this discussion :)
> 
> Hi Edu, may i know your plan on this？I am considering update some of state_circuit.rs with data types(like Block) in witness.rs. I am afraid that our updates may conflict/redundant

I identified that the following pieces are missing:
- a. `CallContext`, `Account`, `TxRefund`, `TxAccessListAccountStorage`, `TxAccessListAccount`, `AccountDestructed` "Tags" and their particular constraints.
- b. Columns usage as defined in https://hackmd.io/VCGteyZEQFKUjHA_A72f1Q?view
- c. State circuit constraint documentation (https://github.com/appliedzkp/zkevm-specs/blob/eda6ea91fa8de7eb1955c1f0939d6a6106a4295b/specs/state-proof.md needs updating)

Then I've started working on the following tasks:
- 1. Complete the spec in https://hackmd.io/2j0HOVH8Qzi4peSZCs0d1g (This is serving as rough notes)
- 2. Write the spec in python with description, PR to zkevm-specs
- 3. Update circuit implementation, PR to zkevm-circuit

I'm currently working on point 2

**Comment by ed255** [comment]
I believe the current design that involves the relationship between EVM Circuit and State Circuit is properly defined and is sound, so we could close this issue.
The Summary is that we have
- EVM Circuit with rw operations guaranteed to take unique and sequencial rwc (timestamps) values.  Each unique rw operation is looked up to the RwTable
- State Circuit verifies that rw operations in RwTable are sorted by [keys, rwc] and also verifies read-write consistency.
- We guarantee that the number of unique enabled rw operations in the EVM Circuit matches the number of unique enabled rw operations in the State Circuit (proving that they are permutations of each other) by:
    1. Unused entries in the RwTable use the `Start` tag with a sequential id that starts at 1.
    2. EVM Circuit uses padding to forbid having extra rw entries not related to the trace.
    3. EVM Circuit counts all unique rw entries from the execution trace by counting rwc.
    4. EVM Circuit looks up every rw entry to the RwTable.  This guarantees that RwTable has at least `N` enabled rw entries that match the ones in EVM Circuit.
    5. EVM Circuit looks up the Start tag in the RwTable with the highest id = `M`.  This guarantees that the RwTable has at most `MAX_RWS - M` enabled rw entries.  By proving that `MAX_RWS - M = N` we get that the exact number of enable rw entries in the RwTable is `N`.  So rw entries in EVM Circuit are a permutation of rw entries in RwTable.

This design works independently of whether the circuits are merged in a single proof or in separate proofs (as long as the lookups are verified).  With this I believe we can close this issue as resolved!  If anyone thinks there's anything pending, please comment so that we reopen it :)
