### ISSUE TITLE
Use logging instead of raw printing for prover workspace member reports

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#342]
Currently, we are just printing the info of the CLI bin with `println!`. 

But @ed255 introduced some time ago logging into the workspace. So it would be nice to use it also in the `prover` workspace member.

This can be taken as implementation example: https://github.com/appliedzkp/zkevm-circuits/blob/28b1ea7a6d3e70fa7b20f47fe24b850c7a48d8b3/integration-tests/src/bin/gen_blockchain_data.rs#L87

**Comment by HAOYUatHZ** [comment]
I second that. Because it will be great for logs capture&monitoring&analytics.

**Comment by CPerezz** [comment]
> Hi, @CPerezz @ed255 , I can do this.

Hey!!! That's nice!! Ping in case you need any help!! 😁😁

**Comment by ChengYueJia** [comment]
Seems like there some println! are used in test mod. Does it still need to be replaced? @CPerezz

**Comment by ChengYueJia** [comment]
> Hey!!! That's nice!! Ping in case you need any help!! 😁😁
I've finished. Please have a view if it's fix this issue. @CPerezz

**Comment by ChihChengLiang** [comment]
resolved in #963
