### ISSUE TITLE
Update state circuit according to specs

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#356]
The specs for the state circuit were updated recently and the circuit implementation needs to be updated accordingly.
Update specs PR: https://github.com/appliedzkp/zkevm-specs/pull/118

**Comment by ed255** [comment]
@lispc and @z2trillion are working on this.

**Comment by lispc** [comment]
WIP PR <https://github.com/scroll-tech/zkevm-circuits/pull/111>

**Comment by ed255** [comment]
In https://github.com/appliedzkp/zkevm-circuits/pull/380 there's been an initial update of the state circuit following the new spec.  There are still some TODOs in the state circuit, so I'm leaving this issue open.

**Comment by CPerezz** [comment]
Does this still apply @ed255 ?

**Comment by ed255** [comment]
> Does this still apply @ed255 ?

Yes, this still applies!  The implementation of the state circuit is not yet complete following the spec.  There are some constraints missing for the "General constraints" section: https://github.com/appliedzkp/zkevm-circuits/blob/e806164a84585edc74b06cf7f476725fdb49cb33/zkevm-circuits/src/state_circuit/state.rs#L195

**Comment by ed255** [comment]
Currently the specs and impl match (or mostly match), so I'll close this issue :)
