### ISSUE TITLE
Ci should report the results of the benchmarks in the PR conversations

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#367]
Currently, as you can see with #352 the results of the benchmarks can only be seen if you go to the logs of the CI and search there. 

It would be a way easier to check if a comment was added into the PR discussion directly with all of the results of each circuit PR that was run.

Not sure how difficult/feasible this is. But would be a nice-to-have thing.

cc @AronisAt79

**Comment by HAOYUatHZ** [comment]
seems we can make use of https://github.com/marketplace/actions/publish-unit-test-results

we can grep/sed the desired result, and then use this github-action to post the summary

**Comment by CPerezz** [comment]
Thath's a nice one @HAOYUatHZ . 

I originally suggested to make a bot to do all that stuff. But it's true that would require more work.
I like your proposal! How do you see it @AronisAt79 ?

**Comment by AronisAt79** [comment]
Thanks @HAOYUatHZ , @CPerezz . It looks perfectly doable.Let me have a look!

**Comment by CPerezz** [comment]
If it has to take too much of your time feel free to work on higher prio tasks.

This is just a convenience thing that can be done at any point.

**Comment by ChihChengLiang** [comment]
Close for inactivity
