### ISSUE TITLE
Required opcodes for basic L2 Bridge

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-circuits#369]
###### required environmental opcodes for L2 Bridge
- [x] CALLVALUE https://github.com/appliedzkp/zkevm-circuits/pull/287
- [x] CALLDATASIZE https://github.com/appliedzkp/zkevm-circuits/pull/329
- [x] CALLDATALOAD https://github.com/appliedzkp/zkevm-circuits/pull/346
- [x] CALLDATACOPY https://github.com/appliedzkp/zkevm-circuits/pull/393
- [x] ORIGIN https://github.com/appliedzkp/zkevm-circuits/pull/360
- [x] CALLER https://github.com/appliedzkp/zkevm-circuits/pull/287
- [x] BALANCE https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/683
- [x] CALL https://github.com/appliedzkp/zkevm-circuits/pull/278
- [x] RETURNDATASIZE https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/703
- [x] RETURNDATACOPY https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/779
- [x] LOG1 https://github.com/appliedzkp/zkevm-circuits/pull/335
- [x] ISZERO #372 

#277 

---
A basic native deposit (L1 > L2) test in zkevm-chain given commit `223b38c79bc3c615293bfe2cb7d482cf399500a7`.

###### bus_mapping::evm::opcodes
- [x] `Using dummy gen_associated_ops for opcode LOG1`
- [x] `Using dummy gen_associated_ops for opcode SHA3`
- [x] `Call to account with empty code is left unimplemented`

###### evm_circuit/witness unimplemented opcodes
- [x] SHR
- [x] SHL (https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/578)
- [x] NOT (https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/565)
- [x] SHA3

###### zkevm_circuits::evm_circuit::execution::dummy
- `ExecutionState::SHA3 is implemented with DummyGadget`
---

**Comment by DreamWuGit** [comment]
What does the `L2 Bridge` mean here ?  @pinkiebell

**Comment by barryWhiteHat** [comment]
L2 bridge means the contract on l2 that allows for deposits and withdraws from L1. So these opcodes need to be supported by zkevm.
