### ISSUE TITLE
Required opcodes for advanced l2 bridge contracts

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-circuits#370]
###### Further opcodes for more advanced l2 contracts (compatibility layers, erc-20 factories etc):
- [x] EXTCODEHASH https://github.com/appliedzkp/zkevm-circuits/pull/353
- [x] EXTCODESIZE https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1014
- [ ] CREATE2
- [x] CODECOPY
- [x] SELFBALANCE https://github.com/appliedzkp/zkevm-circuits/pull/328
- [x] CHAINID https://github.com/appliedzkp/zkevm-specs/pull/168
- [x] SLOAD https://github.com/appliedzkp/zkevm-circuits/pull/353 + https://github.com/appliedzkp/zkevm-circuits/pull/334
- [x] SSTORE
- [x] DELEGATECALL #847 
- [x] STATICCALL #801 

#277

**Comment by z2trillion** [comment]
SELFBALANCE is done: https://github.com/appliedzkp/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/selfbalance.rs

**Comment by CPerezz** [comment]
I'm going to take CHAINID :)

**Comment by ChengYueJia** [comment]
@pinkiebell,  I wanna make sure did the create2 haven done.

ps: I've seen `impl<const IS_CREATE2: bool> Opcode for DummyCreate<IS_CREATE2> ` in the create opcode in bus-mapping.

**Comment by pinkiebell** [comment]
@ChengYueJia There seems to be a bus-mapping implementation but it's still named dummy. cc/ @z2trillion @lispc  regarding status on this one. [1](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes.rs#L240) 

On the other hand these opcodes are not handled in the evm circuit yet [2](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution.rs#L1014) - only dummy gadgets.
As far as I know they are up for grabs :)

**Comment by pinkiebell** [comment]
Looks like `EXTCODESIZE` has a wrong reference 😅

**Comment by silathdiir** [comment]
> Looks like `EXTCODESIZE` has a wrong reference 😅

Just started to work on this opcode on this spec issue 😅 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/327

**Comment by ChihChengLiang** [comment]
The remaining CREATE opcode is tracked in #1130
Meta issue can be closed for just 1 item left.
