### ISSUE TITLE
Missing NUMBER implementation after merge

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#410]
After #381 was merged, I realized it does not include the opcode implementation but rather only the test case.

Indeed, the original PR that was reviewed was not like this when was approved. But maybe due to an error in a rebase or something similar it got deleted the impl part.

It would be required to bring it back the implementation and make sure that it passes the tests.

**Comment by ed255** [comment]
Are you referring to the `gen_associated_ops` implementation of the `NUMBER` opcode?  In such case, this is already "implemented" using `StackOnlyOpcode::<0, 1>::gen_associated_ops`, see:
https://github.com/appliedzkp/zkevm-circuits/blob/1ec38f207f150733a90081d3825b4de9c3a0a724/bus-mapping/src/evm/opcodes.rs#L121

**Comment by ed255** [comment]
Oh, what is actually missing is including the file `bus-mapping/src/evm/opcodes/number.rs` to the module tree.  Adding the line:
```rust
mod number;
```
to `bus-mapping/src/evm/opcodes.rs` should fix it.

**Comment by CPerezz** [comment]
That's right!!!! It makes sense. I noticed the module was missing. But thought that the opcode had it's own impl.

Will make a PR to fix it hopefully including the new `mock` infra.
