### ISSUE TITLE
Migrate `util` module gadgets to the gadgets workspace member

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#463]
Some generic gadgets like LTChip being worked on https://github.com/appliedzkp/zkevm-circuits/pull/460 are basically pulling other functions from `zkevm-circuits` such as `from_bytes`. 

This ends up with circular dependencies.

Therefore we should migrate as many non-zkevm-circuits specific gadgets into the new workspace member added in #457

cc: @roynalnaruto

**Comment by roynalnaruto** [comment]
@CPerezz I can work on this refactoring as a part of #460 if that's okay.

For the time being, I don't think this is a blocker for any other ongoing PR. What's your opinion?

**Comment by CPerezz** [comment]
Hi @roynalnaruto .

We added in the `CONTRIBUTING.md` of the repo something about that specifically which is not merging different topics in the same PR and try to make them atomic (For ease of review).

I know this has relation. And if you want, you can take it and make a PR for it. But please, split the work on this from the work on the RLP circuit.

I'm happy to work on this or to leave it to you. Whatever you prefer :)

**Comment by roynalnaruto** [comment]
I can take this up and create a separate PR. Will wrap it up by beginning of the coming week 👍
