### ISSUE TITLE
pad circuit to make selector offset fixed

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#474]
selector(q_step / q_first_step / q_last_step)  offset should be fixed so vk can be reused.

So we should implement some padding mechanism to make q_last_step not related to `witness::Block`. 

I made a drat PR <https://github.com/scroll-tech/zkevm-circuits/pull/142>, so vk generated by empty circuit can be used to verify circuit constructed from real trace.  This implementation may needs much polish later.  Just put the issue first.

**Comment by lispc** [comment]
The reasons using selector rather than advice are (1) avoid access the last several unavailable rows (2) some performance optimization.    


In production,  selectors should be have fixed values not related to specific  circuit witness.  I am considering this "two selector design pattern":   

We have a real "selector" named "q_available". It is fixed and usually long(eg: from row 0 to row 2**k-64). 

The other is "advice selector", it is an advice column but used like "q_usable" in evm circuit. (We note it as "q_used" now). It is different for each circuit. q_used can be true only when q_available is true.  

By this design, we add a column but make least intrusive changes to circuit logic.

**Comment by ed255** [comment]
@lispc we're wondering if you have worked on this in the scroll-tech fork?  If not, would you be interested in working on a fix to this issue?

**Comment by lispc** [comment]
@ed255 
i fixed it for evm circuit in scroll fork. I added another column and degree. 

q_usable(selector, but not fixed in fact..) becomes q_usable(fixed column, fixed len) and q_used(advice column, not fixed len)

(i think this method is sub optimal for performance.. Would you like this simple but not efficient solution as a PR, or we'd better design a new/more complex/more efficient mechanism like padding-dummy execution state or multi EndBlock execution state..?) 

details:
https://github.com/scroll-tech/zkevm-circuits/blob/4a1c4cfd09f0814498e5a799e60164b5965b5ef5/zkevm-circuits/src/evm_circuit/execution.rs#L148

**Comment by barryWhiteHat** [comment]
@lispc are yall planning to submit a PR for this ?

**Comment by lispc** [comment]
no problem! So you think my solution(add another column and degree) is ok?

**Comment by han0110** [comment]
In the short term I think we can increase `1` degree (leads `extended_k = 3` but seems fine [^if-with-optional-zk]) to halve the `ExecutionState` (with a bit prefixed with ~50 cells instead of ~100 cells) to make `EndBlock` single row as padding. Then we can assign `q_usable` all the way down to the static height to create static pk/vk. Then we can also keep `q_step_last` fixed position without requiring `q_used`. How does this approach sound?

[^if-with-optional-zk]: Ideally with optional zk we can remove the extra degree and get back `extended_k = 2`.

**Comment by lispc** [comment]
@han0110  ok i will move my codes (add 1 degree, add 1 col , to make vk/pk fixed) as a PR here soon

**Comment by han0110** [comment]
Thanks a lot!

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/728

NOTE that in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/795 I also made some updates regarding evm circuit padding, but this issue will remain resolved.
