### ISSUE TITLE
Meta: Opcode spec + implementation status

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#477]
| opcode         | spec | circuit | bus-mapping | ExecutionState | Notes                                                                          |
| ------         | ---- | ------- | ----------- | -------------- | -----                                                                          |
| STOP           | x    | x       | x           | STOP           |                                                                                |
| ADD            | x    | x       | x           | ADD_SUB        |                                                                                |
| MUL            | x    | x       | x           | MUL_DIV_MOD    | MulDivModGadget                                                                |
| SUB            | x    | x       | x           | ADD_SUB        |                                                                                |
| DIV            | x    | x       | x           | MUL_DIV_MOD    | MulDivModGadget                                                                |
| SDIV           | x    | x       | x           | SDIV           |                                                                                |
| MOD            | x    | x       | x           | MUL_DIV_MOD    | MulDivModGadget                                                                |
| SMOD           | x    | x       | x           | SMOD           |                                                                                |
| ADDMOD         | x    | x       | x           | ADDMOD         |                                                                                |
| MULMOD         | x    | x       | x           | MULMOD         |                                                                                |
| EXP            | x    | x       | x           | EXP            |                                                                                |
| SIGNEXTEND     | x | x       | x           | SIGNEXTEND     |                                                                                |
| LT             | x | x       | x           | CMP            |                                                                                |
| GT             | x | x       | x           | CMP            |                                                                                |
| SLT            | x    | x       | x           | SCMP           |                                                                                |
| SGT            | x    | x       | x           | SCMP           |                                                                                |
| EQ             | x | x       | x           | CMP            |                                                                                |
| ISZERO         | x    | x       | x           | ISZERO         |                                                                                |
| AND            | x | x       | x           | BITWISE        |                                                                                |
| OR             | x | x       | x           | BITWISE        |                                                                                |
| XOR            | x | x       | x           | BITWISE        |                                                                                |
| NOT            | x    | x       | x           | NOT            |                                                                                |
| BYTE           | x | x       | x           | BYTE           |                                                                                |
| CALLDATALOAD   | x    | x       | x           | CALLDATALOAD   |                                                                                |
| CALLDATASIZE   | x    | x       | x           | CALLDATASIZE   |                                                                                |
| CALLDATACOPY   | x    | x       | x           | CALLDATACOPY   |                                                                                |
| CODESIZE       | x    | x       | x           | CODESIZE       |                                                                                |
| CODECOPY       | x    | x       | x           | CODECOPY       |                                                                                |
| SHL            | x    | x       | x           | SHL            |                                                                                |
| SHR            | x    | x       | x           | SHR            |                                                                                |
| SAR            |  x    |   x   | x           | SAR            |  https://github.com/privacy-scaling-explorations/zkevm-specs/pull/263 #727 #1036 |
| POP            | x | x       | x           | POP            |                                                                                |
| MLOAD          | x | x       | x           | MEMORY         |                                                                                |
| MSTORE         | x | x       | x           | MEMORY         |                                                                                |
| MSTORE8        | x | x       | x           | MEMORY         |                                                                                |
| JUMP           | x    | x       | x           | JUMP           |                                                                                |
| JUMPI          | x    | x       | x           | JUMPI          |                                                                                |
| PC             | x    | x       | x           | PC             |                                                                                |
| MSIZE          | x | x       | x           | MSIZE          |                                                                                |
| JUMPDEST       | x    | x       | x           | JUMPDEST       |                                                                                |
| PUSH_N         | x    | x       | x           | PUSH           |                                                                                |
| DUP_N          | x    | x       | x           | DUP            |                                                                                |
| SWAP_N         | x    | x       | x           | SWAP           |                                                                                |
| RETURN         | x    | x       | x           | RETURN         |                                                                                |
| REVERT         |  x   | x       | x           | REVERT         |     https://github.com/privacy-scaling-explorations/zkevm-specs/pull/317          |
| SHA3           | x    | x       | x           | SHA3           |                                                                                |
| ADDRESS        | x    | x       | x           | ADDRESS        |                                                                                |
| BALANCE        | x    |  x     |   x        | BALANCE        | #683                                                                       |
| ORIGIN         | x    | x       | x           | ORIGIN         |                                                                                |
| CALLER         | x    | x       | x           | CALLER         |                                                                                |
| CALLVALUE      | x    | x       | x           | CALLVALUE      |                                                                                |
| GASPRICE       | x    | x       | x           | GASPRICE       |                                                                                |
| EXTCODESIZE    |  x  |    x    |     x      | EXTCODESIZE    |   #993                                      |
| EXTCODECOPY    | x    |   x    |   x        | EXTCODECOPY    | #720                                                                       |
| EXTCODEHASH    | x    | x       | x           | EXTCODEHASH    |                                                                                |
| RETURNDATASIZE | x    | x       | x           | RETURNDATASIZE |                                                                                |
| RETURNDATACOPY | x    |  x    |     x     | RETURNDATACOPY | #779                                                                       |
| BLOCKHASH      | x    | x       | x           | BLOCKHASH      |                                                                                |
| COINBASE       | x    | x       | x           | BLOCKCTXU160   | BlockCtxGadget                                                                 |
| TIMESTAMP      | x    | x       | x           | BLOCKCTXU64    | BlockCtxGadget                                                                 |
| NUMBER         | x    | x       | x           | BLOCKCTXU64    | BlockCtxGadget                                                                 |
| DIFFICULTY     | x    | x       | x           | BLOCKCTXU256   | BlockCtxGadget                                                                 |
| GASLIMIT       | x    | x       | x           | BLOCKCTXU64    | BlockCtxGadget                                                                 |
| CHAINID        | x    | x       | x           | CHAINID        |                                                                                |
| SELFBALANCE    | x    | x       | x           | SELFBALANCE    |                                                                                |
| BASEFEE        | x    | x       | x           | BLOCKCTXU256   | BlockCtxGadget                                                                 |
| SLOAD          | x    | x       | x           | SLOAD          |                                                                                |
| SSTORE         | x    | x       | x           | SSTORE         |                                                                                |
| GAS            | x    | x       | x           | GAS            |                                                                                |
| LOG_N          | x    | x       | x           | LOG            |                                                                                |
| CREATE         |  x  |  x     |  x         | CREATE         |  https://github.com/privacy-scaling-explorations/zkevm-specs/issues/371 #1356 #1357 #1358                                                                 |
| CREATE2        |  x   |  x     |  x         | CREATE2        |  https://github.com/privacy-scaling-explorations/zkevm-specs/issues/371    #1356 #1357 #1358                                 |
| CALL           | x    | x       | x           | CALL           |    #278                                         |
| CALLCODE       | x    |  x    |    x       | CALLCODE       |     #932                                                      |
| DELEGATECALL   | x    |   x    |    x     | DELEGATECALL   | #847                                                                       |
| STATICCALL     | x    | x       | x           | STATICCALL     |   #801                                                   |
| SELFDESTRUCT   |      |         |             | SELFDESTRUCT   |    (no intent to implement this)                       |

# Error states

There are constant gas cases and dynamic gas cases. See #1305

| spec | circuit | bus-mapping | ExecutionState                      | Notes                                                                                                                                             |
| ---- | ------- | ----------- | ----------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| x    | x       | x           | ErrorInvalidOpcode                  | #1138                                                                                                                                             |
| x    | x       | x           | ErrorStackOverflow                  | https://github.com/privacy-scaling-explorations/zkevm-specs/pull/301 #873                                                                         |
| x    | x       | x           | ErrorStackUnderflow                 | https://github.com/privacy-scaling-explorations/zkevm-specs/pull/301 #873                                                                         |
|   x   | x       | x           | ErrorWriteProtection                | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/441, https://github.com/privacy-scaling-explorations/zkevm-specs/pull/365 #1001                                                                        |
|  x   |  x    |    x     | ErrorDepth                          | #1312 (CALL) #1430 (CREATE)                                                                                                                                            |
|  x   |    x  |     x    | ErrorInsufficientBalance            |   CALL: https://github.com/privacy-scaling-explorations/zkevm-specs/issues/442 #998 CREATE: https://github.com/privacy-scaling-explorations/zkevm-specs/issues/416 #1425 #1430                                                                                                                                              |
| x  |    x   |     x     | ErrorContractAddressCollision       | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/443 https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1309                                                                        |
| x   |   x   |   x  | ErrorInvalidCreationCode            | https://github.com/privacy-scaling-explorations/zkevm-specs/pull/400 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/434 #1291                                                                                                                                             |
|  x  |   x  |    x    | ErrorMaxCodeSizeExceeded            | https://github.com/privacy-scaling-explorations/zkevm-specs/pull/393 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/445 #1259                                                                                                                                             |
| x    | x       | x           | ErrorInvalidJump                    | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/297 #841                                                                       |
| x   | x       | x           | ErrorReturnDataOutOfBound           | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/446  #1017                                                                    |
| x    | x       | x           | ErrorOutOfGasConstant               | https://github.com/privacy-scaling-explorations/zkevm-specs/pull/266                                                                              |
|  x  | x       |   x     | ErrorOutOfGasStaticMemoryExpansion  | #312 #398 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/455 #1518                                                                                                                                           |
|  x   |  x     |   x      | ErrorOutOfGasDynamicMemoryExpansion |  #398 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/456 #1519                                                                                                                                                |
| x  | x       | x         | ErrorOutOfGasMemoryCopy             | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/414 https://github.com/privacy-scaling-explorations/zkevm-specs/pull/397 #1288                                                                        |
|  x  |   x    |  x      | ErrorOutOfGasAccountAccess          | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/447 #1349                                                                                                                                             |
| x  |   x   |    x     | ErrorOutOfGasCodeStore              | https://github.com/privacy-scaling-explorations/zkevm-specs/pull/393 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/445 #1259                                                                                                                                             |
| x  | x       | x        | ErrorOutOfGasLOG                    | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/448  #1134                                                                                                                                             |
| x   | x       | x      | ErrorOutOfGasEXP                    | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/449 #1231                                                                                                                                             |
| x   |  x     |   x      | ErrorOutOfGasSHA3                   | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/450 #1520                                                                                                                                                  |
|  x  |  x    |   x      | ErrorOutOfGasEXTCODECOPY            | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/451 #1521                                                                                                                                                  |
| x    | x       | x       | ErrorOutOfGasSLOAD                  | https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1119 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/382 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/452 |
|   x   | x       | x       | ErrorOutOfGasSSTORE                 | https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1119 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/382 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/453 |
| x    | x       | x      | ErrorOutOfGasCALL                   | https://github.com/privacy-scaling-explorations/zkevm-specs/pull/287 #827                                                                         |
| x   |    x   | x       | ErrorOutOfGasCALLCODE               | #1127   https://github.com/privacy-scaling-explorations/zkevm-specs/pull/368                                                                                                                                               |
| x   | x      | x        | ErrorOutOfGasDELEGATECALL           | #1127 https://github.com/privacy-scaling-explorations/zkevm-specs/pull/368                                                                                                                                                 |
| x   | x      |  x      | ErrorOutOfGasSTATICCALL             |     #1127  https://github.com/privacy-scaling-explorations/zkevm-specs/pull/368                                                                                                                                            |
|  x  |   x    |  x      | ErrorOutOfGasCREATE2                | https://github.com/privacy-scaling-explorations/zkevm-specs/issues/454 #1522                                                                                                                                                  |
| x  |  -   |     -     | ErrorGasUintOverflow           |  https://github.com/privacy-scaling-explorations/zkevm-specs/pull/436 https://github.com/privacy-scaling-explorations/zkevm-specs/issues/421  #1526 #1564                                                                      |
|      |         |             | ErrorOutOfGasSELFDESTRUCT           |                                                                                                                                                   |

- we decided not to implement `ErrorGasUintOverflow` in `invalid tx` case. See discussion in #1526

**Comment by ed255** [comment]
In https://github.com/appliedzkp/zkevm-circuits/issues/83 we kept track of opcode implementations in the bus-mapping, but I often missed quickly knowing the status of the opcode specs and circuit implementation.  I've extended the list from #83 into a table to include the spec and circuit status.

With this issue, https://github.com/appliedzkp/zkevm-circuits/issues/83 becomes redundant.  @CPerezz do you think we can close the old issue?  Or alternative rename the old issue and update it with this table (I didn't do that because I didn't want to confuse anyone)

**Comment by CPerezz** [comment]
Ye! Makes sense to me! 
Thanks for putting some effort on improve the traceability of this!

**Comment by roynalnaruto** [comment]
`CODESIZE` is in progress:
- [ ] Specs: https://github.com/appliedzkp/zkevm-specs/pull/191
- [ ] Circuit and Bus Mapping: https://github.com/appliedzkp/zkevm-circuits/pull/483

**Comment by icemelon** [comment]
We currently have `SHL`, `SHR`, `SDIV` WIP.

**Comment by ChihChengLiang** [comment]
I did an update on the status of completion on 2023-04-28. Great work for all the progress :)

**Comment by KimiWu123** [comment]
Updated `Error states` table and created corresponding issues for un-implemented error states on July 6, 2023.

**Comment by KimiWu123** [comment]
Updated the status of completion on Aug 9, 2023. 

All the specs were done, except `ErrorOutOfGasCREATE2` is still under review. Still have 7 circuits not finished.

**Comment by KimiWu123** [comment]
Updated on Sep. 19, 2023
All the error states were done except one minor case (GasUintOverflow in invalid txs)!

**Comment by lispc** [comment]
oh btw i can upstream better bus-mapping handling of self-destruct.   It helps build correct statedb.  Soon.  

https://github.com/scroll-tech/zkevm-circuits/blob/2723b82fb5d538d6fcc7b2dd0d84d3df8818499f/bus-mapping/src/evm/opcodes.rs#L499. it is battle tested with mainnet.

**Comment by ChihChengLiang** [comment]
@lispc https://github.com/scroll-tech/zkevm-circuits/blob/2723b82fb5d538d6fcc7b2dd0d84d3df8818499f/bus-mapping/src/evm/opcodes.rs#L499 Looks fantastic! It would be great to upstream it.

**Comment by KimiWu123** [comment]
Updated on Dec. 18, 2023.
After we decided not to implement `ErrorGasUintOverflow` in `invalid tx` case, then all error states and opcodes listed were addressed!!
