### ISSUE TITLE
buss mapping chore: Try wrap read/write ops

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#498]
currently in buss mapping op codes, it is often used `state.push_op(xxx)`, which is not very much meaningful & readable,
Here try to wrap read/write ops with specific op naming, like `call_context_read` `memory_read` `stack_write` etc. Glad to know if you like it !

PR #497 is an example !

**Comment by DreamWuGit** [comment]
Will update all remaining types of operations in incoming PR besides https://github.com/appliedzkp/zkevm-circuits/pull/497

**Comment by CPerezz** [comment]
Is there any further places where this needs to be fixed @DreamWuGit ? 

Will you take care of it?

**Comment by DreamWuGit** [comment]
@CPerezz  yeah, will do it soon for the remaining
