### ISSUE TITLE
backlog: remove `fix_geth_trace_memory_size` 

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#509]
After https://github.com/ethereum/go-ethereum/pull/24867 is merged & released.

**Comment by ed255** [comment]
https://github.com/ethereum/go-ethereum/pull/24867 has now been merged!

**Comment by lispc** [comment]
yes after [v1.10.18](https://github.com/ethereum/go-ethereum/milestone/130) is released, we can upgrade **both the in-process CGO tracer and integration test geth image**.

There are two updates in v1.10.18  related to our repo:

(1) refund added to structlog
(2) the  `fix_geth_trace_memory_size`

**Comment by ed255** [comment]
Resolved in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/540
