### ISSUE TITLE
Address tech-debt left in CIB(Circuit Input Builder) refactor/split

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#513]
In https://github.com/appliedzkp/zkevm-circuits/pull/482 I left some tech-debt to address in the future. As it would make the PR at that time even more difficult to review. 

Therefore, it's time to address all the things left.

- CIB Tx struct only used in tests now. Should we migrate away?
- Make all fn's in error.rs members of self (ie. attribute fns).
- Better handling of unwrapping in regular functions.
- Error out instead of panicking in circuit opcodes impl.

This is a tiny list of some things that got my attention. I think there's quite some more.

**Comment by ChihChengLiang** [comment]
> CIB Tx struct only used in tests now. Should we migrate away?
Struct simplification is continued in #1391

> Make all fn's in error.rs members of self (ie. attribute fns).
Tracked in #1181 

For the rest, we seems to live happily with them, and we can close due to inaction
