### ISSUE TITLE
Be aware that `U256::as_xxxx()` panicks

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/zkevm-circuits#517]
When running some ethereum tests (e.g. [bufferFiller](https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stMemoryTest/bufferFiller.yml)), code panics due the usage of [U256::as_xxx](https://docs.rs/primitive-types/latest/primitive_types/struct.U256.html#method.as_usize)

This used, e.g. in https://github.com/appliedzkp/zkevm-circuits/blob/2693c32513a4a668ce33630f69a9896e849f3c3d/bus-mapping/src/evm/opcodes/calldatacopy.rs#L153

We need to REVERT instead panicking.

**Comment by CPerezz** [comment]
Oh wow!! I did not see that one coming! 

Thats a cool error! Thanks for finding it out! 

Should we impl `as_xxxx` to return a `Result` or similar? So that we can trigger the reversion from the error unwrapping? Or instead we should check first if the number fits??

I'd go for the first option TBH. But I'm also afraid that it will cause the entire code to be full of error handling. Which in any case is better IMO. As we can `?` in most of the places.

**Comment by adria0** [comment]
We can also types, for instance we already have: `Gas` at

https://github.com/appliedzkp/zkevm-circuits/blob/2693c32513a4a668ce33630f69a9896e849f3c3d/eth-types/src/evm_types.rs#L57 and implement `TryFrom<Word>`

In the case of memory, we have already have also:  https://github.com/appliedzkp/zkevm-circuits/blob/2693c32513a4a668ce33630f69a9896e849f3c3d/eth-types/src/evm_types/memory.rs#L72 

I think that I would love to see also a `MemorySize` here, but I do not see it implemented.

WDYT?

**Comment by adria0** [comment]
SGTM 👍

**Comment by adria0** [comment]
@CPerezz  Seems a good first issue, isn't it?

**Comment by CPerezz** [comment]
Not sure about the good first issue as this also requires to implement the correct reversion. And that isn't that easy. WDYT @adria0 ?

**Comment by adria0** [comment]
Oh, not talking about implementing reversion, just to change `u64`/`usize` for a more the specific types `Gas`/`MemorySize`/etc...

**Comment by ChihChengLiang** [comment]
I believe we've addressed part of the memory panics in PRs like #1158 and 
Similar issues like #1276 and #1301 also track and resolve the same problem.

Close this one due to inactivity. Feel free to reopen if you feel there's a need for that.
