### ISSUE TITLE
Possible errors

### ISSUE THREAD

**Issue by web3moon** [privacy-scaling-explorations/zkevm-circuits#533]
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/e8cbcff2054b104b42ae7a5baa4e02baff6e9955/zkevm-circuits/src/evm_circuit/util.rs#L208

Why is the initial capacity of the Vec not set to width, but to height?

**Comment by Brechtpd** [comment]
Ah yes, should be `width` indeed, thanks for catching this. Feel free to fix in a PR. :)

**Comment by leolara** [comment]
please assign to me, I don't have the rights to assign it to me
