### ISSUE TITLE
[Action Required] Agreement to relicense zkevm-circuit codebase

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#554]
Dear contributors,

Thank you for your past contributions to the zkevm-circuit codebase.

We post this issue to request your approval for the relicensing of the zkevm-circuit codebase. To express your consent, please respond to this issue with "I agree."

We originally released the codebase under BOSL, and we plan to relicense it to MIT + Apache2.0 dual licenses, with which open-source developers are more familiar than the former. The relicensing can speed up developers' adoption, reuse, and contribution to the codebase.

Please see the license agreement in the [link](https://docs.google.com/document/d/1EmqipCWlpZZSc9xo4IfDB87egbrhwfZRjls8KYYnRFM/edit#). 

- [x] @3for
- [x] @AronisAt79
- [x] @Brechtpd
- [x] @CPerezz
- [x] @ChihChengLiang
- [ ] @DavidCai1111
- [x] @DreamWuGit
- [x] @HAOYUatHZ
- [x] @Lawliet-Chan
- [x] @NoCtrlZ
- [x] @adria0
- [x] @barryWhiteHat
- [x] @bchyl
- [x] @ed255
- [x] @han0110
- [x] @icemelon
- [x] @kilic
- [x] @lispc
- [x] @miha-stopar
- [x] @ntampakas
- [x] @pinkiebell
- [x] @ripwu
- [x] @roynalnaruto
- [x] @scroll-dev
- [x] @silathdiir
- [x] @spartucus
- [x] @therealyingtong
- [x] @z2trillion

**Comment by CPerezz** [comment]
I agree.

**Comment by ChihChengLiang** [comment]
I agree with the relicensing of the zkevm-circuit codebase from BOSL to MIT + Apache2.0.

**Comment by han0110** [comment]
I agree with the relicensing of the zkevm-circuit codebase from BOSL to MIT + Apache2.0.

**Comment by HAOYUatHZ** [comment]
I agree with the relicensing of the zkevm-circuit codebase from BOSL to MIT + Apache2.0.

**Comment by 3for** [comment]
I agree.

HAOYUatHZ ***@***.***> 于2022年6月4日周六 16:54写道：

**Comment by Lawliet-Chan** [comment]
I agree

**Comment by NoCtrlZ** [comment]
I agree

**Comment by silathdiir** [comment]
I agree with the relicensing of the zkevm-circuit codebase from BOSL to MIT + Apache2.0.

**Comment by z2trillion** [comment]
I agree.

**Comment by ed255** [comment]
I agree.

**Comment by spartucus** [comment]
I agree.

**Comment by lispc** [comment]
I agree

**Comment by icemelon** [comment]
I agree

**Comment by ntampakas** [comment]
I agree.

**Comment by pinkiebell** [comment]
I agree.

**Comment by Brechtpd** [comment]
I agree.

**Comment by scroll-dev** [comment]
I agree.

**Comment by roynalnaruto** [comment]
I agree

**Comment by DreamWuGit** [comment]
I agree
















在 2022-06-06 14:38:47，"Rohit Narurkar" ***@***.***> 写道：

I agree

**Comment by AronisAt79** [comment]
I agree

**Comment by miha-stopar** [comment]
I agree.

**Comment by bchyl** [comment]
I agree.

**Comment by therealyingtong** [comment]
I agree.

**Comment by barryWhiteHat** [comment]
I agree with the relicensing of the zkevm-circuit codebase from BOSL to MIT + Apache2.0.

**Comment by kilic** [comment]
I agree

**Comment by ripwu** [comment]
I agree.

**Comment by ChihChengLiang** [comment]
Hi @DavidCai1111, we're still waiting for your reply and keep reaching out to you. Within 7 days, we will assume you agree and proceed with the license change.
