### ISSUE TITLE
`RETURN` opcode

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#573]
Implement the RETURN execution state for the RETURN opcode.

This opcode uses dynamic length memory copy so it may depend on the Copy Circuit.

Depends on spec: https://github.com/privacy-scaling-explorations/zkevm-specs/pull/229

**Comment by Brechtpd** [comment]
Hey @z2trillion, are you working on this? `RETURNDATASIZE` has a small dependency on `RETURN`, we were wondering if it would make sense for us to implement `RETURN` as well (busmapping + maybe circuit).

**Comment by z2trillion** [comment]
I am. I have WIP PR which handles the memory copy parts of RETURN, but not the contract creation parts: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/719
