### ISSUE TITLE
Run  cargo test without --release  flag failed

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#582]
I often use  "rust-analyzer" plugin via VSCode to run test ,  and found the previously  cmd working well failed with latest main branch.  
i.e.   
![image](https://user-images.githubusercontent.com/16850793/174619162-6970ebfd-0794-4061-8591-3b450636ef0c.png)

the cmd can be :` cargo test --package zkevm-circuits --lib -- evm_circuit::execution::is_zero::test::is_zero_gadget --exact --nocapture`  

but the cargo test with --release can pass,  i.e. `cargo test --release  --package zkevm-circuits --lib -- evm_circuit::execution::is_zero::test::is_zero_gadget --exact --nocapture`   

not sure the root cause for now  !!

**Comment by HAOYUatHZ** [comment]
configuring the opt-level should fix this problem

in Cargo.toml
```
[profile.test]
opt-level = 3

[profile.release]
opt-level = 3
```

**Comment by ChihChengLiang** [comment]
@CPerezz any updates on this one?

**Comment by CPerezz** [comment]
>btw, takes a lot! 141s !
Yes, basically some of these tests require now to have one more row avaliable in the EVM circuit which therefore extends the proving time.

Closing this then. @DreamWuGit feel free to reopen in case you still find some errors.

**Comment by DreamWuGit** [comment]
Won't happen for me now , thanks @CPerezz !!
