### ISSUE TITLE
Add lookups to EVM circuit to constrain number of padding and active rows

### ISSUE THREAD

**Issue by z2trillion** [privacy-scaling-explorations/zkevm-circuits#587]
Once  #322 is done, we need to do add two lookups to the EVM circuit to prove that there exactly `n` active rows and `N_ROWS-n` padding rows in the rw table:
1. lookup(Start, rwc=1)
2. lookup(Start, rwc=N_ROWS-n)

See https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/558#issuecomment-1160765938 for context.

**Comment by ed255** [comment]
This should be resolved once EndBlock state is completed.  Spec PR: https://github.com/privacy-scaling-explorations/zkevm-specs/pull/243
