### ISSUE TITLE
Read-write inconsistency in CallDataLoad and CallDataCopy

### ISSUE THREAD

**Issue by z2trillion** [privacy-scaling-explorations/zkevm-circuits#602]
My understanding of read-write consistency is that non-first access reads should not change row.value, but the following tests fail when I make the changes in this PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/601:

---- evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_multi_step stdout ----
thread 'evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_multi_step' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_simple stdout ----
thread 'evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_simple' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29

---- evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_out_of_bound stdout ----
thread 'evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_out_of_bound' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29

---- evm_circuit::execution::calldataload::test::calldataload_gadget_internal stdout ----
thread 'evm_circuit::execution::calldataload::test::calldataload_gadget_internal' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29

---- evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_zero_length stdout ----
thread 'evm_circuit::execution::calldatacopy::test::calldatacopy_gadget_zero_length' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000000000000000000000000000000cafe111`,
 right: `0x000000000000000000000000000000000000000000000000000000000cafe333`: [CallContext { rw_counter: 11, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853555 }, CallContext { rw_counter: 69, is_write: false, call_id: 1, field_tag: CallerAddress, value: 212853009 }]', zkevm-circuits/src/state_circuit.rs:238:29

@ed255  and @han0110, is something wrong with my understanding of what rw consistency is, or is there a bug in the bus mapping for the calldata gadgets?

**Comment by han0110** [comment]
It's a bug in `CALL` implementation, I will fix this soon. PR #601 looks good, sorry for confusing.

**Comment by z2trillion** [comment]
thanks for the quick reply!

I've also noticed that the initial values for some Rw::CallContext rows are not 0. E.g. in begin_tx, CallerAddress is read from the rw_table and not written: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/begin_tx.rs#L64. Should those instead be writes?

**Comment by lispc** [comment]
btw i'd like to share some tips debugging rw lookup here

(1) I fetched the values from stored_expression and then compared them with rw in step witness. https://github.com/scroll-tech/zkevm-circuits/blob/158ae144f6a72f993c07be090dc98a0133a1d6ec/zkevm-circuits/src/evm_circuit/execution.rs#L1015

(2) i use 0x1000 as rand value for RLC so only looking at the hex RLCed value i can know which field is inconsistent.. https://github.com/scroll-tech/zkevm-circuits/pull/169/files#diff-6a80b984a7756f4e24712f75e42b12ea3be5af4111bdbcfcc08d1b18d33d22acR75

**Comment by han0110** [comment]
> I've also noticed that the initial values for some Rw::CallContext rows are not 0. E.g. in begin_tx, CallerAddress is read from the rw_table and not written: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/begin_tx.rs#L64. Should those instead be writes?

For immutable part of `CallContext`, there will never be write to them, then we can read it from air. In `BeginTx` it will make sure most fields make sense (copied from `TxContext` or initialized properly), except that `IsSuccess`, `IsPersistent` and `RwCounterEndOfReversion` will be checked in the end of a call, still read but **might not be the first read**, and this is the reason I chose to always use read for all immutable part of `CallContext`.

So ideally they the initial row of `CallContext` don't need any constraint (not like initial read of memory should be `0`). Does this add extra complexity to State circuit?

**Comment by z2trillion** [comment]
for consistency, i'd prefer that every rw row have a defined initial value, but it won't cause implementation problems if that's not the case for rw::callcontext rows.

so the reason the state circuit  doesn't need to constrain the initial values for rw::callcontext rows is that the begintx gadget ensures that the initial values match the values in the tx table?

**Comment by han0110** [comment]
> so the reason the state circuit doesn't need to constrain the initial values for rw::callcontext rows is that the begintx gadget ensures that the initial values match the values in the tx table?

Exactly, and technically these fields don't have a fixed initial values, they are context decided by their creator (tx or call family opcodes).
