### ISSUE TITLE
Implement CopyCircuit

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#608]
The CopyCircuit may benefit from new functionality (yet to be specified and developed) added to the CircuitInputBuilder that helps generate the CopyCircuit witness from the execution trace.

**Comment by ed255** [comment]
> Hi @ed255 the copy circuit PR is almost ready (some refactoring required) #584

Thanks!

> Can you provide me a link to the witness generation part that you have mentioned above?

Oh sorry I think I wasn't clear; I'm not referring about something that already exist; but something new that may be developed inside the Circuit Input Builder.

**Comment by roynalnaruto** [comment]
@ed255 can we close this?
