### ISSUE TITLE
Integrate `EvmCircuit` with crate `bus-mapping`

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-circuits#61]
Currently `EvmCircuit` uses lots of self-defined struct that should be provided by crate `bus-mapping` like:

- `Case`
- `CoreStateInstance`
- `ExecutionStep`
- `Operation`

We should remove this when `bus-mapping` is ready for

- Providing `call_id`, `stack_pointer`, `gas_counter`, `case` in `ExecutionStep`
- Providing `Vec<Operation>` from `ExecutionTrace`

**Comment by CPerezz** [comment]
@han0110 can we consider this closed already? I think so no?

**Comment by han0110** [comment]
Yes, I think so. Sorry that I just noticed this now...
