### ISSUE TITLE
begin_tx test with 'RETURN' will cause error case (stack underflow )

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#612]
for code line https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/ca56d448634d89f5e3aeced804d040a1c74bc37c/zkevm-circuits/src/evm_circuit/execution/begin_tx.rs#L382  
current `RETURN`  somewhat dummy op code handles it and let the test pass, it is not a problem. 
From my side , current unit tests are always positive test for evm circuit, so not sure if it is by design .  open this issue to classify .

@han0110  could you have a look ?

**Comment by han0110** [comment]
I think it should have 2 `PUSH` before `RETURN` or using `STOP` instead, seems to be be a mistake.

**Comment by DreamWuGit** [comment]
@han0110  yeah, I change to STOP resulting in success . will fix it then.

**Comment by ChihChengLiang** [comment]
fixed in #613
