### ISSUE TITLE
get_step_err for successful call gets "call failure without return"

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#629]
add a new test `tracer_call_success` which results in error message as title describes, test in  https://github.com/scroll-tech/zkevm-circuits/pull/175/files

the root cause is next step stack is empty , which is considered as failed result .

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/630
