### ISSUE TITLE
`LOG` reverts on memory limits

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/zkevm-circuits#632]
check

```
# 7faabbffffffffffffffffffffffffffffffffffffffffffffffffffffffffccdd60005260006001a000
PUSH32(77225351507333622277426767162471482489787666164639553421579163846097825156317)
PUSH1(0)
MSTORE
PUSH1(0)
PUSH1(1)
LOG0
STOP
```

```
# 60006000a000
PUSH1(0)
PUSH1(0)
LOG0
STOP
```
panics with 
`Execution result is : Err([ConstraintNotSatisfied { constraint: Constraint { gate: Gate { index: 116, name: "LOG" }, index: 124, name: "State transition constraint of log_id" }, location: InRegion { region: Region { index: 6, name: "Execution step" }, offset: 51 }, cell_values: [(VirtualCell { name: "", column: Column { column_type: Advice, index: 23 }, rotation: 0 }, "1")] }])`

**Comment by ed255** [comment]
Does this bytecode create an exception in the EVM execution?
