### ISSUE TITLE
backlog: unify circuits naming

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#650]
Sometimes we use "XXCircuitConfig" as the struct containing columns and "XXCircuit" as the struct to containing witness(block), while sometime we use "XXCircuit" as the struct containing columns.

There are more inconsistency. Eg: EvmCircuit is the "proper" circuit without shared tables, and "TestCircuit" in evm_circuit.rs is the  "full(runnable)" circuit.   While for StateCircuit there is no "proper" circuit without shared tables. "StateCircuit" is the "full" circuit. 

I suggest XXCircuitConfig will be columns while XXCircuit be witness(block).   And we should  unify names like "MyCircuit"/"TestCircuit" to "BytecodeTestCircuit"/"EvmTestCircuit" later.

**Comment by aguzmant103** [comment]
Besides the above, also unify the name of the functions for how a circuit is configured and assigned. This is helpful to simplify the testnet.

**Comment by ed255** [comment]
Here's a summary of the current status:

| circuit  | columns struct     | witness struct      | config constructor            | assign fn                                                      | instance build        |
| ---      | ---                | ---                 | ---                           | ---                                                            | ---                   |
| EVM      | EvmCircuit         | (only test)         | EvmCircuit::configure         | EvmCircuit.assign_block(layouter, block)                       | -                     |
| State    | StateCircuitConfig | StateCircuit        | StateCircuitConfig::configure | StateCircuitConfig.assign(layouter, rws, ...)                  | -                     |
| Tx       | TxCircuitConfig    | TxCircuit           | TxCircuitConfig::new          | TxCircuit.assign(tx_circuit_cfg, layouter, ...)                | -                     |
| Bytecode | Config             | (only test)         | BytecodeConfig::configure     | BytecodeConfig.assign(layouter, ..., bytecodes)                | -                     |
| Copy     | CopyCircuit        | (only test)         | CopyCircuit::configure        | CopyCircuit.assign_block(layouter, block)                      | -                     |
| Exp      | ExpCircuitConfig   | ExpCircuit          | ExpCircuitConfig::configure   | ExpCircuitConfig.assign_block(layouter, block)                 | -                     |
| Keccak   | KeccakPackedConfig | KeccakPackedCircuit | KeccakConfig::configure       | KeccakConfig.assign_from_witness(layouter, keccak_inputs, ...) | -                     |
| PI       | PiCircuitConfig    | PiCircuit           | PiCircuitConfig::new          | PiCircuit.synthesize(pi_circuit_config, layouter)              | PiCircuit.instance    |
| Super    | SuperCircuitConfig | SuperCircuit        | SuperCircuit::configure       | SuperCircuit.synthesize(super_circuit_config, layouter)        | SuperCircuit.instance |

Aux tables assignment:
- Tables:
    - FooTable.load(layouter, values...)
- EVM:
    - EvmCircuit.load_fixed_table(layouter, values)
    - EvmCircuit.load_byte_table(layouter)
- State:
    - StateCircuitConfig.load(layouter)
- TxCircuit:
    - TxCircuitConfig.load(layouter)
- Bytecode:
    - Config.load(layouter)
- Keccak:
    - KeccakPackedConfig.load(layouter)

**Comment by lispc** [comment]
another issue is the capacity/size/padding_to/max_rws of circuits.

**Comment by ed255** [comment]
I've come up with these two traits that would be used to unify all circuits:
```rust
/// SubCircuit is a circuit that performs the verification of a specific part of
/// the full Ethereum block verification.  The SubCircuit's interact with each
/// other via lookup tables and/or shared public inputs.  This type must contain
/// all the inputs required to synthesize this circuit (and the contained
/// table(s) if any).
pub trait SubCircuit<F: Field> {
    /// Configuration of the SubCircuit.
    type Config: SubCircuitConfig<F>;

    /// Returns the instance columns required for this circuit.
    fn instance(&self) -> Vec<Vec<F>> {
        vec![]
    }
    /// Assign the columns used by this circuit.  This includes the columns that
    /// belong to the exposed lookup table contained within, if any.
    fn assign(
        &self,
        config: &Self::Config,
        challenges: &Challenges<Value<F>>,
        layouter: &mut impl Layouter<F>,
    ) -> Result<(), Error>;
}

/// SubCircuit configuration
pub trait SubCircuitConfig<F: Field> {
    /// Config constructor arguments
    type ConfigArgs;

    /// Type constructor
    fn new(meta: &mut ConstraintSystem<F>, args: Self::ConfigArgs) -> Self;
}
```

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/937
