### ISSUE TITLE
Circuit verification failing due low k

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/zkevm-circuits#657]
When doing benchmark tests on the SuperCircuit https://github.com/privacy-scaling-explorations/zkevm-circuits/tree/feature/super_circuit_2 happens that the circuit verification https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/b0cd131325dd03b4b042473743e84e01de218aa8/circuit-benchmarks/src/super_circuit.rs#L104-L110 fails the assertion `assert!(bases.len() >= size);` located in

https://github.com/privacy-scaling-explorations/halo2/blob/f586922d19c3c96ffcec4adbe1790132565ffba6/halo2_proofs/src/poly/commitment.rs#L307

I tried to increase the `k` (+1, +2) but does not work.

cc/ @han0110

**Comment by lispc** [comment]
I guess it is due to incorrect public input size used to generated ParamsVerifier.. i talked this issue with Edu before.. Let me check more

**Comment by lispc** [comment]
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/b0cd131325dd03b4b042473743e84e01de218aa8/circuit-benchmarks/src/super_circuit.rs#L74    I think it is incorrect. This is the public input size. Degree * 2 makes no sense

**Comment by pinkiebell** [comment]
That should be `1 << DEGREE`.

**Comment by lispc** [comment]
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/b0cd131325dd03b4b042473743e84e01de218aa8/zkevm-circuits/src/super_circuit.rs#L278

seems `(1 << DEGREE) - 64`
