### ISSUE TITLE
Add missing circuits to benchmarks

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#666]
We have benchmark tests defined here:
https://github.com/privacy-scaling-explorations/zkevm-circuits/tree/main/circuit-benchmarks/src

We need to include the following circuits:
- [x] PublicInputs #830 
- [x] Bytecode https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/807
- [x] Copy #899
- [x] full Keccak #634
- [ ] Exp Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/980

**Comment by xiaodino** [comment]
We are working on it.

**Comment by ed255** [comment]
> @ed255 looks like all missing benches are done. Do we need exp circuit bench as in #980?

Thanks for reviewing this!  We should have benches for all circuits.  Let me extend this issue to include the Exp Circuit and once it's merged we can close this :)
