### ISSUE TITLE
Move mock_tx creation to `mock` crate

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#677]
After checking #641 I saw that the generation for random Txs is not using the mock crate for testing purposes. Which was specifically designed for this.

I think it would be nice to try to see if we could move all the Tx/Block generation into the `mock` crate and so fave  a unique place where we define all of the mocking/testing utilites for the different components.

**Comment by CPerezz** [comment]
How does it sound @ChihChengLiang @han0110 ?

**Comment by ChihChengLiang** [comment]
Sounds like a good idea
