### ISSUE TITLE
Use testing setup/teardown to load things like DEGREE or Randomness

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#685]
Instead of doing this on each test, why don't we use a crate like: https://github.com/markhildreth/test-context to do test setup/teardown?

_Originally posted by @CPerezz in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/654#discussion_r946674477_

The usage of testing setup/teardown is nothing new at all and we could reduce quite a lot the amount of code that we have and will have in the future in all the async tests we're writing.

My suggestion of the test-context crate is due to the fact that it only requires derive macros (is easy to use) and also will significantly simplify the randomness sharing.

**Comment by CPerezz** [comment]
@ChihChengLiang @han0110 do you think this makes sense??

**Comment by ChihChengLiang** [comment]
What's inside the setup step and the teardown step in our cases?

**Comment by CPerezz** [comment]
> What's inside the setup step and the teardown step in our cases?

The obtention of the DEGREE and the randomness as well as the generation of a setup (if needed) or any other thin that is shared cross tests and repeated over and over.

**Comment by CPerezz** [comment]
After discussing with @ed255 we're closing this as there's not enough code repeatead across tests so that it's really worth it to use setup/teardown infra.
