### ISSUE TITLE
Keccak hashing impl proposal fom Circuit Input Builder (2) not from MPT

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-circuits#697]

**Comment by aguzmant103** [comment]
Dependencies:
- Specify MPT circuit inputs

Useful link: https://github.com/privacy-scaling-explorations/mpt-witness-generator

**Comment by ed255** [comment]
> Dependencies:
> 
>     * Specify MPT circuit inputs
> 
> 
> Useful link: https://github.com/privacy-scaling-explorations/mpt-witness-generator

Actually this note belongs here https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/696 :P (I just copied it there)
