### ISSUE TITLE
Implement RETURNDATASIZE

### ISSUE THREAD

**Issue by Brechtpd** [privacy-scaling-explorations/zkevm-circuits#698]

**Comment by barryWhiteHat** [comment]
@xiaodino and @smtmfft are gonna work on this one

**Comment by xiaodino** [comment]
Completed in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/703

**Comment by ChihChengLiang** [comment]
Thanks for the contribution @xiaodino!
