### ISSUE TITLE
Run integration tests in self hosted runner

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#707]
Recently we added a self hosted runner in order to accelerate the testing times from the github actions that are required for the PRs.

We have another github action that is only run after a commit is merged into main that runs the Integration Tests: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/.github/workflows/integration.yml
Lately these tests reach the memory limits of github runners, so they cause an Out of Memory and crash.  This was expected because as we keep developing the circuits the CPU and memory requirements grow.

It would be ideal if the Integration Tests that are triggered when a commit is merged to main would run in our self hosted runner (which has more memory than github runners), so that we avoid the OOM crash.

**Comment by ntampakas** [comment]
I launched a self hosted runner (36VCPUs and 72G of RAM.

**Comment by ntampakas** [comment]
Just a note regarding the the memory consumption during the tests execution. (the instance that was used has 36VCPUs and 72G of RAM)

![image](https://user-images.githubusercontent.com/9750541/187941787-533dca40-bcd9-40be-92ff-f5c6d357c162.png)

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/731
