### ISSUE TITLE
refactor: move witness.rs and BaseConstraintBuilder out of evm_circuit dir

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#708]
orignally they are used for evm circuit only. But later other circuits use them too. So it will be cleaner to move to a more common location

**Comment by ChihChengLiang** [comment]
Sounds like a good idea to me. @CPerezz or @ed255, comment on this?

**Comment by CPerezz** [comment]
Makes sense if we can reuse it! Are you planning to work on this @lispc ? Or should we take this?
