### ISSUE TITLE
Check end_block's rw_counter when block contains only one tx 

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#721]
@ed255 find that end_block state 's  `rw_counter` assigning depends on if the tx is the last tx. if there is only one tx, such tx is both the first and the last , it is likely to have problems. refer to [comment](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/713#issuecomment-1228628123) 

```
 Some(iter::once(ExecStep { 
     // if it is the first tx,  less 1 rw lookup, refer to end_tx gadget 
     rw_counter: tx.steps().last().unwrap().rwc.0 + 9 - (id == 1) as usize, 
     execution_state: ExecutionState::EndBlock, 
     ..Default::default() 
 })) 
```

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/728
