### ISSUE TITLE
newbie question regarding how zkevm works

### ISSUE THREAD

**Issue by zeroxaa** [privacy-scaling-explorations/zkevm-circuits#732]
hey, I understand one usecase of zkevm circuit project is to generate the proof offchain and verify it onchain via solidity code, that means the circuit itself should be independent of specific block data, in that way we can generate the vk from the circuit and put the vk in verifying contract. While i am looking at some implementation for example pi_circuit.rs, it contains public block data as part of the circuit, that means vk for pi_circuit is not a fixed thing. am i missing something? can someone shed light on how it should work? thanks.

**Comment by CPerezz** [comment]
Best I can provide is some intro docs I made that I have pending to be published.

See: https://hackmd.io/SJ0e7p_dS9y3ZIq-MmXm4Q?view
