### ISSUE TITLE
MPT: Add MPT to Main

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-circuits#740]
Proposal:
- Get it merge as fast as possible
- Do a very quick review (like tests taking too long)
- Then find the gaps with the spec and address them in another task
- A proper review pending in the future once the specs are ready

**Comment by aguzmant103** [comment]
This task:
- Prepare PR (unit tests, lints, checks passing)
- Quick Review

**Comment by ChihChengLiang** [comment]
Close in favor of #1416
