### ISSUE TITLE
SuperCircuit: Integration of Tables and Subcircuits

### ISSUE THREAD

**Issue by andyguzmaneth** [privacy-scaling-explorations/zkevm-circuits#747]
Currently the SuperCircuit contains the State and Copy circuits, but it seems that the rw_table and copy_table are duplicate.  The tables should be de-duplicated and reused between the EVM and State Circuit (for rw_table), and EVM and Copy Circuit (for copy_table)

**Comment by aguzmant103** [comment]
Likely need to split this task into further ones.
