### ISSUE TITLE
Add the Super Circuit to the set of integration tests

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#749]
Add the Super Circuit to the integration test macro here https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/6abc33eeb81ffd64ff73f2a84c04203f33c161eb/integration-tests/tests/circuits.rs#L176

**Comment by xiaodino** [comment]
We are working on it.

**Comment by ed255** [comment]
Resolved by https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/829
