### ISSUE TITLE
Refactor Keccak circuit with challenge API

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-circuits#751]
Using the challenge API instead of the instance value for randomness in Keccak circuit

Notes:
- The randomness will be provided from the super circuit instead of being queried from within the Keccak circuit. This applies to all the sub circuits
- Treat the randomness as an expression, need a small test.
- The circuit needs to be divided into 2 phases: one with the commitments that don't use the randomness; and another one that has access to the randomness and commits values that use it (via RLC).

**Comment by aguzmant103** [comment]
The randomness will be provided from the super circuit instead of being queried from within the Keccak circuit.

**Comment by aguzmant103** [comment]
Comments: treat the randomness as an expression, need a small test.

**Comment by ed255** [comment]
Reference example: https://github.com/han0110/halo2/blob/feature%2Fchallenge-api/halo2_proofs/examples/shuffle.rs

**Comment by aguzmant103** [comment]
Semi blocked by https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/926

**Comment by aguzmant103** [comment]
Notes: there are 3 Keccak implementations
- Already migrated bit implementation
- going to do the multi keccak. 
- Ignore the 3rd keccak implementation
