### ISSUE TITLE
Refactor Tx circuit with challenge API

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-circuits#752]
Using the challenge API instead of the instance value for randomness in Tx circuit

Notes:

- The randomness will be provided from the super circuit instead of being queried from within the Keccak circuit. This applies to all the sub circuits
- Treat the randomness as an expression, need a small test.
- The circuit needs to be divided into 2 phases: one with the commitments that don't use the randomness; and another one that has access to the randomness and commits values that use it (via RLC).

**Comment by ed255** [comment]
Reference example: https://github.com/han0110/halo2/blob/feature%2Fchallenge-api/halo2_proofs/examples/shuffle.rs
