### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-circuits#788]
See [commit history](https://github.com/privacy-scaling-explorations/zkevm-circuits/commits/main)
It first failed after #748 because of missing golang in CI. After that was fixed, these tests are failing:
- serial_test_copy_circuit_erc20_openzeppelin_transfer_succeed
- serial_test_copy_circuit_multiple_erc20_openzeppelin_transfers

A few commits in between could been the source of the errors...

**Comment by ed255** [comment]
Here's the log from the CI:
```
test serial_test_copy_circuit_erc20_openzeppelin_transfer_fail ... ok
thread 'serial_test_copy_circuit_erc20_openzeppelin_transfer_succeed' panicked at 'assertion failed: test_copy_circuit(DEGREE, block).is_ok()', integration-tests/tests/circuits.rs:135:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test serial_test_copy_circuit_erc20_openzeppelin_transfer_succeed ... FAILED
thread 'serial_test_copy_circuit_multiple_erc20_openzeppelin_transfers' panicked at 'assertion failed: test_copy_circuit(DEGREE, block).is_ok()', integration-tests/tests/circuits.rs:135:5
```

**Comment by ChihChengLiang** [comment]
Confirm that tests pass before #762 but failed after.

**Comment by z2trillion** [comment]
Would it be possible to run the integration tests for the CI?

**Comment by ed255** [comment]
> Would it be possible to run the integration tests for the CI?

I think we can do that!  We originally moved them outside of the PR requirements because it was taking a long time, but since we've added our own workers the integration test doesn't take long.  For example, the last run finished in 4m 26s: https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/3110892852/jobs/5042567839

**Comment by ChihChengLiang** [comment]
Oh, @z2trillion do you mean to run the integration tests on every pr instead of `main` branch only?

**Comment by z2trillion** [comment]
I think any time the the main branch changes would be enough. I think it would be useful to catch integration test failures sooner.
