### ISSUE TITLE
Add real prover tests for the integration tests

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#789]
Currently we have 4 kinds of tests in this repository:
1. unit tests, using the mock prover.  Run for every PR
2. integration tests (using real blocks from geth), using the mock prover.  Run for every commit merged to main
3. benchmarks, using mock data and the real prover.  Run on demand via PR labels
4. testool, (using official Ethereum test vectors) using the mock prover.  Plan to run them daily

Sometimes we have bugs in our circuits that wont' show up in the mock prover but will appear in the real prover.  We should have tests using real data that use the real prover, which should be run either for every commit merged to main or daily.

The challenge here is that tests for the real prover require a machine with very high resources, so we should be smart about it.

**Comment by han0110** [comment]
An idea to save the resource for real prover is to fill the fixed table with only necessary values, to make the necessary `k` smaller.

**Comment by ed255** [comment]
I think we could start with the following steps:
- 1a. Duplicate the integration tests defined in https://github.com/privacy-scaling-explorations/zkevm-circuits/tree/main/integration-tests but using the real prover.
- 1b. Alternatively define some realistic setting and block data for tests.  This would require some thought, but would allow testing more special cases
- 2. Figure out the resources needed to run the tests
- 3. Setup the infrastructure to run the tests either when a commit is merged to main, or daily via a custom CI infrastructure

**Comment by han0110** [comment]
> I think this would only apply to the EVM Circuit?

Tx circuit should also need a large `k` I think, due to the lookup table required by `RangeChip`, but I think it's not so costly as EVM circuit to prove, so perhaps we can focus on EVM circuit if we'd like to reduce the real prover integration test time.

**Comment by pinkiebell** [comment]
For smaller blocks, the transaction circuit actually dominates all other circuits regarding the consumption of rows ℹ️

**Comment by han0110** [comment]
Ah that's true, a single ecdsa verification already cost more than `2<sup>16</sup>` rows, so we can't actually reduce Tx circuit's `k` by reducing its table.

**Comment by ed255** [comment]
@leolara is currently working on adding integration tests that use the real prover.
