### ISSUE TITLE
is_zero gadget strange constraint

### ISSUE THREAD

**Issue by themighty1** [privacy-scaling-explorations/zkevm-circuits#844]
Seems like even if the value is not zero, the returned expression will always be zero. This doesn't seem right:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/cbce4db203fef44d7f86383b79917394092902a5/gadgets/src/is_zero.rs#L83-L89

If `value` is e.g. 2,  then `is_zero_expression` is 0 and the returned expression is 0, which is not correct.
Or am I reading this incorrectly?

**Comment by roynalnaruto** [comment]
The returned expression is the constraint that needs to be satisfied, i.e. it has to be `0`.

The expression `is_zero_expression` tells you whether or not the value assigned to the gadget was `0` or not.

So we satisfy the constraint `value * is_zero_expression` for the two cases below, that is:
1. `value == 0 && is_zero_expression == 1`
2. `value != 0 && is_zero_expression == 0`

**Comment by themighty1** [comment]
@roynalnaruto , is the purpose of this gate to constrain the `value` to be zero?

If so, then why is the constraint satisfied when the value != 0 :
> 2. value != 0 && is_zero_expression == 0

**Comment by roynalnaruto** [comment]
Hi @themighty1 

The purpose is to create constraints for the gadget `is_zero`. So for both cases where `value == 0` and `value != 0`, that specific gate should resolve to `0`.
