### ISSUE TITLE
Refactor PublicInput Circuit with challenge API

### ISSUE THREAD

**Issue by davidnevadoc** [privacy-scaling-explorations/zkevm-circuits#851]
The Public Input Circuit uses 2 random values which are currently provided from the Super Circuit:
 1. `randomness`: Used  for word RLC encoding
 2. `rand_rpi`: Used to RLC encode the raw public inputs column.
 
 The second random value `rand_rpi` must be derived at a later phase, once raw public inputs column has been commited to. See the [Public Input spec diagram](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/public_inputs.rev1.png)

**Comment by kunxian-xia** [comment]
The `rand_rpi` must be generated after these words have been synthesized. Therefore, the `rpi_rlc_acc` column will be allocated in third phase, using code like this `let rpi_rlc_acc = meta.advice_column_in(ThirdPhase)`?

**Comment by kunxian-xia** [comment]
Are you going to make the `randomness` for Word RLC public? As the smart contract verifier need it to calculate the RLC(word) for tx fields. But there will be some circular dependency, as having `randomness` become the public instance of the pi circuit implies that we need to first send it to transcript.

**Comment by ChihChengLiang** [comment]
Let's move the discussion to #856. Feel free to reopen it if you like to add more to this thread.
