### ISSUE TITLE
circuit_benches benchmark failed

### ISSUE THREAD

**Issue by JSnobody** [privacy-scaling-explorations/zkevm-circuits#867]
When I run "make circuit_benches DEGREE=18", or "DEGREE=18 make evm_bench", I get an error:

thread 'evm_circuit::evm_circ_benches::bench_evm_circuit_prover' panicked at 'could not find current environment's bytecode', xxxxxxxxxxxx/zkevm-circuits/src/evm_circuit/execution/stop.rs:97:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test evm_circuit::evm_circ_benches::bench_evm_circuit_prover ... FAILED

failures:

failures:
    evm_circuit::evm_circ_benches::bench_evm_circuit_prover

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 7 filtered out; finished in 20.09s

**Comment by ChihChengLiang** [comment]
I can confirm this is reproducible on my device.

**Comment by JSnobody** [comment]
@ChihChengLiang How to solve it? Do you have any good suggestion?
Thank you!

**Comment by JSnobody** [comment]
Today, I check the records of recent code submissions, and find some modification about opcode.
So, I roll the code back to half a month ago and try to run. It works OK with committing information as
`commit cbce4db203fef44d7f86383b79917394092902a5 (HEAD)
Author: z2trillion <z2trillion@users.noreply.github.com>
Date:   Wed Oct 19 20:23:33 2022 -0400`

Thus, I think there is a bug about opcode or bytecode in the recent code(after Oct 19).
You can check it, and solve it.

Thanks.

**Comment by ChihChengLiang** [comment]
Hi @JSnobody,
Thanks for tracking down the bug! 

Is it the last commit that successfully passes the check? Is that a result of `git bisect`?
Are you interested in contributing and fixing this bug?

I'm currently busy with some other tasks so still couldn't look into this for some days.

**Comment by hero78119** [comment]
Based on `git bisect`, the first commit introducing the bug is 
https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/f0c1cf8d4f6e6189cd94838658cd410f482694e5

attach code diff link https://github.com/privacy-scaling-explorations/zkevm-circuits/compare/5549e71...f0c1cf8d

**Comment by hero78119** [comment]
`ConstraintSystemFailure` might related to this https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/790#issuecomment-1254931794

**Comment by CPerezz** [comment]
Isn't this solved by https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/887 already? I think we should close the issue. 

cc: @ed255

**Comment by ed255** [comment]
> Isn't this solved by #887 already? I think we should close the issue.
> 
> cc: @ed255

Yes! Thanks for the notice, this should be resolved now.  I'm closing the issue (and if there are future failures on the benchmarks we can open new issues).

Note that currently we're not running the benchmarks regularly so we may make changes that break them sometimes, but we plan to run them regularly in our infrastructure in the short-term (to quickly detect problems like this).
