### ISSUE TITLE
bug: padding not work in evm circuit

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#868]
reproduce:

set evm_circuit_pad_to to 2000, then

```
cargo test -p zkevm-circuits --all-features --release stop_gadget_simple -- --nocapture
```

it will reports ""evm circuit offset larger than padding: 2000 > 2000"

@ed255

**Comment by pinkiebell** [comment]
https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/795#pullrequestreview-1160065011

**Comment by ed255** [comment]
@lispc thanks for reporting this!  I think there are a few things I missed in the EndBlock PR related to fixed size evm circuit.  I'll try to work on top of @pinkiebell PR to address them
