### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-circuits#875]
[See workflow](https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/3377880208/jobs/5607397059#step:13:219)

**Comment by pinkiebell** [comment]
[Another workflow with the same error but more information](https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/3381189420/jobs/5614830134#step:13:247) 🤔

**Comment by ed255** [comment]
oh, the super circuit integration test takes a long time (like 50 minutes)... I think we'll have to disable it for PRs (a part from fixing the issue), and only let it run once the commit is merged to main.

**Comment by ed255** [comment]
> oh, the super circuit integration test takes a long time (like 50 minutes)... I think we'll have to disable it for PRs (a part from fixing the issue), and only let it run once the commit is merged to main.

I noticed that we're not using the `verify_par()` function from the mock prover!  That should give a significant speed-up on the integration tests when using the super circuit.
