### ISSUE TITLE
Add more super circuit unit tests

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#883]
- multiple txs == MAX_TXS
 - multiple txs < MAX_TXS
 - max_rws padding
 - evm_rows padding

**Comment by xiaowheat** [comment]
We are working on it.

**Comment by xiaodino** [comment]
We are working on it.

**Comment by aguzmant103** [comment]
@xiaodino just following up this week, is this in progress? Let us know if you don't have the bandwidth and we can reassign it on our side

**Comment by xiaodino** [comment]
Hi @aguzmant103 . Sorry for the late reply. I don't have the bandwidth due to other developments. Please reassign it. Thanks.

**Comment by aguzmant103** [comment]
Thanks @xiaodino !
