### ISSUE TITLE
Review missing parts to make ETH transfers works

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#891]
The scope of the current milestone includes supporting ETH transfers.
Currently the integration tests for single and multiple ETH transfers in a block don't pass: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/890

**Comment by aguzmant103** [comment]
- Currently we have integration tests that automatically check on every PR.
- The block doing transfers is disabled on this test.
- The transfers is failing.
- The scope of this issue is reviewing the missing parts and fixing them.

**Comment by aguzmant103** [comment]
@han0110  has a PR to fix disables to empty accounts.
