### ISSUE TITLE
Example / insight into doing a MPT proof verification for existing state

### ISSUE THREAD

**Issue by drewstone** [privacy-scaling-explorations/zkevm-circuits#892]
Hi,

I'm looking to find (if any) circuits that would be useful in verifying a proof of data in the MPT. I don't want to verify updates to any MPT rather just read data and verify existence. This would ideally be paired with `eth_getProof` in spirit. Is there any insight or examples of verifying state in this repo?

**Comment by ed255** [comment]
Hi @drewstone 
We have an MPT circuit in the works, but it isn't ready yet.  You can track it's progress via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/398

Once the MPT circuit is ready it should serve your purpose of proving existence of account fields and storage keys.  You can check the API that the MPT circuit exposes (via a lookup table) here to see the kind of proofs it supports: https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/tables.md#mpt_table

Once the MPT circuit PR is merged we may have tests that serve as examples for verifying MPT proofs of existence.

**Comment by ChihChengLiang** [comment]
Close for inactivity.
