### ISSUE TITLE
math gadgets refactory, for better code structure and unit test coverage.

### ISSUE THREAD

**Issue by smtmfft** [privacy-scaling-explorations/zkevm-circuits#900]
The unit test task was initialized by #586, and we already created a unit test framework PR #865 . 
However, as the comment tells.

> @smtmfft IMO we should also refactor the `math_gadget` module into modules per gadget in it, mainly to lower the lines-of-code in the entire module. What do others think about this? If yes, I'm happy to do this in a separate PR, or this can be done within #865 as well.

_Originally posted by @roynalnaruto in https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/586#issuecomment-1296590176_

Now, the math gadgets part should be refactoryed for better code structure. So I create this task issue.

**Comment by smtmfft** [comment]
To avoid conflict, if nobody else is now working on the refactory, we will do that as we already implemented the math gadget unit test. Otherwise, we can merge the unit test into the refactory branch.

**Comment by ChihChengLiang** [comment]
Completed by #920
