### ISSUE TITLE
keccak/plain: incremental update() broken

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-circuits#922]
Using  `keccak256::plain::Keccak` yields different hashes if `update()` is used multiple times for the same data vs updating once with one large vector(same data). Is this indented?

**Comment by han0110** [comment]
I think it's a bug, so this padding logic

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/3b06585106417a398a0af37422dc1fcadf5a614c/keccak256/src/plain.rs#L26-L32

needs to be moved to [`Sponge::squeeze`](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/3b06585106417a398a0af37422dc1fcadf5a614c/keccak256/src/plain.rs#L151).
