### ISSUE TITLE
Remove the custom CellManager API defined for Keccak MultiPacked impl

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#933]
While migrating `KeccakMultiPacked` circuit  to support the Challenge API, I came across the custom `CellManager` type as well as `CellColumn` and `Cell`, `KeccakRegion` etc...

After chatting with @Brechtpd a bit about that, we belive that even the functionallity is not exactly the same one, we should try to find a way on which we can better abstract the `CellManager` so that we don't have different implementations of it for different circuits.

Note that we have [`CellManager` of the KeccakMultiPacked](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/keccak_circuit/keccak_packed_multi.rs#L203-L209) and we do also have define for the `EVM Circuit` [here](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/util.rs#L218-L224).

Note that this not only happens to the `CellManager` but also to all of the related types: `CellColumn`, `Cell`, `CachedRegion` etc..

This also can make easier to integrate it with the Challenge API as it's difficult to manage it for EVM Circuit, and it's mainly due to the `CellManager` that controls everything there.

The main goal would be to abstract the `CellManager` so that we define an interface that serves for both use cases and that shares behaviour across them. Also, this could be useful as we could plan a slightly bigger re-write of it that also takes care of the `Challenges` on a more ordered manner.

**Comment by ed255** [comment]
Related to https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1203

**Comment by ChihChengLiang** [comment]
Close in favor of #1203
