### ISSUE TITLE
`CALL` & `CALL` OOG refactor

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/zkevm-circuits#940]
Currently `callop.rs` and `error_oog_call.rs` (and probably more to come) are sharing an important amount of code.
It will be nice to refactor both.

**Comment by ChihChengLiang** [comment]
Spec here https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/execution/callop.py . Assign to @KimiWu123
