### ISSUE TITLE
Add benchmarks support for SuperCircuit 

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#943]
We currently don't have a label that triggers only `SuperCircuit` benchmarks. And this is required in order of for example, accomplish tasks like https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/941.

Therefore, this functionality should be added.

cc: @ntampakas @AronisAt79  I guess the functioning will still be the same as for all other benchmarks right? Do we need to have any special considerations for what refers to the reports?? And, is the machine still dedicated to the benchmarks??

**Comment by AronisAt79** [comment]
> We currently don't have a label that triggers only `SuperCircuit` benchmarks. And this is required in order of for example, accomplish tasks like #941.
> 
> Therefore, this functionality should be added.
> 
> cc: @ntampakas @AronisAt79 I guess the functioning will still be the same as for all other benchmarks right? Do we need to have any special considerations for what refers to the reports?? And, is the machine still dedicated to the benchmarks??

@Carlos Hi Carlos! Yes, the machine is still dedicated to those tests. The super circuit bench profile is implemented in the workflow scripts. I think we re only missing a label of the form "benchmarks: Super", is that correct? Can you try to create the label for your PR of interest?

**Comment by CPerezz** [comment]
The label has been created and it's being used in #941 successfully.
