### ISSUE TITLE
Hide `Circuit` implementation of sub-circuits behind `test` feature

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-circuits#953]
After https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/937 we no longer need the implementation `Circuit` for sub-circuits in production, it's only required for test and crates `circuit-benchmarks` to benchmark individual sub-circuit, so we should move current implementation into `#[cfg(any(feature = "test", test))] mod test { ... }` to avoid further consumers to use them accidentally.

**Comment by CPerezz** [comment]
I'm totally in favor of that change!

**Comment by ChengYueJia** [comment]
Hi, I can do it.

**Comment by CPerezz** [comment]
NOTE that `circuit-benchmarks` will need to import `zkevm-circuits` with `test` feature!

Assigning to @ChengYueJia then!

**Comment by ChengYueJia** [comment]
@CPerezz @han0110 
You can have a view #1003

**Comment by leolara** [comment]
@han0110 @ChengYueJia Doesn't SuperCircuit get used outside the tests to run the actual system?

**Comment by leolara** [comment]
But then, my question is SuperCircuit uses the Circuit implementation of the other SubCircuits:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/super_circuit.rs#L269-L276

so all these, should not be only in the tests, but also in production, right?

**Comment by han0110** [comment]
But `new_from_block` is method of `SubCircuit`, which doesn't require the struct to implement `Circuit`, or is there anything inside these implementation requires `Circuit` implementation?

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1300
