### ISSUE TITLE
Integration test of EVM circuit should cache the proving/verifying keys

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/zkevm-circuits#967]
This requires to calculate the minimum grade of the circuit that works for all the blocks in the integration test.

**Comment by ed255** [comment]
This issue may not be completed successfully (as in integration tests passing) until this is resolved https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/986

**Comment by leolara** [comment]
Summary: EVM circuit halo2 code seems to generate different circuit setups when created with different witnesses.

Running all the integration tests gives that the maximum degree required is 18. So a constant is created like for other integration tests:

```
const EVM_CIRCUIT_DEGREE: u32 = 18;
```

And a singleton for the pk is created as for other tests:

```
static ref EVM_CIRCUIT_KEY: ProvingKey<G1Affine> = {
        let block = new_empty_block();
        let circuit = EvmCircuit::<Fr>::new_from_block(&block);
        let general_params = get_general_params(EVM_CIRCUIT_DEGREE);

        let verifying_key =
            keygen_vk(&general_params, &circuit).expect("keygen_vk should not fail");
        keygen_pk(&general_params, verifying_key, &circuit).expect("keygen_pk should not fail")
    };
```

The integrations tests when run with the actual prover give a `ConstraintSystemFailure` for all the tests of EVM circuit:

```
test real_prover::serial_test_evm_circuit_erc20_openzeppelin_transfer_fail ... FAILED
thread 'real_prover::serial_test_evm_circuit_erc20_openzeppelin_transfer_succeed' panicked at 'proof generation should not fail: ConstraintSystemFailure', /home/ubuntu/src/zkevm-circuits/integration-tests/src/integration_test_circuits.rs:184:10
```

This error cannot be debugged as it does not happen with the `mock_prover`.

I try to run with an actual block instead of the empty block to see if the empty block might be causing a problem in the setup:

```
   static ref EVM_CIRCUIT_KEY: AsyncOnce<ProvingKey<G1Affine>> = AsyncOnce::new(async {
        let block_tag = "Transfer 0";
        let block_num = GEN_DATA.blocks.get(block_tag).unwrap();
        let (builder, _) = gen_inputs(*block_num).await;

        let block = block_convert(&builder.block, &builder.code_db).unwrap();
        let circuit = EvmCircuit::<Fr>::new_from_block(&block);
        let general_params = get_general_params(EVM_CIRCUIT_DEGREE);

        let verifying_key =
            keygen_vk(&general_params, &circuit).expect("keygen_vk should not fail");
        keygen_pk(&general_params, verifying_key, &circuit).expect("keygen_pk should not fail")
    });
```

Now in the actual prover the result is that the test based on that block passes, but the rest fail. Still all of them pass with the mock_prover.

This lead me to think that the circuit constrains or the fixed column are being genereted differently depending on the witness.

Solving this is out of scopre of this issue.

**Comment by leolara** [comment]
Blocked by https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1122

**Comment by leolara** [comment]
What is referred above has been implemented in branch: https://github.com/privacy-scaling-explorations/zkevm-circuits/tree/leo/integration-tests-cache-keys-evm

Comparison: https://github.com/privacy-scaling-explorations/zkevm-circuits/compare/leo/integration-tests-cache-keys-evm

**Comment by ed255** [comment]
Following @han0110 comment, I suggest replacing `Block.evm_circuit_pad_to` by a new `max_evm_rows` in `CircuitsParams`, so that we have all the circuits parameters in the same place; and then avoid using a 0 / auto value and instead setting an appropriate value here: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/27a9173dc5bc61501228b1d97da0783cc6257bdb/integration-tests/src/integration_test_circuits.rs#L48-L55

Also I see that we have `keccak_padding: None` in the integration tests, we should also change that for an appropriate value to get a constant keccak circuit.

**Comment by leolara** [comment]
Created issue about @ed255 comment re keccak https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1128

**Comment by aguzmant103** [comment]
Blocked by https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1122
