### ISSUE TITLE
refactor: better rows estimation

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#982]
update 2022.12.14: evm circuit rows estimation is fixed. 

TODO:
 
1. refactor row estimation codes in super circuit
2. add "estimate_rows" as a trait method for tables/subcircuits?
3. we'd better distinguish the rows need without padding and with padding. Log::debug them both? They are both informational

===== 

copy table not included.

More generally, we can refactor the codes on "each module/table costs how many rows". 

TODO: 

print 2 type of debug logs:

1. for each table/submodule, we **manually** estimate the rows needed. Like sum(get_height(each_opcode)) for evm circuit, and block.copy_events.bytes.map(|c| c.len()).sum() for copy table. It is quick, but needed manual code maintainence for consistency. done: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/983
4. print the row_count() of RegionShape automatically.  done: https://github.com/scroll-tech/halo2/pull/16/commits/15dd97605554b9170c2f69cb26bf45e8b7f405a4

**Comment by rrzhang139** [comment]
@lispc Would like to take a stab at it. Could you provide a bit more context on the refactoring row estimation for evm circuit? Are you saying we instead refactor the get_num_rows_required() in super_circuit to call the trait method estimate_rows for evm_circuit and tx_circuit?

**Comment by ed255** [comment]
> Would like to take a stab at it. Could you provide a bit more context on the refactoring row estimation for evm circuit? Are you saying we instead refactor the get_num_rows_required() in super_circuit to call the trait method estimate_rows for evm_circuit and tx_circuit?

@rrzhang139 I addressed some of the points of this issue in this PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/994

In particular I added a `min_num_rows_block` function to each circuit which returns the minimum number of rows required to prove a block.  It's not a trait method, but it could be made into one.  Also I only did it for the circuits, not for the tables (just to clean up a bit the super circuit `k` value estimation)

**Comment by lispc** [comment]
you may use lazy_static to store the height_map somewhere so don't need to recalculate it each time

**Comment by ChengYueJia** [comment]
> you may use lazy_static to store the height_map somewhere so don't need to recalculate it each time
Thx for reminding it. I ganna send a pr.

**Comment by zemse** [comment]
Is this issue still up for contributions?

**Comment by ChihChengLiang** [comment]
We can close this issue:
- We have already implemented the SubCircuit trait for all circuits, and it has a min_num_rows_block method that gives the information on the minimum rows used. 
- The RegionShape statistics should be a Halo2 feature. Something like this will help resolving the issue https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/ef143529304544a18416aa96ba0c6dfa9872a77b/zkevm-circuits/src/tx_circuit/sign_verify.rs#L89
