### ISSUE TITLE
refactor: unify table dev_load and real assignment

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#984]
for tables like tx table and keccak table, when we change the table layout later, we need to change codes both in dev_load and real assignment. Maybe error prone

**Comment by ChengYueJia** [comment]
Hi, I wanna do it.

But with some questions here: 

1. What's the difference between `dev_load` and the real assignment?
2. I've seen the table can be assigned in two ways. What's the different between them?
    * The fisrt is the table is assigned while its associated circuit is assigned.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/0778f85fe9ad326d8284e8c57f1d5f9f46b5db33/zkevm-circuits/src/exp_circuit.rs#L338
   * The second is the table is assigned by invoking its `load` method.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/0778f85fe9ad326d8284e8c57f1d5f9f46b5db33/zkevm-circuits/src/evm_circuit.rs#L365
3. For unifying, can we unify the `assign` related method by defining them in the `LookupTable` trait?

**Comment by ChengYueJia** [comment]
> for tables like tx table and keccak table, when we change the table layout later, we need to change codes both in dev_load and real assignment. Maybe error prone

* for tx_table, it's blocked by #1034, 
       As in real-assign, it's assigned the eth-type::Transaction.
       As in dev-assign, it's assigned the witness::Transaction
* As for keccak_table,  Provide the `dev_load` for the case that we want to consume a keccak table but without running the full keccak circuit.
       It's better for us to remove it?

**Comment by ChihChengLiang** [comment]
Addressed in #1402
