### ISSUE TITLE
bug(super circuit): evm circuit / rw table / mpt table / block table assigned twice

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#987]
maybe this line should be removed https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/c78c86dfb7bc9198c0e7b0fcc5e7ecfd21277893/zkevm-circuits/src/super_circuit.rs#L304

Assigning to same columns in two region, can result the assigned "matrix" repeat twice vertically. At least it costs twice rows without any furthur problems if any

**Comment by han0110** [comment]
Yes I think this is duplicated and should be removed, but I wonder how current `SuperCircuit` pass the integration test, I guess it's because `q_usable` is not enabled in the final row (the row right after `q_last_step`), so the transition from `EndBlock` to `BeginTx` is not causing failure.

**Comment by lispc** [comment]
oh i find rw_table / mpt_table also assigned twice in super circuit, once in state circuit, once standalone.. Will fix them next PR..

**Comment by ChengYueJia** [comment]
Hi, all.
I've seen the some table(like exp_table) can be assigned in two ways. Is this a bug?

* The fisrt is the table is assigned when its associated circuit is assigned.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/0778f85fe9ad326d8284e8c57f1d5f9f46b5db33/zkevm-circuits/src/exp_circuit.rs#L338

* The second is the table is assigned by invoking its `load` method.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/0778f85fe9ad326d8284e8c57f1d5f9f46b5db33/zkevm-circuits/src/evm_circuit.rs#L365


https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/984#issuecomment-1363748474

**Comment by kunxian-xia** [comment]
It's not a bug, as the second one is loaded in the EVM test circuit (not in the super circuit).

**Comment by ChengYueJia** [comment]
> It's not a bug, as the EVM test circuit does not include the `synthesize_sub` of exp circuit.

The above seems like will be assigned twice in non-test situation.

**Comment by kunxian-xia** [comment]
After a quick search, the only place that `exp_table.load` function is called is in the EVM test circuit.
