### ISSUE TITLE
bug:  balance's `test_balance_of_non_exists_address` is wrong

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#988]
there are two errors for `test_balance_of_non_exists_address` here https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/balance.rs#L66
1. no push operation, this test encounter stack underflow error. since this error was caught so not panic.
2. If the given account doesn't exist, it will push 0 onto the stack instead.  not empty stack in https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/balance.rs#L93

**Comment by ChihChengLiang** [comment]
Fixed in #989
